### ISSUE TITLE
Please include <climits> for CHAR_BIT

### ISSUE THREAD

**Issue by toge** [stephenberry/glaze#100]
`glaze/api/hash.hpp` uses `CHAR_BIT`.

```C++
   template <class T, T Value, size_t... Is>
   consteval auto make_array_impl(std::index_sequence<Is...>) {
      return std::array<char, sizeof(T)>{ static_cast<char>(((Value >> (CHAR_BIT * Is)) & 0xff))... };
   }
```

CHAR_BIT is defined in `<climits>`.
Before 0.2.4, it was included by fmtlib.
Because glaze doesn't require fmtlib since 0.2.4, there is no explicit place where includes `<climits>`.
This causes compilation error in several environments.

Could you include `<climits>`? (ex. glaze/api/hash.hpp)

**Comment by mwalcott3** [comment]
Done, thanks for pointing this out.
