### ISSUE TITLE
 error: constructor priorities are not supported  3316 |                                                        const char* argv[])

### ISSUE THREAD

**Issue by AmdRyZen** [stephenberry/glaze#1034]
macos 14    
m2 pro 
gcc 14.1 
glaze/build/_deps/ut-src/include/boost/ut.hpp:3316:74: error: constructor priorities are not supported
 3316 |                                                        const char* argv[])

**Comment by stephenberry** [comment]
Is this a `ut.hpp` issue with gcc 14.1? It probably should be posted over there: [boost ut](https://github.com/boost-ext/ut)

I'll also note that you don't need `ut` to use Glaze, but I understand if you're trying to build and run unit tests as examples.

**Comment by AmdRyZen** [comment]
ok

**Comment by stephenberry** [comment]
I'm moving to a new implementation of [ut](https://github.com/openalgz/ut) that should avoid these issues in #1041
