### ISSUE TITLE
gcc and msvc compilation error with explicit constructors 

### ISSUE THREAD

**Issue by stevem2t** [stephenberry/glaze#1035]
Hello,
Please consider the following:
``` cpp
#include <glaze/glaze.hpp>
#include <filesystem>
struct S1
{
	int    a{};
	int    b{};
	std::filesystem::path   fn{};
};
static_assert( glz::detail::count_members<S1> == 3 );
```
Does not compile under gcc 13 & 14 (and maybe more compilers).
Because count_members returns 2... (and of course tuplification is broken you would have guessed)

Here is what I think is the adequate fix:
``` patch
--- a/include/glaze/reflection/to_tuple.hpp
+++ b/include/glaze/reflection/to_tuple.hpp
@@ -51,7 +51,7 @@ namespace glz
          requires(std::is_aggregate_v<std::remove_cvref_t<T>>)
       inline constexpr auto count_members = [] {
          using V = std::remove_cvref_t<T>;
-         if constexpr (requires { V{{Args{}}..., {any_t{}}}; } == false) {
+         if constexpr (requires { V{Args{}...,any_t{}}; } == false) {
             return sizeof...(Args);
          }
          else {
```
Hopefully no regression for decent compilers...
Enjoy, and best!
(and pardon me for not making a fork + PR for a one-liner ;-) )

**Comment by stevem2t** [comment]
Note that I used fs::path as an example, but many more objects have the problem.
And yes I am also seeing some subtleties with structures containing `const char*` members (for serialization only) :-P so the patch is NOK. (so bad ... should have run unit tests !).

This issue is a bit tricky...
I also attempted to get rid of the any_t, but without much success (trying to do structured bindings inside lambdas inside require clauses... ).

**Comment by stephenberry** [comment]
After digging into this, to the best of my understanding this is a compiler bug in GCC (and MSVC). Clang builds fine with your example code.

The section of the standard that seems to indicate this is a bug in GCC is from [section 12: Overloading](https://eel.is/c++draft/over.ics.list)

> [3.](https://eel.is/c++draft/over.ics.list#3.sentence-1) Otherwise, if the parameter type is an aggregate class X and the initializer list has a single element of type cv U, where U is X or a class derived from X, the implicit conversion sequence is the one required to convert the element to the parameter type.

In the `count_members` code we have a single argument in the initializer list with a direct implicit conversion to the element of the parameter type, so it should not be ambiguous as GCC is saying.

I'll report this bug to MSVC and GCC. In the meantime, use the glaze metadata solution for these kinds of issues. Hopefully it will be fixed sooner than later.

Here is a compiler explorer link with a simple example showing the issue: https://gcc.godbolt.org/z/TeKz6Ee37

**Comment by stevem2t** [comment]
Indeed, with 2 compilers behaving differently, either the spec needs precisions or there is at least one compiler bug !
I have multiple workarounds, so no real hurry. I can probably even use my patch and drop C-array support for now.

It would be great if we could drop the any_t and write something simple like...

``` cpp
template<typename T>
constexpr size_t count_members = []{
  if constexpr( false ) {}
  else if constexpr( requires{ []{ auto[a]     = T{}; }; }) return 1;
  else if constexpr( requires{ []{ auto[a,b]   = T{}; }; }) return 2;
  else if constexpr( requires{ []{ auto[a,b,c] = T{}; }; }) return 3;
  // ...
}();
```
yikes it works !!! at least on gcc...
and might even compile faster than the recursive template + any_t, even if handling 200+ different cases.
made my day :-)

**Comment by stephenberry** [comment]
Neat, I really like this idea! I'll test it with Glaze and compiler explorer and see how far it could take things.

**Comment by stephenberry** [comment]
So, I think the problem with your proposed solution is that the class needs to be default initializable. The current solution does not have this requirement. I'm testing using an extern template, but Clang doesn't like it saying `no definition is available`

**Comment by stevem2t** [comment]
Mmm... looks like it works... for N==1. Gcc makes terminal errors in the requires clauses if the structured binding does not match... IN THE REQUIRE CLAUSE !
```
<source>:45:40: error: only 1 name provided for structured binding
   45 |   else if constexpr( requires{ []{ auto[a]    = T{};  }; })
```

**Comment by stephenberry** [comment]
That sounds like a need for `requires { requires ([]{ auto[a]    = T{};  }); }`

**Comment by stephenberry** [comment]
We probably could use a combination of the current approach and this approach to add support for default initializable types. But, then things would fail if one of the fields was not default initializable.

**Comment by stephenberry** [comment]
Oh wait, the extern template solution seems to work with this approach, I just have to disable warnings locally because I had them as errors.

**Comment by stevem2t** [comment]
The default initializable is not an issue, just try to test for lambdas like:
` [](X&x){ auto& [a,b,c ] = x; } `
But gcc fails the compilation even if in a requires requires... soo bad... but we'll get that to work!

**Comment by stephenberry** [comment]
Nice, but that is another annoying GCC bug. I'll report this one as well.

**Comment by stevem2t** [comment]
You're my hero-porter !

**Comment by stephenberry** [comment]
Haha, well this bug exists for Clang and MSVC as well.

**Comment by stevem2t** [comment]
That makes only 5 compiler bugs for a small problem ! I like coding on the edge, haha...

**Comment by stephenberry** [comment]
It's great to push compilers! Thanks for your effort on trying to solve this!

**Comment by stevem2t** [comment]
You are welcome. Not that we really solved it but at least we understand the problem a bit better, and have found new ideas...

**Comment by stephenberry** [comment]
After a lot of experimenting I'm thinking the best solution is to break reflection for C style arrays. Using C style arrays in Glaze will require a `glz::meta` definition. I think this makes more sense because Glaze is a C++ library and users can in most cases change their C style arrays to use `std::array`. This also simplifies the member counting code so the compilers will act more similarly across MSVC, GCC, and Clang.

If users need C style array support, they can still do so manually through a `glz::meta` definition.

**Comment by stevem2t** [comment]
Glad to hear that, I came to the exact same conclusion ;-)
But I did not want to be pushy and say "just drop it ! who cares ?".

As long as it breaks the compilation when users have C arrays, nobody should be too much worried or affected...
And I agree, there is probably no need in supporting old legacy stuff like that in glaze, as well as no justification for really needing that in any C++ codebase...

**Comment by stephenberry** [comment]
Agreed, I'll make this change soon, and thankfully it will produce a compile time error so it shouldn't have runtime surprises.

**Comment by stephenberry** [comment]
Support is being added in #1097
