### ISSUE TITLE
rapidjson 对比

### ISSUE THREAD

**Issue by AmdRyZen** [stephenberry/glaze#1040]
我对比了好几个json 性能还是比 rapidjson  差一点 
用的是你们官方的  demo  是不是  rapidjson 没开启 simd
<img width="828" alt="image" src="https://github.com/stephenberry/glaze/assets/25969344/b07603f9-9055-4816-95f5-77e2cd7d3dcd">

**Comment by stephenberry** [comment]
I expect you are, but make sure you are benchmarking in Release mode. Also, you can improve Glaze performance if you can reuse your buffer and write:
```c++
glz::write_json(s, glaze); // where glaze is your buffer
```

Also, you should probably do more than 1000 iterations, that's not a lot for benchmarking such a cheap operation.

What compiler and platform are you?

**Comment by AmdRyZen** [comment]
gcc  14.1
macos  14  m2  pro 
不进行1000次 迭代 都在 1ns  看不出结果

**Comment by stephenberry** [comment]
What I mean is do like 100000 iterations, rather than 1000.

This is what I mean:
```c++
std::string glaze{}; // put your buffer here so that you don't constantly reallocate memory
for (size_t i = 0; i < 100000; ++i)
{
   glz::write_json(s, glaze);
}
```

Thanks for the platform details.

**Comment by AmdRyZen** [comment]
我找到你们的压测demo了  你们测试的是  反序列化的性能

**Comment by stephenberry** [comment]
Thanks for the update. Could you share the benchmark loop code for rapidjson? I'd like to run a similar test myself to see where the bottleneck is.

**Comment by AmdRyZen** [comment]
// rapidjson
    rapidjson::StringBuffer buf;
    rapidjson::PrettyWriter<rapidjson::StringBuffer> writer(buf);  // it can word wrap
    writer.StartObject();
    writer.Key("id");
    writer.Int(1);
    writer.Key("name");
    writer.String("a");
    writer.EndObject();
    const auto t5 = std::chrono::steady_clock::now();
    for (auto i = 0; i < 1000; i++)
    {
        buf.GetString();
    }
    const auto t6 = std::chrono::steady_clock::now();
    //纳秒级
    const double dr_ns2 = std::chrono::duration<double, std::nano>(t6 - t5).count();
    std::cout << "[rapidjson cost: " << dr_ns2 << " ns]" << std::endl;

**Comment by AmdRyZen** [comment]
我没事喜欢测试各种库的性能 。。。。

**Comment by stephenberry** [comment]
Oh, it looks like your rapidjson test is not setup properly. You are just accessing the internal buffer of the writer and not actually doing the serialization in your loop.

This code needs to be inside the loop:
```c++
writer.StartObject();
writer.Key("id");
writer.Int(1);
writer.Key("name");
writer.String("a");
writer.EndObject();
```

That's why rapidjson seems so fast, but it isn't doing any work in your loop.

**Comment by AmdRyZen** [comment]
buf.GetString();  不是吗   

struct my_struct
{
    int i = 1;
    /*double d = 3.14;*/
    std::string hello = "c";
    /*std::array<uint64_t, 3> arr = { 1, 2, 3 };
    std::map<std::string, int> map{{"one", 1}, {"two", 2}};*/
};

 // glaze
    my_struct s{};
    std::string buffer{};
    const auto t9 = std::chrono::steady_clock::now();
    for (auto i = 0; i < 1000; i++)
    {
        /*std::string glaze = */glz::write_json(s, buffer);
    }
    const auto t10 = std::chrono::steady_clock::now();
    //纳秒级
    const double dr_ns4 = std::chrono::duration<double, std::nano>(t10 - t9).count();
    std::cout << "[glaze cost: " << dr_ns4 << " ns]" << std::endl;

glaze    glz::write_json(s, buffer);  我 也是怎么做的啊

**Comment by AmdRyZen** [comment]
<img width="548" alt="image" src="https://github.com/stephenberry/glaze/assets/25969344/b9936b27-b3c6-4a9a-8100-42302cbb9453">



<img width="870" alt="image" src="https://github.com/stephenberry/glaze/assets/25969344/7730f871-938f-4e0e-a27c-d5afe2988d2d">

<img width="856" alt="image" src="https://github.com/stephenberry/glaze/assets/25969344/5e251414-7611-407a-962d-a4635437bf2d">

**Comment by AmdRyZen** [comment]
我还测试了 protobuf  json能有怎么快 很不错

**Comment by stephenberry** [comment]
This is a valid test and now if the fields in `my_struct s` change, both Glaze and rapidjson will have the right result, whereas before rapidjson wouldn't have shown any changes in `my_struct`.

**Comment by stephenberry** [comment]
I think protobuf json requires another layer of indirection to get to your C++ code, the conversion from protobuf to JSON might be fast, but you also have to account for your conversion from your C++ objects to protobuf. This double serialization tends to be slow.

**Comment by stephenberry** [comment]
Yes, if you are just using protobuf, it should be faster than JSON because it is a binary format. Glaze implements the [BEVE](https://github.com/beve-org/beve) binary format, which is often faster than protobuf. You can use `glz::write_binary` to test the binary (BEVE) performance.
