### ISSUE TITLE
Option to use partial with char* or char[]

### ISSUE THREAD

**Issue by pawcam** [stephenberry/glaze#1052]
Hello again.

I wanted to make sure I'm understanding the usage of the library correctly when using partials. For example, I have an API that takes a `char*` for performance and memory safety reasons in the overrarching app.
```
void serialize(Data* data, char* buf)
{
  static constexpr field1_partial json_ptrs("/field1")
  glz::write_json<field1_partial>(data, buf)
}
```

this code doesn't compile, and I believe it's due to this concept in container_concepts.hpp, namely failing `      requires !std::same_as<void, decltype(t.begin())>;` :
```
namespace glz
{
   template <class T>
   concept range = requires(T& t) {
      requires !std::same_as<void, decltype(t.begin())>;
      requires !std::same_as<void, decltype(t.end())>;
      requires std::input_iterator<decltype(t.begin())>;
   };
}
```

```
/include/glaze/json/write.hpp:1458:36:   required from ‘auto glz::write_json(T&&, Buffer&&) [with auto& Partial = field1_partial; T = Data&; Buffer = char*]’
 required from here /include/glaze/concepts/container_concepts.hpp:210:12:   required for the satisfaction of ‘range<Buffer>’ [with Buffer = char*]
/include/glaze/core/write.hpp:17:12:   required for the satisfaction of ‘output_buffer<Buffer>’ [with Buffer = char*]
/include/glaze/concepts/container_concepts.hpp:210:20:   in requirements with ‘T& t’ [with T = char*]
/include/glaze/concepts/container_concepts.hpp:211:16: note: nested requirement ‘! same_as<void, decltype (t.begin())>’ is not satisfied
  211 |       requires !std::same_as<void, decltype(t.begin())>;
      |       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/include/glaze/concepts/container_concepts.hpp:212:16: note: nested requirement ‘! same_as<void, decltype (t.end())>’ is not satisfied
  212 |       requires !std::same_as<void, decltype(t.end())>;
      |       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/include/glaze/concepts/container_concepts.hpp:213:16: note: nested requirement ‘input_iterator<decltype (t.begin())>’ is not satisfied
  213 |       requires std::input_iterator<decltype(t.begin())>;
```

This makes sense, since char* is not a struct. It also fails the `output_buffer` concept for similar reasons.

My question is why these concepts block usage for a more primitive type like `char *` as the output buffer only when using partials, but the following is a perfectly valid use:
```
glz::write_json(msg, buf);
```

**Comment by stephenberry** [comment]
This was just overlooked for partial writing, so I'll add in a function that supports raw buffers.

I actually need to make some write API changes to better support handling write errors. I'll probably include this support in that merge.

I'm curious, do you know your sizes? Could you be using `std::string_view`?

**Comment by pawcam** [comment]
As far as knowing sizes:
JSON tags: yes
JSON values: no

so it'll look like this for one partial
`{"name": "John Smith"}`

and this for another and so on.
`{"address": "123 North Str"}`

so the size of the JSON needs to be variable, but we're just allocating enough memory up front to hold anything we would ever serialize and using a buffer + an offset to determine the size of the buffer content we care about.

I get a different issue when using std::string_view interestingly:
```
/include/glaze/json/write.hpp:1326:38: error: could not convert ‘quoted_key’ from ‘const std::basic_string_view<char>’ to ‘long unsigned int’
 1326 |                      dump<quoted_key>(b, ix);
      |                      ~~~~~~~~~~~~~~~~^~~~~~~
      |                                      |
      |                                      const std::basic_string_view<char>
```

where my call to write_json is as follows
```
char buf*;
std::string_view svOut{buf};
glz::write_json<partial_1>(msg, svOut);
```

**Comment by stephenberry** [comment]
Thanks for bringing up these issues with raw and std::string_view buffers. I'm about to merge a major change to support errors when writing and then I'll prioritize these issues.

**Comment by stephenberry** [comment]
Support is being added in #1074

**Comment by stephenberry** [comment]
`std::string_view` is read only, so I've decided to just support `char*` and `char[]` raw buffers for writing. I could add write support for `std::span<char>`, but this might add some confusion and I don't feel is necessary.

**Comment by stephenberry** [comment]
Support has been merged, let me know if you run into any issues.

**Comment by pawcam** [comment]
Awesome, I will definitely check it out soon. Thanks!
