### ISSUE TITLE
Built-in support for type control

### ISSUE THREAD

**Issue by meftunca** [stephenberry/glaze#1065]
Hello, thank you in advance for this excellent library. I list below the features I need. These features can be static.

# is_(json_type_name)
- is_object
- is_array
- is_number
- is_bool
- is_string
- is_null

**Comment by stephenberry** [comment]
This is a good request. Right now these don't exist in the user facing API, but exist in the `glz::detail` namespace. I'll formalize the naming to what you've included here and expose them to the `glz::` namespace.

**Comment by stephenberry** [comment]
This request is actually targeted at `glz::json_t`. See discussion at #1069 
However, C++20 concept support for types should be added as well.

**Comment by stephenberry** [comment]
is_(json_type_name) support is being added in #1082. I've opened #1083 for C++20 concept versions for types, but these probably aren't as useful for you, @meftunca.
