### ISSUE TITLE
How do I write an enum as a raw string?

### ISSUE THREAD

**Issue by 33Heisenberg33** [stephenberry/glaze#1068]
Let's say that I have an enum type, for which i've "enabled stringification".

```
enum class Color
{
    Red, Green, Blue
};

...
static constexpr auto value = enumerate(Red, Green, Blue);
...
```
I will also use this as a type for a member in a struct.

```
struct ColorWrapper
{
     Color color { Color::Green };

     struct glaze
     {
          using T = ColorWrapper;
          static constexpr auto value = glz::object("color", glz::raw<&T::color>);
     };
};
```
What I expect is that the value of the color will appear as a raw string in the json output, however the actual value will still have quotes around it. Is there a way in which I can solve this problem?

Desired output:
```
{
    "color": Green
}
```

**Comment by stephenberry** [comment]
Thanks for brining this up, enums were simply overlooked, but support has now been added in #1071
