### ISSUE TITLE
Link to NDJSON website looks sus...

### ISSUE THREAD

**Issue by vijay8i** [stephenberry/glaze#1077]
The README points to a website for NDJSON that I don't think is about NDJSON. Please fix the README and any other references to the website. 

<img width="781" alt="image" src="https://github.com/stephenberry/glaze/assets/90803233/ff80b9d1-73e5-499c-aba9-8f6b24a617b2">

**Comment by vijay8i** [comment]
REF: https://github.com/ndjson/ndjson.github.io/issues/24

**Comment by stephenberry** [comment]
Thanks for reporting this. So, it appears newline-delimited JSON is now being pushed as [JSON Lines](https://jsonlines.org). I'll update the documentation.
