### ISSUE TITLE
[ICE] `msvc 17.8` (`glaze 2.8.1`)

### ISSUE THREAD

**Issue by helmesjo** [stephenberry/glaze#1078]
Just noticed this so figured I'd share.
See full log [here](https://ci.stage.build2.org/@39bc1f69-7f01-4d48-9f5d-10a1155d5f55/libglaze/2.8.1-a.0.20240612083834.9f44b0adacd6/log/x86_64-microsoft-win32-msvc14.3/windows_10-msvc_17.8-O2/default/stage/0.17.0-a.0.20240607095254.d30cc688b46d/update).
See the 15/58 currently failing builds [here](https://ci.stage.build2.org/@39bc1f69-7f01-4d48-9f5d-10a1155d5f55?builds=&pv=&th=*&tg=&tc=&pc=&rs=error).

```bash
# Visual Studio 17.8 (2022)

C:\tmp\dist\libglaze-2.8.1-a.0.20240612083834.9f44b0adacd6\include\glaze/json/write.hpp(1308): fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\symbols.c', line 32879)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
```

**Comment by stephenberry** [comment]
Try upgrading to the latest MSVC. MSVC has so many ICE issues that I have to work around that I can only guarantee the latest version working. But, I'm continuing to report issues and they are slowly fixing them. MSVC is just fragile with compile time programming.
