### ISSUE TITLE
Does glaze handle structs with static members ?

### ISSUE THREAD

**Issue by diommsantos** [stephenberry/glaze#1100]
I have the following class 
```
class Test
{
public:
    static constexpr std::string_view id{ "test" };
    std::string test = "test";
    int testInt = 125;
};

```
and this json string to be read into the Test class
`{"id":"test","test":"testaaa","testInt":127}`
does the id member variable being static affect glaze? Or it can handle these cases by default?

**Comment by stephenberry** [comment]
Thanks for asking. Pure reflection will only count the non-static members of the class. But, Glaze does support `static constexpr` through a `glz::meta`:

```c++
template <>
struct glz::meta<Test>
{
    using T = Test;
    static constexpr auto value = object("id", &T::id, &T::test, &T::testInt);
};
```

> [!IMPORTANT]  
> An explicit name is required for static constexpr variables. The `"id"` in is not optional. This is because `std::is_member_pointer_v` is only true for non-static members, and this is how Glaze determines if simple name reflection is viable.

Here is a working example of your problem on compiler explorer: https://gcc.godbolt.org/z/q988GoGdY

I'll update Glaze's documentation to make this clearer.
