### ISSUE TITLE
Extra quotes when customizing to_json for map keys

### ISSUE THREAD

**Issue by llchan** [stephenberry/glaze#1101]
Rough sketch of repro:

```c++
#include <glaze/glaze.hpp>

enum class Foo {
    eABC,
    eDEF
};

auto fooName(Foo foo) -> const char* {
    switch (foo) {
        case Foo::eABC: return "ABC";
        case Foo::eDEF: return "DEF";
        default: __builtin_unreachable();
    }
}

namespace glz::detail {
template <>
struct to_json<Foo> {
    template <auto Opts>
    static void op(const Foo& foo, auto&&... args) {
        write<json>::op<Opts>(fooName(foo), args...);
    }
};
} // namespace glz::detail

struct Data {
    std::map<Foo, int> foos;
};

int main(int argc, char* argv[]) {
    Data data;
    data.foos[Foo::eABC] = 123;
    data.foos[Foo::eDEF] = 456;
    auto result = glz::write<glz::opts{}>(data);
    if (!result) {
        return 1;
    }
    std::cout << result.value() << std::endl;
    return 0;
}
```

This produces output like this:
```
{"foos":{"\"ABC\"":123,"\"DEF\"":456}}
```

Rather than the expected:
```
{"foos":{"ABC":123,"DEF":456}}
```

I should point out that if `Foo` is used as values rather than map keys, there is no extraneous quoting.

If there's a better way to do this (supply a custom enum->string function/lambda) I'm open to other ways.  Tried using `glz::meta` with a `value` lambda but couldn't get it to compile without also specializing `to_json`.  Basically want a way to customize glaze to always treat the `Foo` enum as its `fooName(value)` equivalent string.

**Comment by llchan** [comment]
Found a workaround for now:
```c++
template <>
struct glz::meta<Foo>
{
    static constexpr auto custom_write = true;
    static constexpr auto value = enumerate(Foo::eABC);
};
```
This basically tricks glaze into treating `Foo` as a `glaze_enum_t` which goes into the string-ish branch of `write_pair_content`.  I should mention that in my actual use case for this, the enum comes from a third party lib and has hundreds of values and the enum to string function is not constexpr, so using the `enumerate_no_reflect` function on its own will not work.  It's sufficient to just do a `enumerate()` with a single enum value which is enough to get glaze to treat it like an enum.

**Comment by stephenberry** [comment]
Another solution for your original code is to use the `.raw` option in `glz::opts` when writing. The `.raw` option writes out string-like values without quotes.

This line: `write<json>::op<Opts>(fooName(foo), args...);`
becomes:
`write<json>::op<opt_true<Opts, &opts::raw>>(fooName(foo), args...);`

`glz::opt_true` is used as a helper for setting the appropriate boolean at compile time of the templated options, so that the rest of the options get properly passed through.

Here's a working example on compiler explorer of your code: https://gcc.godbolt.org/z/jsf6W57oa
