### ISSUE TITLE
glz::hide support for reflection

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#1108]
Allow glz::hide to work as a wrapper in a struct for use with reflection

**Comment by stephenberry** [comment]
Wrappers around values in structs are something that should be avoided. The intention of Glaze is to not pollute user classes unless it brings significant benefit. Wrappers outside of meta definitions create indirections that are harder to use and make the code less flexible.

**Comment by DUOLabs333** [comment]
I actually do want something like this --- I have a struct that I want to serialize, but out of the ~10 members, I only want to serialize 3. It would be great if I didn't have to specify all of my members (which could change), just to only allow a small portion of it.

**Comment by stephenberry** [comment]
Glaze does have support for specifying only the select field you want to write: [Partial Write documentation](https://github.com/stephenberry/glaze/blob/main/docs/partial-write.md)

I have an open issue to add blacklist support as well (choose which fields to ignore), here: https://github.com/stephenberry/glaze/issues/1140

**Comment by DUOLabs333** [comment]
I can't tell from the documentation, but can you only list the things that you want. So for example, in the partial write documentation, if you only wanted to send the tiger and panda, do you just do `static constexpr auto value = glz::object(&T::tiger, &T::panda)`?

**Comment by stephenberry** [comment]
Yes, if you only want to ever serialize `tiger` and `panda` then you could just use `glz::object(&T::tiger, &T::panda)`

The partial writing with JSON pointers is for when most of the time you want to serialize everything, but sometimes you only want to serialize a subset, and that is when you use the partial writing approach.
