### ISSUE TITLE
GLZ_ENUM without `//`  in context.hpp

### ISSUE THREAD

**Issue by toge** [stephenberry/glaze#1132]
I have one question.

Is it necessary to put `//` after the first parameter of GLZ_ENUM in context.hpp?
```
   GLZ_ENUM(error_code,
            none, //
            no_read_input, //
```
https://github.com/stephenberry/glaze/blob/v2.9.4/include/glaze/core/context.hpp#L15-L17

It works fine in gcc, but I was wondering because there is a `//` after GLZ_ENUM_MAP in schema.hpp.
```
   GLZ_ENUM_MAP(defined_formats, //
                "date-time", datetime, //
                "date", date, //
```
https://github.com/stephenberry/glaze/blob/v2.9.4/include/glaze/json/schema.hpp#L139-L141

**Comment by stephenberry** [comment]
The `//` should not be necessary at all. They were just put there for the sake of clang-format.

**Comment by toge** [comment]
@stephenberry 
Thanks!
Now I understand.
