### ISSUE TITLE
MSVC compiler error

### ISSUE THREAD

**Issue by slize-it** [stephenberry/glaze#1133]
Hey, I don't really know what I'm doing wrong here. However, I can't mange to get this library compiled. I just created a new project (with C++20 enabled) and included the library.

`Build started at 19:33...
1>------ Build started: Project: TestConsole, Configuration: Debug x64 ------
1>main.cpp
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(67,1): warning C4003: not enough arguments for function-like macro invocation 'GLZ_FOR_EACH_HELPER'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(67,1): warning C4003: not enough arguments for function-like macro invocation 'GLZ_STRINGIFY'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(67,1): warning C5109: __VA_OPT__ use in macro requires '/Zc:preprocessor'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2146: syntax error: missing ')' before identifier '__VA_OPT__'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C3861: '__VA_OPT__': identifier not found
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2143: syntax error: missing ';' before '{'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2143: syntax error: missing ')' before ';'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2447: '{': missing function header (old-style formal list?)
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2059: syntax error: ','
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2059: syntax error: ')'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C3536: 'glz::error_code_names': cannot be used before it is initialized
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C2109: subscript requires array or pointer type
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\core\context.hpp(15,4): error C3615: constexpr function 'glz::nameof' cannot result in a constant expression
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(158,1): warning C4003: not enough arguments for function-like macro invocation 'GLZ_FOR_EACH_HELPER2'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(158,1): warning C5109: __VA_OPT__ use in macro requires '/Zc:preprocessor'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2143: syntax error: missing '}' before '('
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2146: syntax error: missing ')' before identifier '__VA_OPT__'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2146: syntax error: missing ';' before identifier '__VA_OPT__'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2059: syntax error: ','
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2059: syntax error: ')'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2143: syntax error: missing ';' before '}'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2064: term does not evaluate to a function taking 1 arguments
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2365: 'glz::nameof': redefinition; previous definition was 'function'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2065: 'defined_formats': undeclared identifier
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2146: syntax error: missing ')' before identifier 'value'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C3861: 'defined_formats_names': identifier not found
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(139,7): error C2065: 'defined_formats_names': undeclared identifier
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(159,4): error C2059: syntax error: '}'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(159,4): error C2143: syntax error: missing ';' before '}'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(160,1): error C2143: syntax error: missing ';' before '}'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(160,1): error C2059: syntax error: '}'
1>C:\Users\user\source\repos\TestConsole\TestConsole\glaze\json\schema.hpp(163,13): error C2906: 'glz::meta<glz::detail::schematic>': explicit specialization requires 'template <>'
1>Done building project "TestConsole.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 19:33 and took 02,110 seconds ==========
`

**Comment by stephenberry** [comment]
Check that you have `/Zc:preprocessor` enabled. MSVC doesn't default to a standards compliant macro processor.

**Comment by slize-it** [comment]
You are a genius. Thanks, it's compiling now! :-)
