### ISSUE TITLE
Please update the vcpkg package

### ISSUE THREAD

**Issue by bence-palkovics** [stephenberry/glaze#1135]
The latest version of glaze in the vcpkg package registry is 2.6.9. Could you please update it?

**Comment by stephenberry** [comment]
There is an active pull request to update glaze here: https://github.com/microsoft/vcpkg/pull/39524

**Comment by bence-palkovics** [comment]
Thanks!

**Comment by jeff-kohn** [comment]
Unfortunately that PR is in limbo until the other port in the same PR is ready. It's also already a few versions behind the latest glaze release unless they update it again. Hopefully it gets updated and approved soon.
