### ISSUE TITLE
MSVC conflict with minwindef.h

### ISSUE THREAD

**Issue by slize-it** [stephenberry/glaze#1136]
I have added the library to a larger project and it seems that there is a problem with a conflict between the `max` definition in `minwindef.h` and the default `limits` header.

![image](https://github.com/stephenberry/glaze/assets/36815388/390a6031-2672-45c6-985c-6e4202b3e638)
![image](https://github.com/stephenberry/glaze/assets/36815388/c244a5f8-ee76-438c-8ad1-303ff415ffbf)

This can be fixed like this:
```
#define NOMINMAX
#include "glaze/glaze.hpp"
```

But perhaps there is another (better) way to solve the problem.

**Comment by stephenberry** [comment]
This has been fixed on the `main` branch. I just haven't made a new release yet.
The way I use to fix this without needing the `#define NOMINMAX` is to write: `(std::numeric_limits<V>::max)()`

**Comment by stephenberry** [comment]
Sorry, this fix was actually on another branch. I'll merge it into main and get a new release out.

**Comment by stephenberry** [comment]
Thanks for the feedback. Merged the fix and released it.
