### ISSUE TITLE
/Zc:preprocessor must be specified in the project settings

### ISSUE THREAD

**Issue by Nother62** [stephenberry/glaze#1160]
Hey,

I have updated Glaze to the newest version in my MSVC project, and initially, I received strange warnings and errors. It turns out my project didn't have `/Zc:preprocessor` (Use Standard Conforming Preprocessor) set in the project settings.

Now, everything is building properly, but there should be some information about this in the README, because newly created projects don't have this set by default.

*I love your project btw. 💯*

**Comment by stephenberry** [comment]
Thanks for pointing this out and the encouragement! I wish MSVC would default to conforming to standard C++, but for now I've added to the README:

### MSVC Compiler Flags

Glaze requires a C++ standard conformant pre-processor, which requires the `/Zc:preprocessor` flag when building with MSVC.
