### ISSUE TITLE
prettify_json("\xf3") invokes out ouf bounds read in prettify.hpp

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#1170]
The index calculated here: https://github.com/stephenberry/glaze/blob/36b61c3c99c2bdd4eaf63338a49d7ed821d90b1d/include/glaze/json/prettify.hpp#L26

can be out of bounds when the input string to prettify is bad (for instance, the string "\xf3").

I verified this by switching operator[] to .at() for the array, which gave the following exception:

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  array::at: __n (which is 18446744073709551603) >= _Nm (which is 256)

**Comment by stephenberry** [comment]
Thanks, yeah that should be a `uint8_t` rather than a `size_t`

**Comment by pauldreik** [comment]
Really fast bug fixing! I think there is a similar place in minify.hpp row 46

**Comment by stephenberry** [comment]
Yeah, I noticed the other one after you pointed out the problem in prettify_json.
I try to treat memory problems seriously and get them done ASAP.
