### ISSUE TITLE
reading generic json on invalid input causes out of bounds read in read.hpp

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#1172]
The following code:

```cpp
   glz::json_t json{};
   auto blah = std::vector<char>{0x22, 0x5c, char(0xff), 0x22, 0x00};
   auto ec = glz::read_json(json, blah);
```

triggers out of bounds access from https://github.com/stephenberry/glaze/blob/ebee5fdf14ec86edc43f485abfba09cc3504f90e/include/glaze/json/read.hpp#L761

seems like uint8_t(...) is needed here as well?

**Comment by stephenberry** [comment]
Yup, another missed `uint8_t` cast
