### ISSUE TITLE
CMAKE Version update

### ISSUE THREAD

**Issue by edunad** [stephenberry/glaze#1177]
Was there a reason to update cmake to `3.25` on 3.0? 
https://github.com/stephenberry/glaze/compare/v2.9.5...v3.0.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL1

`3.25` is not supported on older versions of ubuntu where `3.21` was fine

**Comment by stephenberry** [comment]
I was trying to push forward the version while making all the breaking changes in version 3. Since this adds additional burden I can back track the CMake requirement.

I'll do this in another release today.

**Comment by stephenberry** [comment]
I reverted CMake to 3.21. We should be able to stay at this version until adding C++20 modules support.
