### ISSUE TITLE
converting float -8536070.f to string gives  "-08536070"

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#1178]
I am not sure if it is illegal, but it is definitely unexpected to have a leading zero.

The following test:
```cpp
    "float write"_test = [] {
       std::string buffer{};
       expect(not glz::write_json(-8536070.f, buffer));
       expect(buffer == "-8536070") << buffer;
    };
```
the test fails, buffer contains "-08536070"

**Comment by stephenberry** [comment]
This is strange behavior and it doesn't conform to "the shortest possible representation", which is what the underlying algorithm is supposed to do. Glaze uses a slightly modified version of the code yyjson uses, and looking over the code I would expect this to also show up in yyjson, which is interesting.

Will have to be investigated further. But, the output is valid JSON and correct, so it isn't a major concern.

**Comment by pauldreik** [comment]
I do not think it is valid json. Looking at the railroad diagram on https://www.json.org/json-en.html it seems like a leading 0 must be followed by an optional fraction and optional exponent.

Also, it is rejected when deserializing back from json - I discovered this as part of a roundtrip test. So I think this should be labeled bug, not enhancement.

**Comment by stephenberry** [comment]
Yup, my bad. You're right this is a bug and broken.

**Comment by stephenberry** [comment]
Note: This case works for `double`, just not `float`. The original code from yyjson only handles `double`, so the optimizations for `float` using `double` parsing code introduce some incompatibility. Looking into it.

**Comment by stephenberry** [comment]
I'm moving to use `std::to_chars` with special conversions for `inf` and `nan` to `null` for JSON compliance. This should fix any serialization issues with floating point numbers.

**Comment by stephenberry** [comment]
Well... the performance for `std::to_chars` is abysmal at least on MacOS Arm. I'm going to figure out a faster solution, it just might take a bit longer.

**Comment by stephenberry** [comment]
I've switched Glaze to use the dragonbox algorithm underneath with new float handling. It solves this particular case and I haven't gotten it to error in my tests.

**Comment by pauldreik** [comment]
Unfortunately this still does not handle my roundtrip tests. It failed on the denormalized number 1.40129846e-45f which got serialized to {"value":1.E-45} which is rejected by the glaze deserializer.

**Comment by pauldreik** [comment]
It is work in progress, but you can view that particular test here: https://github.com/pauldreik/glaze/blob/fuzz/fuzzing/json_exhaustive_roundtrip_int.cpp

**Comment by stephenberry** [comment]
Thanks for sharing your fuzz testing! Also, I've added better random float and double testing to Glaze in #1190.

#1190 also fixes the denormalized number serialization issue.
