### ISSUE TITLE
read_json on json_t invoked with invalid unicode causes out of bounds read in hex_to_u32

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#1189]
The following test: 

```cpp
    "json_t garbage input"_test =[] {
      glz::json_t json{};
      expect(not glz::read_json(json, "\x22\x5c\x75\xff\x22"));
    };
```

invokes an out of bounds read. seems like when encountering a \u, it is assumed one can look forward, leading to the derefence in hex_to_u32.

https://github.com/stephenberry/glaze/blob/c365ba48fb839f13290f1e4fc2a1aeab7a295438/include/glaze/json/read.hpp#L746-L750

found in c365ba48fb839f13290f1e4fc2a1aeab7a295438

**Comment by stephenberry** [comment]
End of buffer check needed to be moved up a few lines. Fixed in #1193. Thanks for finding this!
