### ISSUE TITLE
clang - remainder by zero is undefined

### ISSUE THREAD

**Issue by arturbac** [stephenberry/glaze#1198]
In constexpr compiler may skip evaluating code when it is out of current scope context.
And clang is very strict at that so it reports error for
```
glaze/util/hash_map.hpp:535:41: error: remainder by zero is undefined [-Werror,-Wdivision-by-zero]
```
You need to put else scope block after if constexpr

```cpp
constexpr void find_perfect_hash() noexcept
      {
         if constexpr (N == 0) {
            return;
         }
         else {
```

**Comment by stephenberry** [comment]
Thanks for reporting this!
