### ISSUE TITLE
error_on_unknown_keys does not provide any info about the key in error_ctx

### ISSUE THREAD

**Issue by Joshua-Ashton** [stephenberry/glaze#1227]
It would be nice for `error_on_unknown_keys` to fill up `custom_error_message` or something with the key that was unknown and with the name of the struct or something.

Otherwise, it's not that helpful, especially when working with programmatically generated json.

**Comment by stephenberry** [comment]
Thanks for the request. There is plan to add more helpful errors in this case, a similar issue is open here: #1148

**Comment by stephenberry** [comment]
I'm going to be adding thoughts and working on this problem in #1148, so I'm going to close this version of the issue. Thanks for the feedback and encouragement to get this resolved.
