### ISSUE TITLE
GLZ_FLATTEN adds significant compilation time on MSVC.

### ISSUE THREAD

**Issue by RealTimeChris** [stephenberry/glaze#1233]
It seems that without it, it takes roughly 5 minutes to build the Release version of the benchmark suite, but with it, it takes over an hour and still is not done.

**Comment by stephenberry** [comment]
Can you share what version of MSVC you are using? It is building quickly in the GitHub actions and on my machine.

Do you have the latest version?

**Comment by RealTimeChris** [comment]
MSVC 19.40.33812.0. Let me see if there's an updated version.

**Comment by RealTimeChris** [comment]
Also it was staying stuck on the action server that I was launching it on.

**Comment by stephenberry** [comment]
Yeah, this did indeed create problems. I reverted the change in #1235.
