### ISSUE TITLE
GLZ_FLATTEN adds significant compilation time on gcc.

### ISSUE THREAD

**Issue by toge** [stephenberry/glaze#1237]
It seems to be almost same as #1233.

In gcc 14.1, glaze/3.1.7 and glaze/3.1.9 take too long compiliation time with following messages:
```
In file included from glaze/core/meta.hpp:10,
                 from glaze/api/hash.hpp:9,
                 from glaze/api/std/span.hpp:8,
                 from glaze/core/read.hpp:8,
                 from glaze/binary/skip.hpp:8,
                 from glaze/binary/read.hpp:7,
                 from glaze/binary/custom.hpp:6,
                 from glaze/binary.hpp:6,
                 from glaze/glaze.hpp:35,
                 from test10.cpp:16:
glaze/util/for_each.hpp: In function ‘constexpr void glz::for_each_flatten(Func&&) [with long unsigned int N = 34; Func = detail::to_json<detail::schematic>::op_base<glz::opts{10, 0, 1, 1, 1, 0, 0, ' ', 3, 1, 0, 0, 0, 0, 0, 0, 0, glz::float_precision::full, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0}, std::__cxx11::basic_string<char>&, glz::detail::schematic&, glz::context&, long unsigned int&>(glz::detail::schematic&, glz::context&, std::__cxx11::basic_string<char>&, long unsigned int&)::<lambda(auto:743)>]’:
glaze/util/for_each.hpp:23:31: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
   23 |    GLZ_FLATTEN constexpr void for_each_flatten(Func&& f)
      |                               ^~~~~~~~~~~~~~~~
```

It works fine with `-DGLZ_FLATTEN=inline`.
Is this workaround valid?

**Comment by stephenberry** [comment]
Yes, `-DGLZ_FLATTEN=inline` is a fine work around. However, I'll keep this issue open because I don't want users to have to define this. Thanks for pointing this out!

**Comment by stephenberry** [comment]
Not that I recommend turning this option off, but I'm adding this reference for future consideration: https://stackoverflow.com/questions/2954473/variable-tracking-is-eating-my-compile-time

**Comment by stephenberry** [comment]
I merged in a few more changes in #1239, which should improve compilation performance. I'm trying to not split flattening behavior on the number of elements of a struct.

@toge, would you be able to build with `main` and see if compilation is shorter and `variable tracking size limit exceeded` is fixed?

**Comment by toge** [comment]
@stephenberry 
Thank you for your quick response!
Now compilation is shorter than 3.1.9 but `variable tracking size limit exceeded` is sitl occured.

Almost same messages.
```
In file included from glaze/core/meta.hpp:10,
                 from glaze/api/hash.hpp:9,
                 from glaze/api/std/span.hpp:8,
                 from glaze/core/read.hpp:8,
                 from glaze/binary/skip.hpp:8,
                 from glaze/binary/read.hpp:7,
                 from glaze/binary/custom.hpp:6,
                 from glaze/binary.hpp:6,
                 from glaze/glaze.hpp:35,
                 from test10.cpp:16:
glaze/util/for_each.hpp: In function ‘constexpr void glz::for_each_flatten(Func&&) [with long unsigned int N = 34; Func = detail::to_json<detail::schematic>::op_base<glz::opts{10, 0, 1, 1, 1, 0, 0, ' ', 3, 1, 0, 0, 0, 0, 0, 0, 0, glz::float_precision::full, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0}, std::__cxx11::basic_string<char>&, glz::detail::schematic&, glz::context&, long unsigned int&>(glz::detail::schematic&, glz::context&, std::__cxx11::basic_string<char>&, long unsigned int&)::<lambda(auto:742)>]’:
glaze/util/for_each.hpp:23:31: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
   23 |    GLZ_FLATTEN constexpr void for_each_flatten(Func&& f)
      |                               ^~~~~~~~~~~~~~~~
```

**Comment by stephenberry** [comment]
@toge, thanks for testing this! I'm continuing to look into the problem. I'm hoping to come out with a robust solution. Thanks for your patience.

**Comment by toge** [comment]
No problem. There are workaroud.
Your library is still great for me.
Thanks!

**Comment by stephenberry** [comment]
@toge, I just merged in #1240, which uses switch statements that should be easier for the compiler to handle. Does this new change fix the `variable tracking size limit exceeded` issue?

**Comment by stephenberry** [comment]
Oh, I just realized this issue is happening with writing and I was trying to fix reading (I had just assumed the problem would be there). I'll tackle writing soon.

**Comment by toge** [comment]
@stephenberry 
Now It works fine on HEAD.
Thanks a lot!

**Comment by stephenberry** [comment]
Excellent! I'll release a new version soon with these fixes.
