### ISSUE TITLE
Type selection when reading to a variant 

### ISSUE THREAD

**Issue by diommsantos** [stephenberry/glaze#1249]
Suppose we have the following code 
```
struct a1{
int i;
}

struct a2{
double i;
}

std::variant<struct1, struct2> v;
std::string json= "6";
```
Currently without the `glz::meta` we can't use glaze to choose what is the index (or the alternative that the variant holds) after `glz::read(v, json)`. It would be pretty nice if it was possible to write `glz::read<struct2>(v, json)` with the result that after the variant will hold the `struct2` alternative with the double 6 inside, or something similar.

**Comment by stephenberry** [comment]
If you know you are trying to decode `struct2` then you can set this as your variant type and then read into the active element:

```c++
std::variant<struct1, struct2> v = struct2{};
glz::read_json(std::get<struct2>(v), json); // <-- read into the active element
```

Someday I'll probably add support to read into the active element when a variant is passed in, but for now this will suffice without a bunch of compile time overhead.
