### ISSUE TITLE
Any struct with any members named "first" and "second" in any order is treated as a std::pair

### ISSUE THREAD

**Issue by RazielXYZ** [stephenberry/glaze#1266]
Having any two members in a struct named "first" and "second", of any type, causes glaze to treat that struct as a std::pair. In most cases, this leads to compilation failure.
It does not matter if these members are at the start, end, or middle of the struct, nor if there are any other members in between. It also doesn't matter if "second" is before "first".

**Comment by stephenberry** [comment]
Ah, yes this is due to a very simple concept for pair. But, it is very helpful for handling custom pair types.

I'll have to think through ways to reduce this. I think I know how to limit it to only two elements.

Thanks for bringing this issue up!

**Comment by RazielXYZ** [comment]
This is also relatively easy to avoid on the user's part - it just might be unexpected and potentially difficult to find/diagnose, although the template instantiation does point to the struct in question. So I don't think "fully" fixing it is necessarily a priority, but some better handling of the unexpected case would probably be nice to have.

**Comment by stephenberry** [comment]
`std::pair` defines member types: `first_type` and `second_type`. I think making the concept check for these would be a good idea. It would mean custom types would need to define these aliases, but it would create much less astonishment for users.

**Comment by stephenberry** [comment]
I merged in the pair concept requirement for `first_type` and `second_type` into `main` (#1267).
