### ISSUE TITLE
AppleClang std::hash<std::filesystem::path> issue

### ISSUE THREAD

**Issue by Kailo97** [stephenberry/glaze#1280]
### Is that a current problem?
- [x] Not found any related issues
- [x] Supported compiler version (based on README.md and workflows)
- [ ] Checked on latest main (report form v2.9.5)

### Environment
AppleClang 15.0.0.15000309 via github actions image `macos-13`

### Issue
`std::hash<std::filesystem::path>` not founded by compiler referenced in `glz::read_directory`
`glz::read_directory` not used, but build with pch
Implementation not included in STL before version ???. C++ Language reference notice
https://en.cppreference.com/w/cpp/filesystem/path/hash [LWG issue 3657](https://cplusplus.github.io/LWG/issue3657)
`read_directory.hpp` added with https://github.com/stephenberry/glaze/commit/9e8660f0584076bb019a8365779bd3c7a8a5bc7a

Same AppleClang used in glaze's workflow `clang`, but not showing the issue. `directory_tests` from `json_test` was added with same commit

### Side notes
Our project C++20 based, so we choose glaze prior v3.0.0 - v2.9.5, but seem reproducible in latest glaze

### Logs
```
[ 16%] Building CXX object CMakeFiles/plugify.dir/cmake_pch.hxx.pch
In file included from <built-in>:496:
In file included from /Users/runner/work/plugify/plugify/build/CMakeFiles/plugify.dir/cmake_pch.hxx:5:
In file included from /Users/runner/work/plugify/plugify/src/pch.h:4:
In file included from /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/string:576:
In file included from /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/string_view:1027:
In file included from /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/functional:515:
In file included from /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:25:
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/unordered_map:577:[17](https://github.com/untrustedmodders/plugify/actions/runs/10647793720/job/29516117899#step:8:18): error: type 'const std::hash<std::filesystem::path>' does not provide a call operator
        {return static_cast<const _Hash&>(*this)(__x);}
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__hash_table:1997:21: note: in instantiation of member function 'std::__unordered_map_hasher<std::filesystem::path, std::__hash_value_type<std::filesystem::path, std::string>, std::hash<std::filesystem::path>, std::equal_to<std::filesystem::path>>::operator()' requested here
    size_t __hash = hash_function()(__k);
                    ^
/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/unordered_map:[18](https://github.com/untrustedmodders/plugify/actions/runs/10647793720/job/29516117899#step:8:19)04:21: note: in instantiation of function template specialization 'std::__hash_table<std::__hash_value_type<std::filesystem::path, std::string>, std::__unordered_map_hasher<std::filesystem::path, std::__hash_value_type<std::filesystem::path, std::string>, std::hash<std::filesystem::path>, std::equal_to<std::filesystem::path>>, std::__unordered_map_equal<std::filesystem::path, std::__hash_value_type<std::filesystem::path, std::string>, std::equal_to<std::filesystem::path>, std::hash<std::filesystem::path>>, std::allocator<std::__hash_value_type<std::filesystem::path, std::string>>>::__emplace_unique_key_args<std::filesystem::path, const std::piecewise_construct_t &, std::tuple<const std::filesystem::path &>, std::tuple<>>' requested here
    return __table_.__emplace_unique_key_args(__k,
                    ^
/Users/runner/work/plugify/plugify/build/_deps/glaze-src/include/glaze/file/read_directory.hpp:18:47: note: in instantiation of member function 'std::unordered_map<std::filesystem::path, std::string>::operator[]' requested here
            if (auto ec = file_to_buffer(files[entry.path()], entry.path().string()); bool(ec)) {
                                              ^
```
[Full logs (github Actions)](https://github.com/untrustedmodders/plugify/actions/runs/10647793720/job/29516117899)

**Comment by stephenberry** [comment]
Thanks so much for reporting this issue. Will look into it soon.

**Comment by stephenberry** [comment]
Thanks for the details you included about the LWG issue, which seems to be fixed on more recent compilers, but not the current AppleClang. My guess is that Xcode 16 will fix this looking at the C++ improvements.

Do you have a suggestion for how to handle this issue in the meantime? It doesn't make sense to break working code on Xcode just because precompiled headers don't build. I wish there were some macro to prevent clang from precompiling a header, but I can't find one.

The solution may be to wait until Xcode 16 is released before moving to Glaze version 3 if precompiled headers are needed.

Also, if you submit a pull request to add a GitHub Action workflow to test precompiled headers with Glaze I would gladly accept it. I use precompiled headers on GCC all the time, but have no experience with Clang PCH.

**Comment by Kailo97** [comment]
We face same issue in our project. As `hash_value` implemented, we workaround by defining hash wrapper
```cpp
// std::hash<std::filesystem::path> not in the C++20 standard by default
struct path_hash {
	[[nodiscard]] auto operator()(const std::filesystem::path& path) const noexcept {
		return std::hash_value(path);
	}
};

std::unordered_map<std::filesystem::path, std::string, path_hash> files;
```

**Comment by stephenberry** [comment]
Thanks for this suggestion! I've just merged this into main. Let me know if this allows you to build now.
