### ISSUE TITLE
Support of custom string

### ISSUE THREAD

**Issue by sjanel** [stephenberry/glaze#1340]
I would like to use this library with a custom string implementation as drop-down replacement of `std::string`. Is it possible to do that currently ?

If not, would it be possible to define a "writable buffer of char" as returned by value type custom mapping to make it work ? It could be a `span<char>`, or something else maybe.

**Comment by stephenberry** [comment]
Glaze uses C++20 concepts to handle different types. If your string class has a similar API to a std::string then it should still work. It should work as long as it has `size()`, `resize()`, and `data()` (to get the underlying buffer).

If you run into any issues, let me know.

**Comment by sjanel** [comment]
Thanks a lot! Indeed it seems to work out of the box. What about explaining it in the documentation?

**Comment by stephenberry** [comment]
Nice. And thanks for the suggestion. I'll add some documentation notes about this.
