### ISSUE TITLE
Integer Parsing Bug on main

### ISSUE THREAD

**Issue by RealTimeChris** [stephenberry/glaze#1346]
So when running the following tests (parsing into an int64_t), I get the following output:
```cpp
passTest11.json Input: [122.2345678910]
passTest11.json Failed - Expected Output: 122
Glaze Error: 1:5: expected_bracket
   [122.2345678910]
       ^
passTest13.json Input: [100000.300e7]
passTest13.json Failed - Expected Output: 1000003000000
Glaze Error: 1:8: expected_bracket
   [100000.300e7]
          ^
passTest14.json Input: [1002.34e+9]
passTest14.json Failed - Expected Output: 1002340000000
Glaze Error: 1:6: expected_bracket
   [1002.34e+9]```

**Comment by stephenberry** [comment]
Oh, that's not good. Will have to look into it.

**Comment by RealTimeChris** [comment]
Cool - btw I put together a couple of Uint/Int validation tests if you want to use them:
https://github.com/RealTimeChris/Jsonifier/blob/dev/Tests/Uint.hpp
https://github.com/RealTimeChris/Jsonifier/blob/dev/Tests/Int.hpp
https://github.com/RealTimeChris/Jsonifier/tree/dev/Tests/UintValidation
https://github.com/RealTimeChris/Jsonifier/tree/dev/Tests/IntValidation

**Comment by stephenberry** [comment]
Sweet, thanks!
