### ISSUE TITLE
Should integers round or truncate (cast) from decimal numbers?

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#1355]
Need to formalize how decimal numbers are parsed into integers. Do we truncate or round? Currently rounding is performed, but should this be the default behavior?

I think there should be a compile time option to reject decimal inputs to integers as well. However, I think that exponents should still be valid (e.g. `1e7` rather than writing `10000000`).

**Comment by FirstTimeEZ** [comment]
This is an obvious loss of precision, You wouldn't try parse an `int` into a `ushort` either for the same very obvious reason.

> Do we truncate or round?

Don't truncate or round anything, you clown.

**Comment by FirstTimeEZ** [comment]
This is an obvious loss of precision I would expect a first year student to understand, You wouldn't try parse an `int` into a `ushort` either for the same very obvious reason.

> Do we truncate or round?

Don't truncate or round anything, you clown.

**Comment by RealTimeChris** [comment]
I say truncate should be default. It avoids ever "making up" input as well as follows what happens when you static_cast<int64_t>(0.2e12)

**Comment by stephenberry** [comment]
The more I think about it the more I think the integer parser should reject decimals, but accept exponents.

If decimals exist, a floating point value should be used instead.

This helps with clarity, performance, and Glaze can always provide wrappers for automatic casting so that integers can still be parsed from decimal JSON inputs.
