### ISSUE TITLE
glz::read for NDJSON with specifc options fails to build 

### ISSUE THREAD

**Issue by Haatschii** [stephenberry/glaze#1356]
Minimal reproducible example:

```C++
struct Foo  {
	int x;
};


int main ([[maybe_unused]] const int argC, [[maybe_unused]] char* argV[] ) {
	std::vector<Foo> assets{};
	const auto error = glz::read<glz::opts{.format = glz::NDJSON, .error_on_unknown_keys = false, .validate_skipped = true}>(assets, "{\"x\":1}\n{\"x\":2}");
}
```

The example fails to build (Glaze v3.6.1 and GCC 14.2) with the error (along with a lot of noise):
> glaze/include/glaze/json/skip.hpp:158:29: error: no matching function for call to ‘skip_array<glz::opts{100, '\001', '\000', '\000', '\001', '\001', '\000', '\000', ' ', 3, '\001', '\000', '\001', '\000', '\000', '\001', '\000', 0, glz::float_precision::full, '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\001', '\000', '\000', '\001', '\001', 0}>(glz::context&, const char*&, const char*&)’

I don't see why the combination of options should be invalid, so I assume this is a bug. I guess the reason is the requires statement in skip.hpp:63 wrongly excluding NDJSON. See the accompanying pull request.

**Comment by stephenberry** [comment]
Thanks for that fix! I've also added this simple case as a unit test.
