### ISSUE TITLE
how to support one json field with different format when different scenarios

### ISSUE THREAD

**Issue by JimjunZhang** [stephenberry/glaze#1361]
I have a case.  We are providing data to clients. We have an old format json file, but later we found the format wasn't good enough then updated to use new format. To support the compatibility we want to keep the same json key but with different value format, i.e. old format for old clients while new format for new clients.  We know the corresponding client by using a flag. 

The old value format as below key "feeCashflows".
![image](https://github.com/user-attachments/assets/d2ab18c5-cd8f-487d-8967-46006a780415)

The new value format as below key "feeCashflows"
![image](https://github.com/user-attachments/assets/020c5421-10a4-492a-8e41-b5930a1d5c1c)

Is there easy way to generate the corresponding json by using a switch flag?  Thanks!

**Comment by stephenberry** [comment]
If your `deal` structure holds a boolean switching between the two formats, then you can use a `glz::custom` wrapper to check the boolean on writing and write out the appropriate value.

I'll just throw this example out for now, but a can make an example tailored to your problem later when I have more time.
```c++
struct custom_buffer_input
{
   std::string str{};
};

template <>
struct glz::meta<custom_buffer_input>
{
   static constexpr auto read_x = [](custom_buffer_input& s, const std::string& input) { s.str = input; };
   static constexpr auto write_x = [](auto& s) -> auto& { return s.str; };
   static constexpr auto value = glz::object("str", glz::custom<read_x, write_x>);
};

suite custom_buffer_input_test = [] {
   "custom_buffer_input"_test = [] {
      custom_buffer_input obj{};
      std::string s = R"({"str":"Hello!"})";
      expect(!glz::read_json(obj, s));
      expect(obj.str == "Hello!");
      s.clear();
      expect(not glz::write_json(obj, s));
      expect(s == R"({"str":"Hello!"})");
      expect(obj.str == "Hello!");
   };
};
```

**Comment by stephenberry** [comment]
I'll also note that from your custom write lambda you'll probably have to return a variant of your two versions. Glaze will then serialize the active member of the variant.

**Comment by JimjunZhang** [comment]
Thanks, @stephenberry !  The variant works.  However, I have another issue to compose the old format.  You may notice the number of fees are dynamic and the fee names are also dynamic. 

I tried to unknown_write to define the old format as:

```
struct JfeeCashflowsLegacy_
{
    std::string name;
    std::map<std::string, std::vector<JfeeCashflows_cashflows_> > items;  // for legacy format
};
template <>
struct glz::meta<JfeeCashflowsLegacy_> {
    using T = ressps::JfeeCashflowsLegacy_;
    static constexpr auto value = glz::object(
        "name", &T::name
    );

    static constexpr auto unknown_write{ &T::items };
    static constexpr auto unknown_read{ &T::items };
};


```
Here I have to add additional field "name", otherwise I can't get the old format output.  But I don't want to have the redundant field "name".  
Any better idea? Thanks!

**Comment by stephenberry** [comment]
I'd need to dig into this in more detail but have you experimented with using `glz::custom`?

There is documentation here: https://github.com/stephenberry/glaze/blob/main/docs/wrappers.md#custom

**Comment by JimjunZhang** [comment]
Yes, I tried glz::custom to use lambda read and write and the write returns std::variant.  This works to generate different formats based on the boolean switch.
The new issue is how to generate the dynamic for the old value format, i.e.  in the "feeCashflows", the keys of the json fields are dynamic and the number of the json fields are also dynamic.

So, I redefined the structure by using unknown_write as:

```
struct JfeeCashflows_cashflows_
{
    // ....
}
struct JfeeCashflowsLegacy_
{
    std::unique_ptr<std::string> dummy{};   // dummy field for using extra unknown_write
    std::map<std::string, std::vector<JfeeCashflows_cashflows_> > items;   // for legacy format. I use std::string instead of sv
};
struct JfeeCashflows_
{
    std::vector<JfeeCashflowsLegacy_> feeCashflows;  
};
template <>
struct glz::meta<JfeeCashflowsLegacy_> {
    using T = JfeeCashflowsLegacy_;
    static constexpr auto value = glz::object(
        "dummy", &T::dummy
    );

    static constexpr auto unknown_write{ &T::items };
    //static constexpr auto unknown_read{ &T::items };   // not able to use read as using std::string instead of sv
};
```
 
Then, I fill in the JfeeCashflowsLegacy_::items in the object.  After you fixed the unknown field writing issue, we should be able to generated the correct json.   By using this definition, we'll lose the ability to read the json back as using std::string in the map.'   Not sure if there is a better way for this?

I also considered to use glz::raw_json, i.e. generate the dynamic items to json string first by using std::map, then attach to the "feeCashflows" object, but I understand it may lose some performance as additional json generation step.

**Comment by stephenberry** [comment]
I'm a little lost as to the exact issue here. If you could make a simple example on compiler explorer and share the link with me that would help. You can add Glaze as a library on compiler explorer.

`glz::raw_json` is a good solution in some cases, albeit there is additional performance overhead. You can also use `glz::json_t` for generic JSON structures: [generic-json.md](https://github.com/stephenberry/glaze/blob/main/docs/generic-json.md). This may help you here.

**Comment by JimjunZhang** [comment]
Hi @stephenberry , 
The latest version in compiler explorer is v2.0.3.  Not sure if it supports the unknown_write/read feature. However, the unknown_write is good workaround for me now as not much performance overhead.  Thanks for the support!

**Comment by stephenberry** [comment]
There is a `trunk` option, which is the latest version. Yet, I'm glad you have a workaround!

**Comment by stephenberry** [comment]
I'm closing this for now, but feel free to reopen or open new issues as you run into them. Thanks!
