### ISSUE TITLE
Enums as strings not working anymore

### ISSUE THREAD

**Issue by Haatschii** [stephenberry/glaze#1375]
After updating glaze to the current version I noticed that my glz::meta for enums seems to be ignored. Minimal reproducible example:

```c++
enum class MyEnum {X, Y, Z};

template<>
class glz::meta<MyEnum> {
	using enum MyEnum;
	static constexpr auto value = enumerate("X", X, "Y", Y, "Z", Z);
};


int main ([[maybe_unused]] const int argC, [[maybe_unused]] char* argV[] ) {
	MyEnum test = MyEnum::X;
	std::cout << glz::write_json(test).value_or("Error") << std::endl;	
	return 0;
}
``` 
This gives `0` instead of `"X"`. The result is the same when changing the glz::meta to `static constexpr auto value = enumerate(X, Y, Z);` which corresponds to the example in the README. I am pretty sure this worked in a previous version of glaze. Maybe I missed something?

**Comment by stephenberry** [comment]
Yeah, I'm surprised this bug got through. I'll try to address this soon.

**Comment by stephenberry** [comment]
Ah, I figured out the issue.  Your `class glz::meta<MyEnum>` needs to be `struct glz::meta<MyEnum>`, otherwise the template specialization won't work.

I'm surprised your compiler didn't give you a warning. Clang gave me a helpful warning.

**Comment by Haatschii** [comment]
Damn, sorry, missed that. GCC did indeed not raise any warnings.

**Comment by stephenberry** [comment]
No problem, I just found a bug today that was causing my team terrible headaches, I was always indexing with `[0]` rather than `[i]`.
