### ISSUE TITLE
Glaze minified seems to be having an issue under GCC/Ubuntu

### ISSUE THREAD

**Issue by RealTimeChris** [stephenberry/glaze#1390]
So when I run the following code as follows:
https://github.com/RealTimeChris/Json-Performance/blob/main/Source/main.cpp#L205
But with minified set to = minified, it seems to throw an "expected_bracket" error across 3 of the tests - the JsonData-Minified, CitmCatalog-Minified, and Twitter-Minified tests.

**Comment by stephenberry** [comment]
Well, currently your Json-Performance repository doesn't build on Mac where I usually develop. Could you try to version your code so that it isn't constantly breaking?

**Comment by RealTimeChris** [comment]
Alright my bad the benchmark branch should build properly now.

**Comment by stephenberry** [comment]
I can't seem to replicate this problem. I built and ran `main` and `benchmarking` tests on Ubuntu with GCC 13.2.1 and everything passed.

Can you test again on your side and provide more details about what configuration is failing if you still see the issue?

**Comment by stephenberry** [comment]
@RealTimeChris, can you check whether this is still an issue?

**Comment by RealTimeChris** [comment]
Alright checking.

**Comment by stephenberry** [comment]
I still can't replicate this. Does this error only show up in Release mode for you? And, what version of GCC are you using?

**Comment by RealTimeChris** [comment]
<img width="250" alt="{4E793172-CDD1-4D0C-B507-035F8D7A03E5}" src="https://github.com/user-attachments/assets/4cd352ed-60ba-48b4-811d-353ef14a7cd9">
And yes only release mode. Let me try it with a newer GNUC++.

**Comment by RealTimeChris** [comment]
<img width="490" alt="{3367DD56-1717-4958-9B13-8BE4C2BDC63E}" src="https://github.com/user-attachments/assets/b76c095b-953d-4a8d-bdae-c34d4c4a3fda">
<img width="522" alt="{18AF5FDE-E041-4C49-8152-16057EB4FCC2}" src="https://github.com/user-attachments/assets/6f61d2a0-78fe-4d29-9afd-c52f6c49fafb">
You sure you're cloning the benchmarking-tests branch?

**Comment by stephenberry** [comment]
I was able to replicate the issue and figured out problem. Will have a fix soon.

**Comment by RealTimeChris** [comment]
Nice - was it related to integer parsing?

**Comment by stephenberry** [comment]
Yeah, it was due to a `reinterpret_cast<uint8_t*&>(...)`. Reinterpreting to a pointer of the same size or to an unsigned integer is not UB, but doing both together is UB.
