### ISSUE TITLE
add assignment operator for std::string_view to glz::json_t

### ISSUE THREAD

**Issue by scalpel4k** [stephenberry/glaze#1411]
It would be neat if one could directly assign std::string_view to glz::json_t. It saves a few key strokes compared to making the copy outside ...

thx

**Comment by stephenberry** [comment]
Good suggestion. I'll plan to add this soon.

**Comment by stephenberry** [comment]
Support has been added into `main` to construct and assign from `std::string_view`. Will be included with the next release.
