### ISSUE TITLE
json_t::get<int>() fails with static assertion while json_t::get<double>() succeeds

### ISSUE THREAD

**Issue by hs-vc** [stephenberry/glaze#1487]
I’m encountering a compilation error when attempting to use json_t::get<int>() on a  generic JSON object. Using json_t.get<double>() on the same value compiles and runs fine. I tested this with Glaze v4.0.1 and GCC 14.2.0 on Linux.

**Error:**
```
/path/to/gcc/include/c++/14.2.0/variant:1152:42: error: static assertion failed: T must occur exactly once in alternatives
 1152 |       static_assert(__detail::__variant::__exactly_once<_Tp, _Types...>,
 ```
 
 **Example Code:**
 ```c++
 #include <glaze/json.hpp>

int main(int argc, char const *argv[]) {
    glz::json_t json{};
    std::string buffer = R"([5,"Hello World",{"pi":3.14}])";
    glz::read_json(json, buffer);

    auto v1 = json[0].get<double>(); // Works fine
    auto v2 = json[0].get<int>();    // Causes compilation error

    return 0;
}
```

 Is this behavior expected, or is it a bug?

**Comment by stephenberry** [comment]
I added documentation to [generic-json](https://github.com/stephenberry/glaze/blob/main/docs/generic-json.md) to add some explanation. Thanks for bringing this up!
