### ISSUE TITLE
reflection fails with anonymous namespaces

### ISSUE THREAD

**Issue by arturbac** [stephenberry/glaze#1501]
i use anonymous namespaces for blocks of code and struct declarations in translation units to hide symbols after linking.
Using a name from anonymous namespace fails compiling.

```cpp
namesapce {
  struct in_anon_namespace
    { 
    int a; 
    };
  }  // namespace
void test_anon()
{
  in_anon_namespace obj;
  glz::error_ctx res{glz::read_file_json(obj, "path", std::string{})};
}
```
```bash
In file included from glaze-src/include/glaze/json/json_t.hpp:11:
In file included from glaze-src/include/glaze/api/std/string.hpp:9:
In file included from glaze-src/include/glaze/core/meta.hpp:8:
glaze-src/include/glaze/reflection/get_name.hpp:24:19: error: variable 'glz::detail::external<(anonymous namespace)::in_anon_namespace>' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
   24 |    extern const T external;
```

**Comment by stephenberry** [comment]
I've run into this issue with automatic reflection. You can always use a `glz::meta`, but it would be nice to find an alternative solution that doesn't require extra typing, but I'm not sure if it is possible. I'll keep this issue alive until it has been looked at more closely.

For now, use a local meta or global meta to handle your struct.

**Comment by arturbac** [comment]
Ok I'll try to examine Your reflection substring.
I made it to work with simple enum for enums defined in inlined and anonymous namespaces so it is just another case of substr to handle.

**Comment by stephenberry** [comment]
Oh, I thought it was a linkage problem, not just a parsing issue. It would be great if it's just a parsing problem.

**Comment by arturbac** [comment]
compile error explains all

_is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage_

So the reflections get mangled names of extern declared objects of type T
```cpp
   template <class T>
   extern const T external;
```
to make it working with anonymous namespaces it cannot refer to external variable.
I need to think how to do it to get object pretty name without defining it.
In simple enum I do it by using function like
```cpp
   template <class T>
   auto mangled_name( T const & )
   { pretty_function from argument name }
```
so I don't have problems of that kind

**Comment by arturbac** [comment]
Ok this case is not about type but class member name.
Currently You obtain it from getting address of member from object so You need construct extern to avoid trying at compile time constructing object. You are using get<N>(to_tuple(t)); where t is an object
```cpp
std::string_view from_object{ glz::detail::get_name_impl<0,basic>};
```
But You can get pointer to member instead of address of object
directly from type T
```cpp
constexpr auto from_type{ glz::detail::mangled_name<&basic::my_member>() };

std::print("from_object {}\nfrom_type {}\n", from_object, from_type);
```
```bash
from_object auto glz::detail::mangled_name() [Ptr = ptr_t<std::remove_cvref_t<decltype(p)>>{&external.my_member}]
from_type auto glz::detail::mangled_name() [Ptr = &basic::my_member]
```

question is if to_tuple(t) can be modified to work as to_tuple<T>()

**Comment by stephenberry** [comment]
It can be achieved for structures that have a glz::meta defined. Because these provide the member object pointers. However, pure reflection blocks our ability to get member object pointers and we must use extern pointers to get the names.

If you discovered a way to get member object pointers from a structured binding that would be amazing, but I've tried hard and failed.

**Comment by arturbac** [comment]
- There is no way to get member pointer by index without object, still some instance is required
- can not get address of member from dereferencing nullptr
- can not return address of member from heap allocated object (after destruction)
- extern is probably the only way so there is no solution to this

But there is something i saw in Your code and I know from working on simple enum You can improve compile time performance
- finding anything in strings because it is linear it affects lineary time '''name.substr(name.find("GLAZE_REFLECTOR") + ''' , the shorter string less time it takes also if You can pre-calculate 'shortcuts' positions or increments it is worth doing that
- using functions like name.find is much slower that writing own pure pointer find loops, template significant causes slowdown, function call causes significant slowdown at compile time. It is definitely worth implementing own very simple loops for finding. I didn't liked to do that in simple enum but results in time trace had no mercy

**Comment by stephenberry** [comment]
Thanks for the feedback! I'll implement simple loops for searching, as it's always nice to reduce compile times. Your idea of pre-calculating shortcut positions is also smart.

**Comment by stephenberry** [comment]
I'm going to close this issue, but work on compile time performance as I'm able. Thanks for the feedback.
