### ISSUE TITLE
Very weird undefined behavior with the glaze library

### ISSUE THREAD

**Issue by hs-vc** [stephenberry/glaze#1507]
I encountered a very strange crash, and below is a minimal reproducible example. In this project, there is some redundant code that should not affect the program’s expected output, but removing or altering these seemingly unrelated parts prevents the crash

This issue was tested on Ubuntu 24.04 with glaze v4.0.1 and gcc 14.2.0.

src/main.cpp
```c++
#include <version> // Including this header triggers the undefined behavior, even though it's not otherwise used
#include <glaze/json.hpp>
#include <cassert>


int main(int argc, char const *argv[]) {
    auto has_value =  glz::json_t{}.dump().has_value(); // cause SIGSEGV or  SIGABRT
    assert(has_value);
    return 0;
}
```

src/unused.cpp
```c++
#include <glaze/json.hpp>

static bool unused_function() {
    return glz::json_t{}.dump().has_value();
}

```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.22)
project(glaze_test)

set(CMAKE_CXX_STANDARD 23)

find_package(glaze REQUIRED)


add_executable(glaze_test
        src/unused.cpp
        src/main.cpp
)

target_link_libraries(glaze_test
        PRIVATE
        glaze::glaze
)
```

**Comment by stephenberry** [comment]
That is very strange and very bad. I'll dig into it as soon as I'm able. One quick test I'm curious about is whether this issue still exists if you name the variable something other than `json`, since nholmann uses this name everywhere.

**Comment by stephenberry** [comment]
I tried to replicate this error here: #1508. However, it is passing GCC 14.2.0 with the latest Glaze version (v4.2.0).
Can you test the latest Glaze version? Is there some other way I need to setup the environment?
Are you building with C++23?

**Comment by stephenberry** [comment]
Thanks for uncovering this. It feels like a GCC compiler bug. I will dig a little deeper and submit an issue to the GCC team if I can't uncover anything. My suspicion is that it has to do with the c++ feature macro for std::expected, as Glaze aliases std::expected if it is available.
I also have a pull request open to remove the custom glz::expected, since the supported compilers no longer need it.

**Comment by hs-vc** [comment]
It seems the issue is caused by file https://github.com/stephenberry/glaze/blob/90e5309b13a9f8be9fd2e052579a8a0bd8db9df0/include/glaze/util/expected.hpp#L52

It appears that the `<version>` header is missing in this file before the `__cpp_lib_expected` macro is used. In my example code, only one of the two source files include `<version>`, leading to the inclusion of `<expected>` in one unit and `<experimental/expected>` in another. This causes a conflict between the two.

To resolve this issue, I believe the file should explicitly include the <version> header.

**Comment by stephenberry** [comment]
Ah, that's it! Thanks! I'll make that change ASAP.
