### ISSUE TITLE
glz::merge writes erroneous comma when object is empty

### ISSUE THREAD

**Issue by SenseOnline** [stephenberry/glaze#1520]
I am attempting to modify an existing json that may contain additional fields using the following excerpt 
```cpp
struct {
  std::string hello;
} data;
std::vector<int> my_arr;
std::map<std::string_view, std::raw_json_view> potentiallyContainsUnknownJSON;

/* ... read code ... */

data.hello = "goodbye";
glz::write_json(glz::merge{
  glz::obj{ 
      "my_arr", my_arr, 
      "data", metadata
  },
  potentiallyContainsUnknownJSON
});
```

input: 
```json
{"my_arr":[1,2,3],"data":{"hello":"world"} }
```
expected output:
```json
{"my_arr":[1,2,3],"data":{"hello":"goodbye"}}
```
actual output:
```json
{"my_arr":[1,2,3],"data":{"hello":"goodbye"},}
```

Is there a way to work around this or an alternative to achieve the same effect?

**Comment by stephenberry** [comment]
Thanks for reporting this. This was an issue with merging empty objects with `glz::merge`. I included a fix in my active pull request that I just merged: #1519. So, the `main` branch should now work for you.
