### ISSUE TITLE
Ubuntu build instructions and dependencies

### ISSUE THREAD

**Issue by vaskark** [stephenberry/glaze#1530]
Hi. Can someone do me a favour and explicitly state the build instructions for glaze? If they are listed anywhere I can't find them. And any dependencies I might need?

Thanks.

Edit: This is what I tried...

```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -Wno-dev -S . -B ./build
cmake --build ./build -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
```

And I got this error:

```
1 error generated.
gmake[2]: *** [tests/json_test/CMakeFiles/json_test.dir/build.make:76: tests/json_test/CMakeFiles/json_test.dir/json_test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1738: tests/json_test/CMakeFiles/json_test.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
1 error generated.
gmake[2]: *** [tests/json_test/CMakeFiles/json_test_non_null.dir/build.make:76: tests/json_test/CMakeFiles/json_test_non_null.dir/json_test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1764: tests/json_test/CMakeFiles/json_test_non_null.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

**Comment by stephenberry** [comment]
Glaze is only headers and has no dependencies, so you shouldn't need to build it separately from the project you use it in.
If you're trying to build the test projects as your error is indicating, you should use typically CMake instructions.
Next week I can add more documentation and details if you need them.
The README should point to an example project that shows how to include Glaze via CMake.
You can also use a build system like Conan.

**Comment by vaskark** [comment]
Thanks for responding. 

I'm just trying to build glaze because it's now a requirement of Hyprland (git).

I'll keep at it.

**Comment by vaskark** [comment]
Me again.

Glaze was made an internel dependency and is now fetched and built along with Hyprland.
Closing.

**Comment by stephenberry** [comment]
Thanks for updating me and figuring out a solution. If you have any tips for improving the documentation in Glaze, just let me know.
