### ISSUE TITLE
Extra glaze directory when installing, some unused files are being installed?

### ISSUE THREAD

**Issue by Peanhua** [stephenberry/glaze#154]
When doing ```make install``` after building, the include directory is buried inside two glaze's, the other one feels unnecessary:
```
$ cmake --install-prefix=/usr/local ..
...
$ make
...
$ make install
...
-- Installing: /usr/local/include/glaze/glaze/util/bit.hpp
...
```
Would prefer seeing:
```
-- Installing: /usr/local/include/glaze/util/bit.hpp
```

Also some files are installed even if they don't seem to be used:
```
...
-- Installing: /usr/local/lib/cmake/ut-1.1.9/utTargets.cmake
-- Installing: /usr/local/lib/cmake/ut-1.1.9/utConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/ut-1.1.9/utConfig.cmake
-- Installing: /usr/local/include/ut-1.1.9/include
-- Installing: /usr/local/include/ut-1.1.9/include/boost
-- Installing: /usr/local/include/ut-1.1.9/include/boost/ut.hpp
$ grep -r ut.hpp /usr/local/include/glaze | wc
      0       0       0
$ grep -r ut.hpp /usr/local/share/glaze | wc
      0       0       0
$
```

If they are needed, it's a bit weird that the cmake files are placed in different directory structure than glaze's own, ```PREFIX/lib/cmake/...``` vs ```PREFIX/share/...```:
```
-- Installing: /usr/local/share/glaze/glazeConfig.cmake
-- Installing: /usr/local/share/glaze/glazeConfigVersion.cmake
-- Installing: /usr/local/share/glaze/glazeTargets.cmake
```

**Comment by mwalcott3** [comment]
Thanks for pointing this out. 

#155 removes the boost ut stull from the installation and gets ride of the glaze/glaze nesting.

We tend to use FetchContent over find_package so we don't always notice problems with the install target.  So I added an install/find_package test to the github workflows to make sure we at least don't break the install target. It wouldnt have helped in this case but good to have nonetheless.
