### ISSUE TITLE
json_ptr.hpp:514:102: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by chill1n** [stephenberry/glaze#158]
Building with GCC 10.3 (-std=c++20) on Ubuntu 20.04 and cmake 3.22.0 I get the following issue during build:

/home/developer/workspace/test/glaze/release/_deps/glaze-src/include/glaze/json/json_ptr.hpp: In function ‘constexpr bool glz::valid()’:
/home/developer/workspace/test/glaze/release/_deps/glaze-src/include/glaze/json/json_ptr.hpp:514:102: internal compiler error: Segmentation fault
  514 |             using G = member_getter<V, glz::detail::string_literal_from_view<key_str.size()>(key_str)>;
      |                                                                                                      ^
0x7f275468208f ???
        /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f2754663082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.

In the project I would like to use glaze I'm restricted to gcc 10.3.0 at this moment.
Is there a way to work-around this issue?

You should be able to reproduce this using the code snippet:
```c++
#include <glaze/glaze.hpp>

int main()
{

    glz::recorder<double, float> rec;

    double x = 0.0;
    float y = 0.f;

    rec["x"] = x;
    rec["y"] = y;

    for (int i = 0; i < 100; ++i) {
       x += 1.5;
       y += static_cast<float>(i);
       rec.update(); // saves the current state of x and y
    }

    glz::write_file_json(rec, "recorder_out.json");
    
}
```

**Comment by stephenberry** [comment]
We'll have to look into whether we can get gcc 10 to work. Right now we're just supporting gcc 11 and beyond. Thanks for pointing this out.

**Comment by stephenberry** [comment]
After looking more at the gcc 10 support for C++20 I just don't think we'll be able to support that compiler version. We're trying to embrace C++20 with Glaze and gcc 10 just lacks too many useful features from C++20. Sorry for this inconvenience.

**Comment by mwalcott3** [comment]
gcc10 support was added by @fregate in #190 and has been added as a tested compiler in the in #199.

**Comment by chill1n** [comment]
Very nice, and thanks a lot. But I already migrated to gcc-11 to enjoy more of c++20. :)
I'm sure this will increase the application range for glaze, though.
