### ISSUE TITLE
any plan support idl file?

### ISSUE THREAD

**Issue by romanholidaypancakes** [stephenberry/glaze#16]
automatically output the corresponding structure according to idl,no need to manually enter the following code

```
template <>
struct glz::meta<my_struct> {
   using T = my_struct;
   static constexpr auto value = object(
      "i", &T::i,
      "d", &T::d,
      "hello", &T::hello,
      "arr", &T::arr
   );
```

**Comment by stephenberry** [comment]
idl files are not currently on our roadmap, but it is an interesting proposition. I'll keep it in mind, but it probably won't happen soon unless someone wants to contribute or the team I lead finds a need for it.
