### ISSUE TITLE
Dump null instead of infinity or nan by default

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#160]
For proper JSON compliance.

**Comment by mwalcott3** [comment]
validation and conformance stuff is bundled in with the noexcept stuff in #156

**Comment by mwalcott3** [comment]
I just jumped the gun and merged it in separately #171 since someone was asking about the nan stuff and the noexcept might take a bit longer to be ready. Sorry in advance about the merge conflicts.
