### ISSUE TITLE
OOB read of table end position

### ISSUE THREAD

**Issue by friendlyanon** [stephenberry/glaze#176]
Definition:

https://github.com/stephenberry/glaze/blob/6931d824071253c621c24aa39ef181545fb5a246/include/glaze/util/hash_map.hpp#L238

Out of bound read:

https://github.com/stephenberry/glaze/blob/6931d824071253c621c24aa39ef181545fb5a246/include/glaze/util/hash_map.hpp#L291-L295

The check before accessing the OOB offset misses the end position.

**Comment by mwalcott3** [comment]
Thank you, It has been fixed in main.
