### ISSUE TITLE
Can not read json file

### ISSUE THREAD

**Issue by LiMYmy** [stephenberry/glaze#184]
```read_file``` is not working well with version ```1.0.0```.
Here is the code.
```
#include "glaze/glaze.hpp"

struct my_struct
{
  std::string name;
  std::string label;

  struct glaze {
    using T = my_struct;
    static constexpr auto value = glz::object(
        "name", &T::name,
        "label", &T::label
    );
  };
};

int main(int argc, char const *argv[])
{
  std::string file = "../file.json";
  my_struct s;
  auto ec = glz::read_file(s, file);
  if (ec) {
    std::string descriptive_error = glz::format_error(ec, file);
  }
  
  return 0;
}
```
Here is the json file
```
{
  "name": "my",
  "label": "label"
}
```
It works with version ```0.3.6```.

**Comment by LiMYmy** [comment]
![image](https://user-images.githubusercontent.com/72388584/222653489-09610993-38e5-458c-be3d-5297bf6535f4.png)

**Comment by mwalcott3** [comment]
Thank you for reporting this. I can't seem to replicate the read access violation but it reminds me of an error I saw on certain versions of MSVC. If this is MSVC this might be related to an issue I saw that should have been addressed in ea708376bdfe5dbe4c38b7d03f5145956c329f28. Are you using the latest commit or the v1.0.0 tag?

Could you try pulling the latest commit to see if that fixes your issue?
If not do you mind me asking what compiler, compiler version number, and flags are you using?

**Comment by stephenberry** [comment]
I just put out a v1.0.1 release as well, which includes the fix.

**Comment by LiMYmy** [comment]
Now it works with version ```1.0.1```. Thanks for the timely fix.

**Comment by LiMYmy** [comment]
By the way, I am confused about using ```glz::format_error(ec, file)```. It looks like that the second param need to be ```buffer```, but I only have a file name when using ```read_file```. What should I do?

**Comment by mwalcott3** [comment]
> By the way, I am confused about using `glz::format_error(ec, file)`. It looks like that the second param need to be `buffer`, but I only have a file name when using `read_file`. What should I do?

Yeah, that is a bit annoying. Your best bet right now is probably to break up the call glz::file_to_buffer, glz::read_json, then glz::format_error.
