### ISSUE TITLE
Are there plans to add this library to the conan center?

### ISSUE THREAD

**Issue by PikachuHyA** [stephenberry/glaze#23]
https://conan.io

Conan Center

https://conan.io/center/

**Comment by stephenberry** [comment]
Yes, we plan to. I'll keep this issue as a reminder.

**Comment by Ahajha** [comment]
I have a recipe ready, I will probably create a pull request within a few days. I wanted to wait for the initial surge of fixes to settle down.

**Comment by Ahajha** [comment]
Looks like someone beat me to the punch, it seems it's already there: https://github.com/conan-io/conan-center-index/pull/13499

**Comment by stephenberry** [comment]
Issue solved: https://github.com/conan-io/conan-center-index/pull/13499

**Comment by Ahajha** [comment]
@stephenberry FYI I think you can remove the link to my recipe in the README. The one in Conan Center is actually maintained, and should be what people use.

**Comment by stephenberry** [comment]
@Ahajha, thanks! Will do.
