### ISSUE TITLE
I cant use concepts!

### ISSUE THREAD

**Issue by edwardbr** [stephenberry/glaze#250]
Hi I am writing in intel sgx enclaves, this uses effectively embedded programming platform and often (as in my case) has partial or missing implementations of the standard library.  e.g. access to a filesystem.  Unfortunately I have tried compiling your library and the biggest blocker is that intel sgx does not support c++20 concepts.  Do you think that it would it be gratuitously complicated if I tried to strip them out?

**Comment by stephenberry** [comment]
Thanks for your interest, and as much we'd like to support as many compilers as possible, I don't see removing concepts as feasible. Not only do concepts make the code much cleaner and producer better errors, but they also allow us to avoid the compiler producing intermediate code that would cause compilation errors. There are cases where concepts like `std::invocable` make it possible to build code that previously would have been very difficult to manage (`std::is_invocable_v` won't guard against compilation errors in some of these cases). The ability to introspect function calls, check member function names, and so forth, make concepts significantly more powerful than traditional `std::enable_if` approaches.

So, I think you're best off using another library until support for concepts is added to your compiler. I wish you all the best with your development!

**Comment by edwardbr** [comment]
OK many thanks for your answer!
