### ISSUE TITLE
Would you consider making this library available through vcpkg?

### ISSUE THREAD

**Issue by sanjayatn** [stephenberry/glaze#254]
I have been using vcpkg to install my dependencies and it works well for me so far. Are you planning to support it in the future?

**Comment by stephenberry** [comment]
I've never used vcpkg, but I wouldn't be against supporting it. I would be more open to adding support if someone who is used to vcpkg like yourself submitted a pull request adding the support.

**Comment by omarhogni** [comment]
I created a pull request to vcpkg adding glaze
https://github.com/microsoft/vcpkg/pull/30966

**Comment by omarhogni** [comment]
Glaze has been merged into vcpkg.
