### ISSUE TITLE
Map values to a different struct (not subclass)

### ISSUE THREAD

**Issue by RozeFound** [stephenberry/glaze#257]
I have to work with a bit funky structured json, and I want to map things a bit differently, so I tried to map values from one structures to another. I missing something, or this is actually impossible?

Code:
```cpp
struct Scene {

    struct Camera {

        std::string_view center;
        std::string_view eye;
        std::string_view up;

        std::vector<std::string_view> paths;

        bool fade;
        bool preview;

        struct Parallax {
            bool enabled;
            float amount;
            double delay;
            int mouse_influence;
        } parallax;

        struct Shake {
            bool enabled;
            float amplitude;
            int roughness;
            int speed;
        } shake;

    } camera;

    struct General {

        std::string_view ambient_color;

        bool bloom;
        int bloom_strength;
        double bloom_threshold;

        bool norecompile;

        std::string_view clear_color;
        std::optional<bool> clear_enabled;

        struct OrthogonalProjection {
            int height;
            int width;
        } orthogonalprojection;

        std::string_view skylight_color;

    } general;

    std::vector<Object> objects;

};

GLZ_META(Scene, camera, general, objects);
GLZ_META(Scene::Camera, center, eye, up, paths);
template <> struct glz::meta<Scene::General> {

    using T = Scene::General;

    using general_t = Scene::General;
    using camera_t = Scene::Camera;
    using parallax_t = camera_t::Parallax;
    using shake_t = camera_t::Shake;

    static constexpr auto value = glz::object (

        "ambientcolor", &general_t::ambient_color,

        "bloom", &general_t::bloom,
        "bloomstrength", &general_t::bloom_strength,
        "bloomthreshold", &general_t::bloom_threshold,

        "norecompile", &general_t::norecompile,

        "camerafade", &camera_t::fade,
        "camerapreview", &camera_t::preview,

        "cameraparallax", &parallax_t::enabled,
        "cameraparallaxamount", &parallax_t::amount,
        "cameraparallaxdelay", &parallax_t::delay,
        "cameraparallaxmouseinfluence", &parallax_t::mouse_influence,

        "camerashake", &shake_t::enabled,
        "camerashakeamplitude", &shake_t::amplitude,
        "camerashakeroughness", &shake_t::roughness,
        "camerashakespeed", &shake_t::speed,

        "clearcolor", &general_t::clear_color,
        "clearenabled", &general_t::clear_enabled,

        "orthogonalprojection", &general_t::orthogonalprojection,

        "skylightcolor", &general_t::skylight_color

    );

};
GLZ_META(Scene::General::OrthogonalProjection, height, width);
```

If I remove all camera-related stuff from meta, it compiles, otherwise gives a lot of errors.

**Comment by stephenberry** [comment]
Typically, I would recommend mapping the JSON in the same format as your C++, so `Camera` and `General` would be subjects within `Scene`. In this case you would create separate meta objects for each class.

If you want to map values into a different struct, this can be done for sub-components. However, you cannot map camera components to the `General` struct, because the `General` struct does not contain the camera or any of its components. If you gave the `General` struct a pointer to `Camera`, then you could achieve this mapping by registering lambdas with the meta, but that doesn't seem logical.

Because the `Scene` contains everything, you can remap the items within the scene. Below is a snippet:
```c++
template <> struct glz::meta<Scene> {
   using T = Scene;
  static constexpr auto value = glz::object("camerafade", [](Scene& s) -> auto& { return s.camera.fade;  });
};
```

This would map the camera fade to the top level of the scene.

> I will also note that your use of `std::string_view` is fine only if you intend to keep the input buffer alive. Remember that `std::string_view` does not hold onto the memory, so if you load in a JSON document and delete the buffer, the memory all the string views are pointing to will have been destroyed. I would venture to guess they should all use `std::string`, but I could be wrong based on your use case.

If you could simplify this a bit and show what you want the JSON file to look like, I could show you how to do it in code.

**Comment by RozeFound** [comment]
The problem is, it's not JSON that I created, I can only read it.
Also camera fade not in `Scene`, it's in `Scene::General` that's what I'm struggling with.
Regarding to your advise, input buffer is guaranteed to exists as long as resources from it in use.

The JSON file I'm working with:
```json
{
	"camera" : 
	{
		"center" : "192.479 14.304 0.000",
		"eye" : "192.479 14.304 1.000",
		"up" : "0.000 1.000 0.000"
	},
	"general" : 
	{
		"ambientcolor" : "0.3 0.3 0.3",
		"bloom" : false,
		"bloomstrength" : 2,
		"bloomthreshold" : 0.64999997615814209,
		"camerafade" : true,
		"cameraparallax" : false,
		"cameraparallaxamount" : 0.5,
		"cameraparallaxdelay" : 0.10000000149011612,
		"cameraparallaxmouseinfluence" : 0,
		"camerapreview" : true,
		"camerashake" : false,
		"camerashakeamplitude" : 0.5,
		"camerashakeroughness" : 1,
		"camerashakespeed" : 3,
		"clearcolor" : "0.7 0.7 0.7",
		"clearenabled" : null,
		"orthogonalprojection" : 
		{
			"height" : 2160,
			"width" : 3840
		},
		"skylightcolor" : "0.3 0.3 0.3"
	},
	"objects" : { /* Not a subject of the case */ } 
}
```

I can try to create some simplified example instead of providing the real data, if it'll help

**Comment by RozeFound** [comment]
While this does make sense and is a working approach, this looks kinda hacky.
Wouldn't it be a good idea to have something like my initial approach work out of the box?
I don't think I'm the only one who have to work with awkwardly structured JSON

**Comment by stephenberry** [comment]
Yes, we want to make mapping easier, but we are limited by needing the memory to be directly addressable for the sake of performance. Approaches that do not make memory available can be a bit cleaner, but they have huge performance implications. So, the goal is to make mapping easier without sacrificing performance, which is tricky.

You can always use the generic json (glz::json_t) to handle any format, but this is much less performant and not generally recommended.

**Comment by RozeFound** [comment]
Also the errors are useless if you try to map something to a different struct, spent like an hour trying to figuring out what's wrong. At least you can improve on this front, or simply document. On this note I'll close the issue, you were a great help, also great library btw

**Comment by stephenberry** [comment]
Thanks for pointing out problems with errors. Will definitely try to improve the library in that area. It's always helpful to see other's use cases, so thanks for explaining your challenges. Hope the library works well for you!
