### ISSUE TITLE
Cannot support the same key

### ISSUE THREAD

**Issue by hulingyue** [stephenberry/glaze#258]
{
    "arg": {
        "channel": "tickers",
        "instId": "LTC-USD-200327"
    },
    "data": [{
        "instType": "SWAP",
        "instId": "LTC-USD-200327",
        "last": "9999.99",
        "lastSz": "0.1",
        "askPx": "9999.99",
        "askSz": "11",
        "bidPx": "8888.88",
        "bidSz": "5",
        "open24h": "9000",
        "high24h": "10000",
        "low24h": "8888.88",
        "volCcy24h": "2222",
        "vol24h": "2222",
        "sodUtc0": "2222",
        "sodUtc8": "2222",
        "ts": "1597026383085"
    }]
}

It's a response from okex. I failed to parsing the json string , due to 'arg' and 'data' both has a key 'instId'

**Comment by stephenberry** [comment]
This shouldn't be a problem, because the key is used in different contexts. Could you share some of your glaze code? It is most likely a registration problem.

**Comment by hulingyue** [comment]
> This shouldn't be a problem, because the key is used in different contexts. Could you share some of your glaze code? It is most likely a registration problem.

Of cause. 
I found the error: note: non-constexpr function 'glaze_error' cannot be used in a constant expression
            glaze_error("Unable to find perfect hash");

so i think maybe i can expand the bucket. So i change the function: `template <size_t N>
      constexpr auto naive_bucket_size() noexcept
      {
         return N < 8 ? 3 * N : 6 * N;
      }` and then compilation passed


Those are some of my code, hope those can help you recurrence issues

**Comment by hulingyue** [comment]
GLZ_META(OkexMarketJsonStruct::OkexMarketCommonRequestParameter, channel, instId);
GLZ_META(OkexMarketJsonStruct::OkexMarketEventSuccessArg, channel, instId);
GLZ_META(OkexMarketJsonStruct::OkexMarketDepthResponseDataParameter, asks, bids, ts, checksum);
GLZ_META(OkexMarketJsonStruct::OkexMarketBboResponseDataParameter, instType, instId, last, lastSz, askPx, askSz, bidPx, bidSz, open24h, high24h, low24h, volCcy24h, vol24h, sodUtc0, sodUtc8, ts);

template <typename A>
struct glz::meta<OkexMarketJsonStruct::OkexMarketCommand <A>> {
    using T = OkexMarketJsonStruct::OkexMarketCommand <A>;
    static constexpr auto value = object(
        "op", &T::op,
        "args", &T::args
    );
};

template <typename A>
struct glz::meta<OkexMarketJsonStruct::OkexMarketEventSuccessResponse <A>> {
    using T = OkexMarketJsonStruct::OkexMarketEventSuccessResponse <A>;
    static constexpr auto value = object(
        "event", &T::event,
        "arg", &T::arg
    );
};
GLZ_META(OkexMarketJsonStruct::OkexMarketEventFailureResponse, event, code, msg);

template <typename A, typename B>
struct glz::meta<OkexMarketJsonStruct::OkexMarketDataResponse <A, B>> {
    using T = OkexMarketJsonStruct::OkexMarketDataResponse <A, B>;
    static constexpr auto value = object(
        "arg", &T::arg,
        "action", &T::action,
        "data", &T::data
    );
};

**Comment by stephenberry** [comment]
The `naive_bucket_size()` function was removed in the latest codebase (I know release 1.2.0 has these changes). If you update to the latest code it uses `static constexpr size_t bucket_size = (N > 16 ? 8 : 4) * std::bit_ceil(N);`

This makes the bucket size even larger than your changes and should compile.

Let me know if you have issues compiling with the latest version of Glaze.

**Comment by hulingyue** [comment]
> The `naive_bucket_size()` function was removed in the latest codebase (I know release 1.2.0 has these changes). If you update to the latest code it uses `static constexpr size_t bucket_size = (N > 16 ? 8 : 4) * std::bit_ceil(N);`
> 
> This makes the bucket size even larger than your changes and should compile.
> 
> Let me know if you have issues compiling with the latest version of Glaze.

OK , Thanks you for you help! 👍 :)

**Comment by mwalcott3** [comment]
I think we need to test the bitmix function and use a better one. The one used now is pretty arbitrary and probably sucks. We don't need it to be great but If its too bad it may cause stuff to fail to compile. Also we should have a fallback map if we fail instead of failing to buil.

Assuming perfect statistical properties of the underlying hash function I think the old bucket sizes would have around a 1/2880798 chance (Which is way too low) of failing at 32 keys after 1024 iterations and that now should be approx 1 in 1e63 or so. However the last version with naive_bucket_size function was capped out at 20 keys so I think the expected chance of failing used to be around 3e+34 worst case.

That hash function is quite possibly the worst hash function in existence. I think there is an additional xor shift in there so its likely not as bad now. But realistically this is a sign we should just use more established bitmixing function like.
```c++
  h ^= h >>> 33;
  h *= 0xff51afd7ed558ccdL;
  h ^= h >>> 33;
  h *= 0xc4ceb9fe1a85ec53L;
  h ^= h >>> 33;
```
