### ISSUE TITLE
Custom serializer from a string

### ISSUE THREAD

**Issue by Ahajha** [stephenberry/glaze#268]
Is it possible to serialize from a string using a custom parser? My specific use case is I have UUIDs in string form (something like "0c724964-cb3c-4b21-8ce5-7039ab7c4ecb") and I would prefer if possible to serialize directly into a UUID type (the UUID library we use has a parser from a string view), rather than allocating a string just to throw it away later. I presume there is some sort of internal buffer, so perhaps I could get a view of that when parsing UUIDs?

Thanks!

**Comment by stephenberry** [comment]
Yes, you can customize your serialization for any of your types or third party types. See the documentation here: [docs/custom-serialization.md](https://github.com/stephenberry/glaze/blob/main/docs/custom-serialization.md)

I added a possible example of your use case to the documentation, which is the same as below:

Say we have a UUID library for converting a `uuid_t` from a `std::string_view` and to a `std::string`.

```c++
namespace glz::detail
{
   template <>
   struct from_json<uuid_t>
   {
      template <auto Opts>
      static void op(uuid_t& uuid, auto&&... args)
      {
         // Initialize a string_view with the appropriately lengthed buffer
         // Alternatively, use a std::string for any size (but this will allocate)
         std::string_view str = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
         read<json>::op<Opts>(str, args...);
         uuid = uuid_lib::uuid_from_string_view(str);
      }
   };

   template <>
   struct to_json<uuid_t>
   {
      template <auto Opts>
      static void op(uuid_t& uuid, auto&&... args) noexcept
      {
         std::string str = uuid_lib::uuid_to_string(uuid);
         write<json>::op<Opts>(str, args...);
      }
   };
}
```

**Comment by Ahajha** [comment]
Excellent! Question about the parsing buffer, what does it do in the case of overflow? I'm assuming it doesn't throw, so there must be some other way to indicate the error? Also, if it's too short, does `str` get shorter (forcing the UUID parse to fail)?

**Comment by stephenberry** [comment]
It stores an error code, just like normal, which is returned from `glz::read_json`. If it is shorter, yes the string_view will get shorter and the UUID parse should then fail.

**Comment by Ahajha** [comment]
Interesting, is it possible to read the code to fail faster in that case?
(Also, just out of curiosity, where is the error code stored? Is that somewhere in `args...`?)

**Comment by stephenberry** [comment]
Yes, you can read the error from the `glz::context`, which is part of the args. In the code you'll see a lot of the following:
```c++
if (bool(ctx.error)) [[unlikely]]
   return;
```

The program should already fail fast because all the other glaze functions check and short circuit the code if an error is detected.

This is `(auto& value, auto&&... args)` expanded: `(auto& value, glz::context&& ctx, It&& it, End&& end)`

The error is stored in the context (`ctx.error`).

**Comment by Ahajha** [comment]
One last thing, if the parse into a UUID fails, how can I make that into a glaze failure? Currently it throws an exception (not a fan, but that's what it does).

**Comment by mwalcott3** [comment]
You can set the error code in the context and return. The internal glaze read code will propagate the error code up the stack. 

I don't think there are custom errors at this time if that is what you are asking for. There are kludges/hacks you can do if you want (Static cast a custom error code into ctx.error, use a static threadlocal string to store error messages etc.). There probably should be a way to extend the built in errors but that's a separate issue.

**Comment by Ahajha** [comment]
Awesome, that should be everything I need, thanks!

I'll leave this open while I prototype incase anything comes up, if I don't say anything for a few days feel free to close it :)

**Comment by stephenberry** [comment]
I'll just make a note that you can still use a try-catch block around your `glz::read_json` to catch the uuid error. But, now you have two error checking mechanisms going on. I would do as @mwalcott3 said and have a try catch inside of the custom parse code and set the context error.
