### ISSUE TITLE
Shorthand Way to Serialize/Deserialize Json To/From Struct?

### ISSUE THREAD

**Issue by gurbaaz27** [stephenberry/glaze#27]
Hi! I wanted to know if glaze has some shorthand way to serialize/deserialize a json to/from struct, like the one nlohmann json provides with `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE` and `NLOHMANN_DEFINE_TYPE_INTRUSIVE` macros. To quote their solution, 
![image](https://user-images.githubusercontent.com/60743677/197758741-91f06b1e-07df-43d8-879b-757f2c524750.png)

If not yet, are there any plans to implement a similar or better thing? Since otherwise basic serialization/deserialization of deeply nested structs become a big pain.

**Comment by mwalcott3** [comment]
No, this doesn't exist currently. Yes, this will probably be added soon. It's really simple to add some convenience macros and prevents quite a bit of duplication.

**Comment by stephenberry** [comment]
Shorthand macros have been added. Thanks for raising this issue.

Documentation has been added to the readme. Here's the example:

> In order to use these macros you must include the header: glaze/core/macros.hpp

- GLZ_META is for external registration
- GLZ_LOCAL_META is for internal registration

```c++
struct macro_t {
   double x = 5.0;
   std::string y = "yay!";
   int z = 55;
};

GLZ_META(macro_t, x, y, z);

struct local_macro_t {
   double x = 5.0;
   std::string y = "yay!";
   int z = 55;
   
   GLZ_LOCAL_META(local_macro_t, x, y, z);
};
```
