### ISSUE TITLE
Why does glz::format_error not take a const ref to buffer ?

### ISSUE THREAD

**Issue by rajkosto** [stephenberry/glaze#274]
`[[nodiscard]] inline std::string format_error(const parse_error& pe, auto& buffer)`
the auto& here prevents me from passing a const std::string& as the buffer (which works for read_json)
this variable is only used inside the body of this function as a const auto& argument, so i think it should be const auto& in this function's signature as well.

**Comment by stephenberry** [comment]
Thanks! Fixed in #278
