### ISSUE TITLE
write.hpp ostream support function missing index parameter in internal call

### ISSUE THREAD

**Issue by rajkosto** [stephenberry/glaze#275]
```
   // For writing json to std::ofstream, std::cout, or other streams
   template <opts Opts, class T>
   inline void write(T&& value, std::ostream& os, is_context auto&& ctx) noexcept
   {
      detail::write<Opts.format>::template op<Opts>(std::forward<T>(value), ctx, std::ostreambuf_iterator<char>(os));
   }
```

Getting
`error C2780: 'void glz::detail::write<10>::op(T &&,Ctx &&,B &&,IX &&)': expects 4 arguments - 3 provided`

unable to write to std::ostream because of this error, maybe something else is wrong though

**Comment by mwalcott3** [comment]
@stephenberry Are streams still supported? I thought the stream support and non ix write stuff got stripped out.

**Comment by stephenberry** [comment]
@mwalcott3 Yeah, I think that is just leftover cruft.

**Comment by rajkosto** [comment]
if ostreams are not supported anymore, what is the preferred way of outputting json into something like a boost::beast::multi_buffer used by boost::beast::dynamic_body
i thought i could just wrap it in boost::beast::ostream and output the json that way

**Comment by mwalcott3** [comment]
Ideally you could directly write to the buffer but Im not familiar with boost::beast . Otherwise you will have to copy the data to the buffer. Not too familiar with beast but I think the following might work.
```c++
size_t n = boost::asio::buffer_copy(buffer.prepare(json.size()), boost::asio::buffer(json));
buffer.commit(n);
```

The problem with using the stream iterators the way glaze was using them is that it would result in multiple virtual function calls for basically every single char. So it was more memory efficient due to buffered io but introduces quite a bit of overhead.

Unlike the read stuff that has a ton of stuff assuming contiguous ranges for optimizations it would be much easier to support streams for writing since that's pretty much isolated to dump. However due to the heavy use of polymorphism in C++ streams paired with faster IO times Im not sure its worth it.

**Comment by rajkosto** [comment]
Yeah i currently use
```
vector<char> bodyBuf;
glz::write<writeOpts>(obj,bodyBuf);
boost::asio::buffer_copy(body.prepare(bodyBuf.size()),boost::asio::buffer(bodyBuf.data(),bodyBuf.size()));
body.commit(bodyBuf.size());
```

but i was hoping to avoid the temporary buffer

**Comment by mwalcott3** [comment]
> Yeah i currently use
> 
> ```
> vector<char> bodyBuf;
> glz::write<writeOpts>(obj,bodyBuf);
> boost::asio::buffer_copy(body.prepare(bodyBuf.size()),boost::asio::buffer(bodyBuf.data(),bodyBuf.size()));
> body.commit(bodyBuf.size());
> ```
> 
> but i was hoping to avoid the temporary buffer is it possible to have glaze repeatedly write whatever is left to a fixed size buffer instead (so pause and continue) ? i can then keep appending the contents of that smaller temporary buffer to the beast multi buffer

Up to @stephenberry. Alternatively we could add support for iterators then you could use boost::asio::buffer_sequence_begin(x) and boost::asio::buffer_sequence_end(x) but I find that unlikely considering it was supported originally but was removed a long time ago.

**Comment by stephenberry** [comment]
Yeah, I don't think we'll directly support streams any time soon, as typically contiguous buffers are the way to go.
Note that boost::asio::buffer is a contiguous buffer, which you can just pass a std::string to. So, your above code:
```c++
vector<char> bodyBuf;
glz::write<writeOpts>(obj,bodyBuf);
boost::asio::buffer_copy(body.prepare(bodyBuf.size()),boost::asio::buffer(bodyBuf.data(),bodyBuf.size()));
body.commit(bodyBuf.size());
```
Can be written as:
```c++
std::string bodyBuf;
glz::write<writeOpts>(obj,bodyBuf);
boost::asio::buffer body(bodyBuf);
```

This will remove the copy, and if you're able to keep the `bodyBuf` alive for multiple calls, then you'll be reusing your allocation. These changes will improve performance.

Here is the code for boost asio that shows how it is just using the string pointer:
```c++
/// Create a new modifiable buffer that represents the given string.
/**
 * @returns <tt>mutable_buffer(data.size() ? &data[0] : 0,
 * data.size() * sizeof(Elem))</tt>.
 *
 * @note The buffer is invalidated by any non-const operation called on the
 * given string object.
 */
template <typename Elem, typename Traits, typename Allocator>
ASIO_NODISCARD inline ASIO_MUTABLE_BUFFER buffer(
    std::basic_string<Elem, Traits, Allocator>& data) ASIO_NOEXCEPT
{
  return ASIO_MUTABLE_BUFFER(data.size() ? &data[0] : 0,
      data.size() * sizeof(Elem)
#if defined(ASIO_ENABLE_BUFFER_DEBUGGING)
      , detail::buffer_debug_check<
          typename std::basic_string<Elem, Traits, Allocator>::iterator
        >(data.begin())
#endif // ASIO_ENABLE_BUFFER_DEBUGGING
      );
}
```

**Comment by rajkosto** [comment]
beast multi buffer is a sequence of boost::asio::buffers not a single one, `body.prepare` gives a beast "MutableBufferSequence" which lets you iterate over the buffers and fill them (using the buffer copy helper function does that), then commit the actual number of bytes written to them

**Comment by stephenberry** [comment]
Right. If you can use `beast::flat_buffer` then you could avoid the copy.
