### ISSUE TITLE
Why is study.hpp and thus threadpool.hpp included by default in glaze/json.hpp (which is included by other files) ?

### ISSUE THREAD

**Issue by rajkosto** [stephenberry/glaze#276]
I compile on windows but do not include <windows.h> in most files which makes the following errors if threadpool.hpp is included:
```
1>glaze\thread\threadpool.hpp(31,28): error C3861: 'GetActiveProcessorGroupCount': identifier not found
1>glaze\thread\threadpool.hpp(37,17): error C3861: 'GetThreadGroupAffinity': identifier not found
1>glaze\thread\threadpool.hpp(39,16): error C3861: 'SetThreadGroupAffinity': identifier not found
1>glaze\thread\threadpool.hpp(55,28): error C3861: 'GetActiveProcessorGroupCount': identifier not found
1>glaze\thread\threadpool.hpp(58,20): error C3861: 'GetMaximumProcessorCount': identifier not found
```
what could possibly a normal user just wanting to read/write json want with a threadpool for running some internal study ?
especially since including this file requires an (annoying) windows.h include before it (manually, from the user's side)

**Comment by stephenberry** [comment]
This is a very valid point. All that group affinity stuff was added for our customer when first developing the library and is actually not necessary on windows 11. The study code is associated with JSON and therefore currently included in the header, it allows the user to run studies based on a JSON input file using the same meta data. We could make this an optional include, but if we also make it lighter weight by removing windows.h, it shouldn't be so much of an issue.

@mwalcott3, do you think we can get rid of the group affinity stuff now? Or, does this need to be within a macro that turns this on when needed?

**Comment by mwalcott3** [comment]
I'd hide the group affinity stuff behind a macro for now if we want to keep it. However, I tend to agree that the study should probably be separated from the rest of the JSON stuff. 

99% percent of people likely have no interest in it. To be honest I think it can be entirely removed from glaze. I can just throw it in with pigeon, I'm planning on bundling it with the optimization code anyways since there is another code base that would find that useful when it moves over to JSON config files.

**Comment by stephenberry** [comment]
I'd rather just use standard C++ and avoid macros, so I'll strip it out and you can transfer it to where you need it.

**Comment by stephenberry** [comment]
Handled in #279

windows.h is no longer included in the threading code and the group affinity stuff is gone.
