### ISSUE TITLE
json/write.hpp does not include core/write.hpp making data_ptr undefined

### ISSUE THREAD

**Issue by rajkosto** [stephenberry/glaze#277]
creates confusing error about missing data_ptr definition when wanting to write to any output type
json/read.hpp works standalone without needing to manually include core/read.hpp separately so this should probably be made symmetrical for write.hpp

**Comment by stephenberry** [comment]
Thanks for pointing this out, will fix.

**Comment by mwalcott3** [comment]
Fixed in #283
