### ISSUE TITLE
running glz::format_error with err==missing_key results in empty string

### ISSUE THREAD

**Issue by rajkosto** [stephenberry/glaze#281]
This is because pe.location is after the valid indices of the source string i give it (converting just one json object with `glz::read<glz::opts{.error_on_unknown_keys=true, .error_on_missing_keys=true}>`), which causes info inside format_error to be null
In this case i think at least the string representation of the ec should be output (or maybe the error pointer should point to the closing } of the object missing the key instead of one after it ?).

**Comment by mwalcott3** [comment]
Thank you, addressed in #283.
