### ISSUE TITLE
[Question] Move meta to `cpp` file 

### ISSUE THREAD

**Issue by RozeFound** [stephenberry/glaze#282]
Sorry it may be a stupid question but I want to clarify.
Why can't I move meta into a separate `cpp` file?

Why is structure like this isn't possible?

```cpp
// user.hpp

struct User {
    std::string name;
    int age;
};

// user.cpp

template <> struct glz::meta<User> {
    using T = User;
    static constexpr auto value = glz::object("name", &T::name,"age", &T::age);
};
```

I know I can `#include` cpp file to import structures and meta, but that's not a common way to write code to say the least

**Comment by mwalcott3** [comment]
The meta is queried compile time so like most constexpr/consteval stuff this requires the compiler to see the actual implementation. If you want to separate the meta from the class Id be more keen to put it in a secondary header file like "user_meta.hpp" or put all your metas in one header file.

Putting it in a cpp file is fine if you just want to use it in that translation unit. You could include the cpp file just like you stated to get around this limitation. Irregular and cpp files often aren't written to  be included (include guards, non inline functions, etc) but if it works for you it works for you.

**Comment by RozeFound** [comment]
Oh, so it must see meta at compile time. And there is no way it can be done at link time?

**Comment by mwalcott3** [comment]
Nope, not to my knowledge. Closest thing I can think of is you can put the metas in a cpp file and then wrap the read_json/write_json calls with a function declared in a header and defined in a cpp file.

**Comment by RozeFound** [comment]
Thanks for clarification, I hope I didn't stole too much of your time 😅
Have a good day!
