### ISSUE TITLE
Numeric enum Support

### ISSUE THREAD

**Issue by katazina0** [stephenberry/glaze#288]
Hello, I was wondering whether numeric enum parsing/serializing is supported with glaze?

for example, this:
```
enum struct MyEnum {
    VALUE_1 = 200,
    VALUE_2 = 300,
    VALUE_3 = 400,
    UNUSED_VALUE = 500
};
std::vector<MyEnum> enums;
```
would get parsed from this JSON:
```{"enums":[200, 300, 400]}```

Not sure if this is already possible using glz::meta<>.

**Comment by stephenberry** [comment]
Currently enums are handled as strings in JSON. However, support for this would not be hard to add.
I'll try to add this soon, thanks for bringing it up.

**Comment by katazina0** [comment]
Thanks for the response, glad to hear that!

As I was testing some more things, I stumbled upon a bug. Fairly sure it's not due to an issue on my end, here it is:

```
  ... "restrictions": [
        ],
        "warnings": [
          ], ...
```

Empty arrays seem to get indented when they shouldn't. Here's the function used:
```glz::write<glz::opts{.skip_null_members=false,.prettify=true,.indentation_width=2}>(object, buffer);```

Sorry if it's not appropriate to post the bug report here.

**Comment by jbbjarnason** [comment]
I think this here: https://github.com/stephenberry/glaze/blob/main/include/glaze/ext/jsonrpc.hpp#L53

Serves similar purpose like you need, convert enum to number. I am not sure if this works while reading from json.

**Comment by mwalcott3** [comment]
> I think this here: https://github.com/stephenberry/glaze/blob/main/include/glaze/ext/jsonrpc.hpp#L53
> 
> Serves similar purpose like you need, convert enum to number. I am not sure if this works while reading from json.

Yeah, something like that would be a good workaround. Reading would not work with to_underlying since it returns a value. 

If you are okay with undefined behavior (breaking strict aliasing specifically) reinterpret_cast should be able to enable read support.
``` c++
static constexpr auto value{[](auto&& enum_value) -> auto& { return *reinterpret_cast<std::underlying_type_t<std::decay_t<decltype(enum_value)>>*>(&enum_value); }};
```

**Comment by cbdj** [comment]
Any update on this feature ?

**Comment by TheooT** [comment]
Adding enum support would be so useful, please make us aware on this feature !

**Comment by stephenberry** [comment]
@cbdj @TheooT 
Support for numeric enums has now been added (#323). Thanks for pinging me to get this done! Let me know if you run into any issues.

See the following unit test as an example:
```c++
enum class my_enum_type
{
   value_0,
   value_1
};

struct test_enum_struct
{
   my_enum_type type = my_enum_type::value_1;
};

template <>
struct glz::meta<test_enum_struct>
{
   using T = test_enum_struct;
   static constexpr auto value = object("type", &T::type);
};

suite numeric_enum_tests = [] {
   "numeric_enum"_test = [] {
      test_enum_struct obj{};
      std::string s{};
      glz::write_json(obj, s);
      expect(s == R"({"type":1})");
      
      obj.type = my_enum_type::value_0;
      expect(!glz::read_json(obj, s));
      expect(obj.type == my_enum_type::value_1);
   };
};
```

**Comment by cbdj** [comment]
Wow ! Thanks for your reactivity ! It works as expected !

**Comment by TheooT** [comment]
Many thanks, good luck for the future of your great product !
