### ISSUE TITLE
remove unused code in jsonrpc

### ISSUE THREAD

**Issue by jbbjarnason** [stephenberry/glaze#292]
FYI, I was skimming through the code and stumbled upon unused code in jsonrpc, what I forgot to remove during the initial PR.

https://github.com/stephenberry/glaze/blob/7d828d2b9e2020d1ed4b6e45be6685b892167cdb/include/glaze/ext/jsonrpc.hpp#LL503C35-L503C49

**Comment by stephenberry** [comment]
Removed in #343
