### ISSUE TITLE
gcc-13 build failure

### ISSUE THREAD

**Issue by justend29** [stephenberry/glaze#295]
## Error
Glaze fails to build with GCC13. Here is the error output: [gcc13_build_failure.txt](https://github.com/stephenberry/glaze/files/11464796/gcc13_build_failure.txt).

Upon reading the [porting to GCC13 guide](https://gcc.gnu.org/gcc-13/porting_to.html), glaze's build failure seems to be a consequence of the move semantics changes described there.

I will come to attempt to better understand what the issue is, but without a strong understanding of glaze's implementation, I can only assume others will much better understand what's going on.

## Reproduction

Just a standard build w/ CMake, but for completeness, here's exactly what I did:
```bash
cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -Dglaze_DEVELOPER_MODE=ON -DCMAKE_COLOR_DIAGNOSTICS=ON
cmake --build build
```

Additinally, since gcc-13 was just released and may not be available on many systems, I've attached a [Dockerfile.txt](https://github.com/stephenberry/glaze/files/11465334/Dockerfile.txt)
  to construct a build environment for glaze with gcc-13. Its `.txt` extension is so GitHub allowed me to upload it. It can be used as such:

```bash
# build docker image
docker build -t gcc13:glaze -f Dockerfile.txt .

# build glaze in container from local sources & local build directory
docker run --rm -t --name build-glaze -v /local/path/to/glaze:/root/glaze gcc13:glaze
```

**Comment by stephenberry** [comment]
I don't have docker currently set up, would it be straightforward for you to test the current version of Glaze again with gcc-13? I think the issues may not be resolved since the compiler errors look the same as the MinGW ones.

I'm hoping GitHub actions will soon support gcc-13

**Comment by justend29** [comment]
No problem at all.

Builds like a charm! Testing both with G++ 13.0.1 (shown below) through my above Dockerfile, and with G++13.1.1 on my local machine. 
```txt
-- The CXX compiler identification is GNU 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-13 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FetchContent.cmake:1279 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  tests/CMakeLists.txt:6 (FetchContent_Declare)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Fetching dependencies...
-- ...finished fetching dependencies.
-- The C compiler identification is GNU 13.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-13 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/glaze/build-gcc13
[0/2] Re-checking globbed directories...
[18/18] Linking CXX executable tests/json_test/json_test
```

Also, I believe that GitHub Actions supports running jobs in a docker container if that's an accepted alternative for GH actions w/ GCC13. I can always handle that at some point in the future, if the support is there.

**Comment by stephenberry** [comment]
Thanks for testing! Glad it's working. My guess is we should catch gcc-13 build errors by testing with MinGW, so we probably don't need more actions right now. But, if you wanted to setup a gcc-13 Github action using a docker container I would gladly accept it. Though, it probably won't be too long until we can just add gcc-13 to our current approach.
