### ISSUE TITLE
Custom serialization for base class

### ISSUE THREAD

**Issue by RozeFound** [stephenberry/glaze#296]
I have two classes called vec2_t and vec3_t, they both derive from vec_t. 

#### Is there a way to implement serialization to base class only, instead of duplicating code?
Simple "no" will be okay.

It's not a major issue, since you can simply move actual serialization to a function, but still.

```cpp
constexpr void str_to_vec (vec_t<double>& vec, std::string_view string) {
    for (std::size_t i = 0, last_id = 0; i < vec.size(); i++) {
        auto delimiter_position = string.find(' ', last_id+1);
        auto str = string.substr(last_id, delimiter_position);
        vec.at(i) = std::stod(str.data());
        last_id = delimiter_position;
    }
}

namespace glz::detail {
    template <> struct from_json<vec2_t> {
    template <auto Opts> static void op (vec2_t& vec, auto&&... args) {
        std::string_view string = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"; 
        read<json>::op<Opts>(string, args...);
        str_to_vec(vec, string);
      }
   };
    template <> struct from_json<vec3_t> {
    template <auto Opts> static void op (vec3_t& vec, auto&&... args) {
        std::string_view string = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"; 
        read<json>::op<Opts>(string, args...);
        str_to_vec(vec, string);
      }
   };
}
```

**Comment by RozeFound** [comment]
I totally forgot about concepts... Sorry to bother you with such nooby questions, I'll try to not do it again

**Comment by stephenberry** [comment]
No problem, concepts are wonderful!

**Comment by RozeFound** [comment]
Looks like you changed something, and now it gives me "ambiguous partial specialization of `from_json<vec3_t>`
I checked documentation for custom serialization, but there was no changes. What could've caused it?

**Comment by RozeFound** [comment]
The code in question: 
```cpp
template <class T> requires std::derived_from<T, vec_t> 
struct from_json <T> {

    template <auto Opts>
    static void op (T& vec, auto&&... args) noexcept {

        char _cbuf[64]; 
        std::string_view buffer(_cbuf); 
        read<json>::op<Opts>(buffer, args...);

        for (int position = 0; auto& value : vec) {
            auto str = buffer.substr(position);
            position = buffer.find(' ', position) + 1;
            std::from_chars(str.begin(), str.end(), value);
        }
    }
};
```
And it conflicts with https://github.com/stephenberry/glaze/blob/main/include/glaze/json/read.hpp#L877-L972

**Comment by stephenberry** [comment]
There was a recent change to use erase rather than resize for vector like containers. Does your container have resize but not erase?

I can make it fallback to call resize if there is no erase method for the container. Erase is generally better because it doesn't require the type to be default constructible, which is why the change was made.

**Comment by RozeFound** [comment]
It doesn't have erase nor resize ¯\\_(ツ)\_/¯
It's not a vector-like container, it's a vector like in math

**Comment by stephenberry** [comment]
Gotcha, makes sense. I'll dig into it and add some unit tests. I think I may have caused an issue with an erasable concept being added. For now, just use the latest release until this is fixed. But, let me know if you have this issue with the latest release.

**Comment by RozeFound** [comment]
Well, that's the issue with the **latest release**, I just updated from 1.2.2 to 1.4.0 and this issue arose.

**Comment by stephenberry** [comment]
Oh, interesting. If you end up figuring out what release broke it, let me know. Otherwise, I'll set up some tests and work through it.

**Comment by RozeFound** [comment]
Looks like last version this issue isn't happening is 1.2.6, so 1.3.0 and everything after it producing the same issue

**Comment by RozeFound** [comment]
Maybe the fact my 2-3 value vectors have iterators with the only purpose of easier serialization, make em look like vector-like objects?

**Comment by stephenberry** [comment]
Yeah, that was the release where we moved to using more range concepts, so I think it has to do with some of those concepts being used.

**Comment by RozeFound** [comment]
So what can we do about this?

**Comment by stephenberry** [comment]
It should totally be fixable, I'm looking over the diff between the versions right now, but nothing is popping out to me yet.

**Comment by stephenberry** [comment]
In release 1.3.0 concept `array_t` changed, specifically the `range` concept it uses changed from:
```c++
 template <class T>
   concept range = requires(T& t) {
                      typename T::value_type;
                      requires !std::same_as<void, decltype(t.begin())>;
                      requires !std::same_as<void, decltype(t.end())>;
                   };
``` 
to:
```c++
template <class T>
   concept range = requires(T& t) {
                      requires !std::same_as<void, decltype(t.begin())>;
                      requires !std::same_as<void, decltype(t.end())>;
                      requires std::input_iterator<decltype(t.begin())>;
                   };
```

Is there anything suspicious about this change???

**Comment by stephenberry** [comment]
Could you try swapping out this concept and see if it fixes the problem?

**Comment by RozeFound** [comment]
Where is it

**Comment by stephenberry** [comment]
In `glaze/core/common.hpp`

**Comment by RozeFound** [comment]
Yep, fixed
Looks like removing `typename T::value_type;` causing the issue

**Comment by RozeFound** [comment]
Not sure how to fix it in the lib tho
it's fine for range to not have `typename value_type`.
Maybe for `array_t` concept check for `data()` method?

**Comment by RozeFound** [comment]
The class your concepts consider as array:
```cpp
struct vec_t {

    constexpr virtual double& operator[] (const std::ptrdiff_t index) = 0;
    constexpr const double& operator[] (const std::ptrdiff_t index) const { return operator[](index); }

    constexpr double& at (const std::ptrdiff_t index) { return operator[](index); }
    constexpr const double& at (const std::ptrdiff_t index) const { return operator[](index); }

    constexpr virtual std::string string() const = 0;
    constexpr virtual std::size_t size() const noexcept = 0;

    constexpr double* begin() noexcept { return (double*)this + 1; };
    constexpr double* end() noexcept { return (double*)this+size() + 1; };

};
```

**Comment by stephenberry** [comment]
I just merged in #416, which lets you add a flag to your class to fix the partial specialization ambiguity.
I've documented it at the end of [custom-serialization.md](https://github.com/stephenberry/glaze/blob/main/docs/custom-serialization.md), but you just need to update your class to look like:

```c++
struct vec_t {
    static constexpr auto glz_custom_read = true; // Add this to your class
    
    constexpr virtual std::string string() const = 0;
    constexpr virtual std::size_t size() const noexcept = 0;

    constexpr double* begin() noexcept { return (double*)this + 1; };
    constexpr double* end() noexcept { return (double*)this+size() + 1; };

};
```

That will cause the glaze reading concepts to fail and use your custom parsing instead.

**Comment by stephenberry** [comment]
Ah, you've helped me think of a better idea. I'll get back to you soon.

**Comment by stephenberry** [comment]
I just pushed a hot fix that moves this logic into the `glz::meta` object. This way you can specify that you want custom reading outside of your class. In your case you should just be able to add the following code:

```c++
template <class T> requires std::derived_from<T, vec_t>
struct glz::meta<T>
{
   static constexpr auto custom_read = true;
};
```

Now, you no longer need to modify your class.

**Comment by RozeFound** [comment]
That looks better, and what's more important it works, but it's still weird that you need additional variables when you already have custom serialization
It would be much more straightforward if it just preferred user implementation over internal

**Comment by stephenberry** [comment]
Yeah, it's a limitation in the language for partial template specialization. If you fully specified the template it would prefer yours, but then you wouldn't be able to use `std::derived_from` and you'd have to have more code.

**Comment by RozeFound** [comment]
Well anyway it's a good compromise. I surprised that you resolved the issue that fast

**Comment by stephenberry** [comment]
This one wasn't too bad and it's a good general improvement to add.
