### ISSUE TITLE
Reading a csv with std::strings

### ISSUE THREAD

**Issue by klemenpeganc** [stephenberry/glaze#324]
Hi!
I have a following csv structure to read:
```
id,udl
1,BRN
2,STR
3,ASD
4,USN
```
For this, I have created a struct and the glaze bindings:
```
struct my_struct
{
    std::vector<int> id{};
    std::vector<std::string> udl{};
};

template <> struct glz::meta<my_struct>
{
    using T                     = my_struct;
    static constexpr auto value = glz::object("id",
                                              &T::id,
                                              "udl",
                                              &T::udl);
};
```

When I call: 
```
my_struct my_str;

if (auto ec = glz::read_file_csv<glz::colwise>(my_str, filePath))
{
    LOG4CXX_ERROR(logger_,
                  "Reading of csv file [" << filePath << "] failed with error code [" << ec << "] at location [" << ec.location
                                              << "].");
    return;
}
```
I get a lot of compilation issues regarding the std::string... If I have a structure without std::string, then it works as expected. Any tips on how to read the strings from the CSV?

**Comment by stephenberry** [comment]
Yeah, right now `CSV` is somewhat restricted and doesn't currently support strings. One question is whether strings should be expected to be quoted, but I think the default should expect them not to be quoted.

Will add this hopefully soon.

**Comment by stephenberry** [comment]
@klemenpeganc Support for reading std::string has been added (#325). Let me know if you run into any other problems with CSV handling, it isn't being used and tested as much as the JSON side, but I have plans to add more features to it.
