### ISSUE TITLE
Unset char as key cut off the json output

### ISSUE THREAD

**Issue by maor-da** [stephenberry/glaze#335]
The "pretty" JSON is cut off when using `char`.

```c++
struct test{
  int a;
  char c;
  std::string str;
}
```
```c++
test obj{};
std::string buffer{};
glz::write<glz::opts{.prettify = true}>(obj, buffer);

printf("%s", buffer.c_str());
```

result:
```json
{
   "a": 0,
   "c": "
```

when expecting:
```json
{
   "a": 0,
   "c": "", // since json has only string
   "str": ""
}
```

Another issue is with `char*`, it causes to dereference null in the code.
I can PR if you want.

**Comment by stephenberry** [comment]
Thanks for bringing this up. If you're able to submit a PR with a fix that would be great!

**Comment by stephenberry** [comment]
This should all be working now.
