### ISSUE TITLE
Error to deserialize empty std::set

### ISSUE THREAD

**Issue by sweihub** [stephenberry/glaze#345]
Hi

Glaze failed to deserialize the empty set, if the array with values, it works, the code to reproduce
```cpp
#include <set>
#include <glaze/glaze.hpp>

struct GetTest {
    uint32_t id;
    std::string method;
    std::set<uint32_t> params;
};

GLZ_META(GetTest, id, method, params);

int main(int argc, const char *argv[])
{
    auto s = R"(
        {"id": 1, "method": "get_session", "params": []}
    )";

    GetTest get{};
    if (glz::read_json(get, s)) {
        std::cout << "ERROR" << std::endl;
    }
    else {
        std::cout << "OK" << std::endl;
    }

    return 0;
}
```

**Comment by stephenberry** [comment]
@sweihub 
I implemented your test case and did not get an error. Maybe test with the `main` branch of glaze and see if the issue still exists. There already exists a unit test for reading in an empty set.

**Comment by stephenberry** [comment]
I'm closing this, because it doesn't seem to be an error anymore, but certainly comment or make a new issue if this shows up again.
