### ISSUE TITLE
unable to use type std::unordered_set<std::string> within glaze template

### ISSUE THREAD

**Issue by narknon** [stephenberry/glaze#360]
The compiler does not appear to be able to implicitly convert std::string when used within an unordered set within the glaze template.  It works fine within vectors.

**Comment by stephenberry** [comment]
Can you provide an example that produces your issue? There currently exists a unit test for `std::unordered_set<std::string>` shown below, which passes:

```c++
"std::unordered_set"_test = [] {
    std::unordered_set<std::string> set;
    expect(glz::read_json(set, "[]") == glz::error_code::none);
    expect(set.empty());
    
    set = {"hello", "world"};
    std::string b{};
    glz::write_json(set, b);
    
    expect(b == R"(["hello","world"])" || b == R"(["world","hello"])");
    
    set.clear();
    
    expect(glz::read_json(set, b) == glz::error_code::none);
    
    expect(set.count("hello") == 1);
    expect(set.count("world") == 1);
};
```

**Comment by narknon** [comment]
Sure, sorry for not including it original, was late and I was trying to get this working for a while.  We use a macro for strings to allow easy conversions when dealing with a separate system (the File::StringType), but that is literally just "using StringType = std::string;".  I also tried it with std::unordered_set\<std::string\> directly, and even with changing the name meta in string.hpp in glaze source.
Other array types work within the UVTDSettings struct.
The compiler output is attached below.


(Namespaced RC::UVTD)
```
class SettingsManager
    {
    public:
        
            struct UVTDSettings
            {
                std::unordered_set<File::StringType> ValidUDTNames = valid_udt_names;
            };
           
    static void read_settings();
    };
```

(Outside Namespace)

```
template <>
struct glz::meta<RC::UVTD::SettingsManager::UVTDSettings>
{
        using T = RC::UVTD::SettingsManager::UVTDSettings;
        static constexpr auto value = object(
                                             "ValidUDTNames", &T::ValidUDTNames
                                             );
};
```


[message(4).txt](https://github.com/stephenberry/glaze/files/12130486/message.4.txt)

**Comment by stephenberry** [comment]
It looks like your error has to do with using the binary format. Which, I've been able to replicate an error using.

**Comment by narknon** [comment]
Thank you, but could you clarify where I'm using the binary format?

**Comment by stephenberry** [comment]
Your attached message.txt errors have to do with `glz::detail::from_binary`. Are you calling `write_binary` or `read_binary`?

**Comment by narknon** [comment]
No, everything I'm calling is in that code snippet.

**Comment by narknon** [comment]
Does read_file call to read_binary?

**Comment by stephenberry** [comment]
`read_file` looks at the extension, if your extension is `.json` it should read as JSON. You can call `read_file_json` explicitly as well.

**Comment by narknon** [comment]
read_file_json seems to allow it to compile.  Not sure why it wasn't picking up the .json (was the extension not supposed to be explicit as well?

Thanks for the help.

**Comment by stephenberry** [comment]
read_file expects the extension to be in the name. Note sure why it wasn't picking it up. I'm closing issue, but new ones can be added for binary set handling (if needed) or file reading if there is an issue there.
