### ISSUE TITLE
Add error_on_unknown_keys = false option to binary (add skip_binary)

### ISSUE THREAD

**Issue by toge** [stephenberry/glaze#376]
I am trying to adopt crusher as my internal data format to speed up read/write.
Since some programs use only few fields, I would be happy if I could read only the minimum number of fields, like `read_json` with `error_on_unknown_keys=false`.

Are there any plans to add opts to `read_binary`?

**Comment by stephenberry** [comment]
`read_binary` actually doesn't error with unknown keys, it just reads in the minimum as you want. In the future I do want to add `error_on_unknown_keys = true` as an option for binary reading, but currently it should behave as you want.

**Comment by stephenberry** [comment]
Oops, my initial reply was wrong (thus deleted). Yes, `error_on_unknown_keys=false` should be added. I'll this issue alive, because it definitely a good feature.

**Comment by stephenberry** [comment]
@toge, #428 has just been merged, which adds skipping to the binary format. So, now you should be able to use `error_on_unknown_keys = false` or use `glz::skip`. This still needs more robust testing, but the code is now there.

**Comment by toge** [comment]
@stephenberry 
Thanks!
I'm trying it.

**Comment by stephenberry** [comment]
That's great to hear! We'll be continuing to add more binary support to match what is possible with JSON and vice versa.
