### ISSUE TITLE
integer overflow in stoui64.hpp row 68

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#380]
The following test:
```cpp
   "integer overflow in stoui64.hpp:68"_test = [] {
      std::string buffer{R"({"arr":[e5555511116]})"};
      my_struct value{};
      glz::context ctx{};
      [[maybe_unused]] const auto ec = glz::read<glz::opts{.force_conformance = false}>(value, buffer, ctx);
   };
```
causes an integer overflow in https://github.com/stephenberry/glaze/blob/d7bb0069053ba2b77b3e5bcec48cc6109331316b/include/glaze/util/stoui64.hpp#L68

This is the error message:
> /home/paul/code/glaze/include/glaze/util/stoui64.hpp:68:22: runtime error: signed integer overflow: 10 * 555551111 cannot be represented in type 'int'

**Comment by stephenberry** [comment]
Test added and fixed in #379
