### ISSUE TITLE
glz::schema thoughts

### ISSUE THREAD

**Issue by jbbjarnason** [stephenberry/glaze#405]
The two `std::vector` https://github.com/stephenberry/glaze/blob/83d1cb0e924d1adeb6c9a18d04ca0b7fe95e44f4/include/glaze/json/schema.hpp#L21 members make the struct require global constructor and exit time destructor, since the `std::vector` is allocating its memory of the heap. 

Would it make sense to change to `std::array` or do you have any other ideas?

**Comment by stephenberry** [comment]
I think it would be best to change these members to use `std::span`. This way the user could compile time allocate the proper sized `std::array` to construct the `schema` (meaning initialize the spans with arrays). We could template the schema with the sizes of these member arrays, but that makes the interface more clunky. Using a `std::span` will let us keep the size of the `schema` constant so it doesn't need to be templated while allowing these members to be various sizes.

Thoughts?

**Comment by jbbjarnason** [comment]
I tried using std::span briefly on friday but was not successful, I will need to try it a bit more.

**Comment by stephenberry** [comment]
Issue fixed with #460
