### ISSUE TITLE
Handle "encoded" members.

### ISSUE THREAD

**Issue by justend29** [stephenberry/glaze#448]
## Premise

Various sources of JSON data, particularly databases, will encode JSON in JSON strings. This therefore requires two levels of parsing:
1. Parsing the received JSON into a struct
2. Parsing members that are encoded as JSON in strings into data structures

For example, to achieve semi-structured schemas in Postgres, the following table could be created:
```sql
CREATE TABLE Client_state
(
  id INTEGER PRIMARY KEY,
  # ...
  layouts JSONB
);
```

This will result in the JSON contents of `layouts` being treated as a JSON encoded string. Something possibly as follows (with some spacing so we don't go crazy):
```json
{
  "id": 4848,
  "layouts": "{\"first layout\": [ \"inner1\", \"inner2\" ] }"
}
```

As expected, the serialized JSON "doubly" encodes the value of `layouts` - with more spacing here:
```
{
  \"id\": 4848,
  \"layouts\": \"{\\"first layout\\": [ \\"inner1\\", \\"inner2\\" ] }"
}
```

I currently experience this problem reading data from Postgres. My current solution is to have two structs: 1. one with the direct response format, where the encoded members are strings, and 2. another with all the encoded members expanded.
This second struct has a custom `from_json` specialization, which first parses the JSON into the response struct, then parses the encoded string members of that struct, and finally moves all the parsing results to the top-level parse result.

## Addition

It would be splendid to offer the ability to "doubly" encode and decode members directly in glaze's `meta` struct. This would not only relieve the need to decode into two separate structs with custom `from_json`, but would likely massively increase the performance of reading & writing data structures with this format. This performance increase would come from the fact that I believe that glaze wouldn't have to internally perform the double encoding/decoding I'm doing above, but could instead handle "double escaped", as it [currently does](https://github.com/stephenberry/glaze/blob/main/include/glaze/json/read.hpp#L388) for normal escaped characters:

```c++
auto handle_escaped = [&]() {
                  switch (*it) {
                  case '"':
                  case '\\':
                  case '/':
                     value.push_back(*it);
                     ++it;
                     break;
                  case 'b':
                     value.push_back('\b');
                     ++it;
                     break;
                  case 'f':
                     value.push_back('\f');
                     ++it;
                     break;
                  case 'n':
                     value.push_back('\n');
                     ++it;
                     break;
...
```

### Suggestion

For my contrived example with Postgres above, an additional sensitivity within meta may look as follows. Some consideration for doubly encoding/decoding on only one of read/write may be worthwhile (`glz::encode_read` & `glz::encode_write` maybe?).

```c++

struct Client_state {
  std::size_t id{};
  // ...
  std::map<std::string, std::vector<std::string>> layouts{};
};

template <>
struct glz::meta<Client_state> {
  using T = Client_state;
  static constexpr auto value = glz::object("id", &T::id, /* ... */ "layouts", glz::encoded{&T::layouts} );
};
```

Thoughts?

**Comment by stephenberry** [comment]
I think your reasoning is well thought out and your suggestion excellent. I'll try to add this support soon.

**Comment by stephenberry** [comment]
@justend29 I just merged in #449, which adds a `glz::unquote` wrapper with the behavior you're looking for.
This version uses a `static thread_local std::string` to do the double parsing. So, this isn't as efficient as it could be, but it is way less code. But, it will reuse this buffer, so it should be fairly efficient. In the future we can improve these functions to be more efficient, but I'm going to have to carefully think about whether this should result in `if constexpr` checks across the entire codebase and if we should add a boolean to the context to know if we are within the initial quotes. I don't think it is currently worth writing this optimization. But, I figured I'd add the wrapper so that it is easier to deal with as a user.

Here is an example unit test:
```c++
template <>
struct glz::meta<client_state> {
   using T = client_state;
   static constexpr auto value = object("id", &T::id, "layouts", unquote<&T::layouts>);
};

suite unquote_test = [] {
   "unquote"_test = [] {
      client_state obj{};
      std::string s = R"({
  "id": 4848,
  "layouts": "{\"first layout\": [ \"inner1\", \"inner2\" ] }"
})";
      expect(!glz::read_json(obj, s));
      expect(obj.id == 4848);
      expect(obj.layouts.at("first layout") == std::vector<std::string>{"inner1", "inner2"});
      
      std::string out{};
      glz::write_json(obj, out);
      expect(out == R"({"id":4848,"layouts":"{\"first layout\":[\"inner1\",\"inner2\"]}"})");
   };
};
```

If you have additional thoughts, let me know. Or if I should call it something other than `unquote`

**Comment by justend29** [comment]
@stephenberry That's great from a user perspective. Thank you! It's probably fine for now to do the double parsing, as you say.

As for the name, seeing as there exists a `quoted` modifier which does something different than this `unquote`, it does kind of conflate the two processes. This addition would unescape all escape codes when parsing, not exclusively quotes, and it applies to more than just numbers, which is all `quoted` applies to.

With that, a modifier name such as `escaped` (adjective), `unescape` (verb), `encoded`(adjective), or `decode` (verb) or something to delineate these two may be worthwhile. It's ultimately up to you.

**Comment by stephenberry** [comment]
I've updated the name for numbers to `quoted_num` and `unquote` to `quoted`. So, I think the naming is better now.
