### ISSUE TITLE
Missing exception wrappers for newline delimited JSON

### ISSUE THREAD

**Issue by Haatschii** [stephenberry/glaze#488]
As far as I can see there are no exception wrapper functions in `glz::ex` for the NDJSON functions. Is there a specific reason for this, or was there just no demand? In the latter case I could write a pull request adding these functions if you like?

**Comment by stephenberry** [comment]
It's just demand. I intend to expand the exception API, it just isn't used by as many people. Feel free to submit a pull request, that would be great!
