### ISSUE TITLE
wstring support for keys (unordered_map)

### ISSUE THREAD

**Issue by UE4SS** [stephenberry/glaze#515]
Is there support for using `std::wstring` for keys in associative containers like `std::unordered_map` ?
Take the type `std::unordered_map<std::wstring, std::wstring>` for example.
I could cheat by doing a lossy string conversion:
```c++
std::wstring to_wstring(const std::string& input)
{
    // Code to convert wstring to string here.
}

std::string to_string(const std::wstring& input)
{
    // Code to convert string to wstring here.
}

namespace glz::detail
{
    template <>
    struct from_json<std::wstring>
    {
        template <auto Opts>
        static void op(std::wstring& output, auto&&... args)
        {
            std::string str{};
            read<json>::op<Opts>(str, args...);
            output = to_wstring(str);
        }
    };

    template <>
    struct to_json<std::wstring>
    {
        template <auto Opts>
        static void op(const std::wstring& input, auto&&... args)
        {
            const auto str = to_string(input);
            write<json>::op<Opts>(str, args...);
        }
    };
}
```
But this code produces an extra pair of quotes for the key to the unordered_map:
```json
{
   "my_unordered_map": {
      ""MyKey"": "MyValue",
   }
}
```
If there is no such support, how would I go about supporting it myself ? Because clearly the `from_json`/`to_json` functions aren't working very well in this case.

**Comment by stephenberry** [comment]
std::wstring is not supported. The JSON specification requires UTF-8.

**Comment by justend29** [comment]
@stephenberry Having that as a `static_assert` or concept may be worthwhile to reject `wstring` instead of generating invalid JSON with duplicate quotes.
