### ISSUE TITLE
Serialization differs (and silently fails) depending on optimization

### ISSUE THREAD

**Issue by Haatschii** [stephenberry/glaze#520]
Consider the following minimal example:
```c++
#include <iostream>
#include <glaze/glaze.hpp>
#include <glaze/core/macros.hpp>
#include <glaze/exceptions/json_exceptions.hpp>

struct Foo {
	int64_t id = std::numeric_limits<int64_t>::min();
	std::string name = "Whatever";
	
	GLZ_LOCAL_META(Foo, id, name);
};

int main() {
	Foo test{};
	std::cout << glz::ex::write_json(test) << std::endl;
	return 0;
}
```
The expected output is of course `{"id":-9223372036854775808,"name":"Whatever"}` and compiling with `-std=c++20 -O1` the program indeed gives this result. However increasing the optimization to `-O2` the output changes to `{"id":-0,"name":"Whatever"}`, which is obviously different and wrong. For this example I used not further compiler flags other than the include directory with `g++ (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)`. While this setup always reproduces the bug on my system do note that with other compiler flags or slightly different the code the bug might not appear. E.g. without the string variable in `Foo` the serialization is correct independent of optimization level.

I think this is a rather grave bug, as it is nondeterministic (at least at compilation level) and silently produces a wrong result which is conforming JSON nevertheless. I had not time to try to track it down yet, but the fact that the appearance of the bug depends on the optimization level and exact code suggests undefined behavior somewhere in glaze.

**Comment by stephenberry** [comment]
It was that nasty issue of not being able to negate the minimum value of a signed integer to get the absolute value. This was fixed with #523.

Thanks for catching this!
