### ISSUE TITLE
Add utf8 encoded json tests.

### ISSUE THREAD

**Issue by mwalcott3** [stephenberry/glaze#56]
Right now everything is 100% ascii in the tests. Im not aware of anything glaze is doing that would break utf8 but wouldn't be surprised if there was any issues on this front.

**Comment by mwalcott3** [comment]
On this topic, we need to add a test for unescaped unicode in meta object keys and reading in escaped unicode in the json to test that it prevents escape skipping in the object.

**Comment by stephenberry** [comment]
Added unicode tests
