### ISSUE TITLE
Reflection limitations documentation

### ISSUE THREAD

**Issue by dbraeckelmann** [stephenberry/glaze#618]
Hi, first of all: very nice that this library integrated the newly discovered reflection tricks using source_location, highly appreciated!

It would be really nice, if the limitations could be explictely documented right in the README. We tried using the library with a structure of more than 40 fields (for an external REST API we don't have control over) and it did not work because of the current 28 field limitation. At least the usage of Concepts made it immediately clear what was wrong, but would be even nicer to have this mentioned in the documentation (also the enum field limits, 100 currently if I remember correctly from the reddit thread?).

Cheers and keep on the great work!

**Comment by stephenberry** [comment]
Thanks for the feedback! My plan is to add support for up to 128 members today.

**Comment by stephenberry** [comment]
@dbraeckelmann, support has been added for up to 128 fields (merged #620)! Let me know if you run into any issues with this.
