### ISSUE TITLE
Fails with -DFETCHCONTENT_FULLY_DISCONNECTED=ON

### ISSUE THREAD

**Issue by yurivict** [stephenberry/glaze#619]
cmake fails:
```
CMake Error at tests/CMakeLists.txt:24 (target_link_libraries):
  The link interface of target "glz_test_common" contains:

    Boost::ut

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at tests/CMakeLists.txt:64 (target_link_libraries):
  The link interface of target "glz_test_exceptions" contains:

    Boost::ut

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Package builders don't allow builds to fetch anything for security reasons.
All fetches should be done before the build.
One way to do this is to use Git submodules.

cmake args:
-DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -GNinja

-----------------------

While we can't have FetchContent_Declare in cmake files, this FetchContent_Declare is particularly insecure since it doesn't check the cryptographic hash. Man-in-the-middle attacks can easily cause user systems' compromised and hacked.

**Comment by stephenberry** [comment]
Boost::ut is only used for unit tests, and shouldn't be included unless the developer mode is on. If you're running the CMake at top level it will assume developer mode.

I don't think it makes sense as a sub module because Boost::ut is not an actual dependency.

Thanks for pointing this out, and feel free to offer more insight into how to fix this or submit a pull request.

**Comment by yurivict** [comment]
The FreeBSD port builds, but tests fail to run because of this problem.

**Comment by stephenberry** [comment]
Gotcha. What would be a good solution without submodules? I ask this also because a lot of the projects I work on can't use submodules.

**Comment by justend29** [comment]
`FETCHCONTENT_FULLY_DISCONNECTED` does not mean "try to first find the package locally", it means "assume the results of fetching have already been populated." Attempting to run tests with this build-option enabled will not work unless pre-population has been done.

If you would like to build the unit tests without acquiring the test dependencies through FetchContent, the integration between `find_package` and `FetchContent` [introduced in CMake 3.24](https://cmake.org/cmake/help/latest/module/FetchContent.html#integrating-with-find-package) allows calls to `FetchContent` to be redirected to `find_package` with top-level flags. This means you will have to provide the dependencies yourself, possibly as system packages, and this can be done without changes to glaze (assuming the correct package name is currently being used).

In any case, [dependency providers](https://cmake.org/cmake/help/latest/command/cmake_language.html#dependency-providers) can be used to fulfill these dependency requirements in any esoteric manner you'd like. 

Git submodules are fine if you have a few dependencies without any transitive dependencies, but do not scale well and do not consider transitive dependencies well. Although glaze's dependency requirements are currently small, there are too many great alternatives with features like those mentioned above to every consider git submodules.

**Comment by yurivict** [comment]
> Are you creating a FreeBSD port for glaze? What's the use-case?

I already did.
The use case is when some other package would use glaze - the glaze port would be available.

---------------

About ut:
You could first run ```find_package(UT)``` and then only fetch when ```UT_FOUND``` would be equal to FALSE.

**Comment by justend29** [comment]
Okay, so you've created a dev package for BSD. The unit tests are needed for this?

That behavior to first try `find_package` is already available with a top-level flag, `FETCHCONTENT_TRY_FIND_PACKAGE_MODE`, as is described in the first link above. A call to `find_package` does not need to be explicitly added, as the integration between `find_package` and `FetchContent` from CMake 3.24 already handles this.

This or a dependency-provider will allow you to acquire UT any way you'd like - including as a pre-built binary or in a build from source.
Does this solve your issue? is there something more I could provide that would help you better?

**Comment by stephenberry** [comment]
It seems like this is not actually an issue. If a way to improve our CMake setup is proposed we'll consider it, but for now I think we're good.

Also, how would the `URL_HASH` work for FetchContent_Declare when we are just using the zipped file path?
