### ISSUE TITLE
How do you read [] JSON with your lib

### ISSUE THREAD

**Issue by rivaros** [stephenberry/glaze#636]
```json
[{
   "i": 287,
   "d": 3.14,
   "hello": "Hello World",
   "arr": [
      1,
      2,
      3
   ],
   "map": {
      "one": 1,
      "two": 2
   }
}]
```
@stephenberry hello! would your lib be able to read_json the above?

**Comment by stephenberry** [comment]
Certainly, just read into a `std::vector<my_struct>` or a similar array-like type.

**Comment by rivaros** [comment]
Thanks for the hint! So we don't need to have any array initialized in front, as number of elements in JSON array can vary. We only know the struct of each element.

**Comment by stephenberry** [comment]
You're welcome! A std::vector will handle any number of elements.

If you have an array of mixed objects then use a std::tuple or a std::vector of std::variant of your types.
