### ISSUE TITLE
Glaze will not link under arm 32 bit gcc.

### ISSUE THREAD

**Issue by tdsr-llc** [stephenberry/glaze#647]
When glaze is compiled for 32 bit arm the function mulhi64 in strod.hpp gets instantiated  in each object.
It looks like the function needs either static or inline to avoid this issue. 
To be honest I do not know if Glaze is intended to support cross-compiling to a 32 bit arm with gcc. 
Maybe if Glaze is not intended for 32 arm a note would be needed some where.

I think Glaze is great and I have used on x86 and Glaze has worked well there.  I am moving code from x86 to an arm platform and found the issue.

**Comment by stephenberry** [comment]
Glad you're enjoying Glaze! I have used glaze a lot on 64 bit arm, but you're the first in my knowledge to try on 32 bit arm. If you find a work around, please include a pull request. But, I don't currently have to time to prioritize 32 bit platforms.

I do think adding a note to the documentation would be helpful, so I'll keep this issue alive until then.

**Comment by stephenberry** [comment]
I added a comment to the README about Glaze being developed and tested only on 64bit little-endian platforms. So, I'm closing this issue. But, if you wanted to add support for 32bit Arm, I would welcome a pull request, though I would expect that to be a significant effort.

**Comment by tdsr-llc** [comment]
Thank you for the update.
I have a work around for this issue in a local copy.
But I should see if there are other issues before going forward with a pull
request. I need to get to the point of running the code on arm 32 which
should be soon enough.
