### ISSUE TITLE
`write_json` seems to be broken in release v2.0.0

### ISSUE THREAD

**Issue by kalradivyanshu** [stephenberry/glaze#673]
I was testing https://github.com/stephenberry/glaze/issues/649, while `read_binary_untagged` and `write_binary_untagged` works perfectly, my code started breaking at `write_json`.

I recreated it here: https://github.com/kalradivyanshu/glaze_v2_issue

It is just a class with inner structs all which are defined in: https://github.com/kalradivyanshu/glaze_v2_issue/blob/master/src/struct_details.hh

Then we create an empty class object and call `write_json` on it:

```c++
#include <cstddef>
#include <cstdint>
#include <glaze/glaze.hpp>
#include <iostream>

#include "struct_details.hh"

int main(void) {
    details2::UD u1;

    std::string json = glz::write_json(u1);

    std::cout << json << std::endl;

    return EXIT_SUCCESS;
}

```
This runs as expected in glaze 1.9.9 and fails in glaze 2.0.

steps to recreate:
(requires conan and cmake)
```bash
git clone https://github.com/kalradivyanshu/glaze_v2_issue
cd glaze_v2_issue
./run_example.sh
```
This will run the code with glaze v1.9.9 and will run and give output:
```
[100%] Built target GlazeTest
+ ./GlazeTest
{"id":"","n":"","e":"","aid":"","o":0,"ob":true,"ri":"","v":{},"a":{}}
```
Which is expected

Now switch to glaze v2.0 by switch to branch v2, which just changes the glaze version: https://github.com/kalradivyanshu/glaze_v2_issue/pull/1/files

```bash
git checkout v2
./run_example.sh
```

This fails to build with the following wall of error: https://github.com/kalradivyanshu/glaze_v2_issue/blob/v2/build_fail.log

cmake version: `3.27.8`
conan version: `2.0.16`
using WSL2 (ubuntu 24.04) in windows 11.

Thank you so much for all your work in this library, it helped me delete so much boilerplate.

**Comment by stephenberry** [comment]
I was able to fix this issue in #675. Thanks for the bug report!

**Comment by stephenberry** [comment]
You're welcome. I will push a minor update today.

**Comment by stephenberry** [comment]
Version 2.0.1 has been released
