### ISSUE TITLE
gcc std::declval issues

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#7]
It looks like gcc has some issues with std::declval, which I'm not sure how to get around.
Specifically this line `return std::declval<T>().*mptr_type{};` in member_check in common.hpp. gcc seems to think this std::declval is being evaluated, even when I make the function consteval. Until gcc fixes the bug or I figure out a work around gcc just won't work yet. clang and MSVC should be working fine.

_Originally posted by @stephenberry in https://github.com/stephenberry/glaze/issues/4#issuecomment-1279320423_

**Comment by Igisid** [comment]
I tried to fix the build error. It turned out something like this:
```    
template <class T, class mptr_t>
constexpr decltype(auto)   member_check()
{
    using mptr_type = std::decay_t<mptr_t>;
    if constexpr (std::is_member_pointer_v<mptr_type>) {
        using Type = decltype(std::declval<T>());
        return Type{}.*mptr_type{};
    }
    else if constexpr (std::is_enum_v<std::decay_t<T>>) {
        return std::declval<T>();
    }
    else {  // is a lambda function
         using invoke = std::invoke_result_t<mptr_t, T>;
         return std::decay_t<invoke>{};
    }
}
```
The tests are passing. But when compiling a warning:
warning: returning reference to local temporary object [-Wreturn-stack-address]
I hope this warning can be fixed.

**Comment by stephenberry** [comment]
The problem with this is that it requires `T`, the exposed class, to be default constructible. But, we want to be able to create interfaces to non-default constructible types. This is the reason why we need `std::declval` rather than `T{}`, and a major reason why declval exists.

This...
```c++
using Type = decltype(std::declval<T>());
        return Type{}.*mptr_type{};
```
is the same as
```c++
  return T{}.*mptr_type{};
```

So, while this change currently passes tests, it really isn't a solution. But, thanks for looking into it. We'll keep trying to find a solution.

**Comment by Ahajha** [comment]
I might have a solution that mostly avoids using std::declval altogether, using a bit of template metaprogramming (everyone's favorite (: )
```c++
      template <class, class>
      struct member_check;

      template <class T, class mptr_t>
      requires std::is_member_pointer_v<std::decay_t<mptr_t>>
      struct member_check<T, mptr_t>
      {
         using type = decltype(std::declval<T>().*std::decay_t<mptr_t>{});
      };

      template <class T, class mptr_t>
      requires(!std::is_member_pointer_v<std::decay_t<mptr_t>> &&
               std::is_enum_v<std::decay_t<T>>)
      struct member_check<T, mptr_t>
      {
         using type = T;
      };

      template <class T, class mptr_t>
      requires(!std::is_member_pointer_v<std::decay_t<mptr_t>> &&
               !std::is_enum_v<std::decay_t<T>>)
      struct member_check<T, mptr_t>
      {
         using type = std::invoke_result_t<mptr_t, T>;
      };
```
Then we can replace
```c++
std::decay_t<decltype(member_check<T, std::tuple_element_t<
             1, std::tuple_element_t<I, meta_t<T>>>>())>...>{};
```
with
```c++
std::decay_t<member_check<T, std::tuple_element_t<
             1, std::tuple_element_t<I, meta_t<T>>>>()>...>{};
```
This at least builds, haven't tried tests/benchmarks.

**Comment by stephenberry** [comment]
Nice, this is a great idea. Your use of member_check was almost there. It just needed to be:
```c++
 std::decay_t<typename member_check<T, std::tuple_element_t<
                              1, std::tuple_element_t<I, meta_t<T>>>>::type>...>{};
```

The latest commit has this change, so see if gcc builds now for you. I'm getting some weird linker problem, but if may be with my compiler setup.
3cdddb9f340dca331b026a4cddcedba47fc717b5

**Comment by Ahajha** [comment]
Ah, the `typename` issue, if I recall it *shouldn't* be necessary in C++20 but clang doesn't support that yet (coming in clang 16!) so that's why I didn't catch it.

There are two more issues I'm running into, the first is with code like the following in `json/study.hpp`:
```c++
result.gen() =
                  [this, dist = std::normal_distribution<double>(
                                        mean, std_dev)]() {
                  return dist(this->engine);
               };
```
The compiler complains about no matching function call, yada yada. The fix is to make the lambdas mutable:
```c++
result.gen() =
                  [this, dist = std::normal_distribution<double>(
                                        mean, std_dev)]() mutable {
                  return dist(this->engine);
               };
```
(There are 4 of these in that file)

The second issue I haven't figured out yet is this:
```
[build] /home/alex/Documents/glaze/include/glaze/core/common.hpp:357:10: error: invalid cast from type ‘const char*’ to type ‘Color’
[build]   357 |          To{from};
[build]       |          ^~~~~~~~
```

**Comment by stephenberry** [comment]
Pushed a fix for mutable lambdas (72151c2bb8f3f7ab6023b5eb26741da076ae3767). I'm actually surprised other compilers didn't complain about this.

**Comment by stephenberry** [comment]
That `To{from};` error is strange, because it is coming from a concept, which is supposed to fail in that case.

**Comment by Ahajha** [comment]
Yea, and as far as I can tell it doesn't interact with "Color" at all.

I think I have something, but I'm not 100% sure if it's what you want:
```c++
      template <class From, class To>
      concept non_narrowing_convertable = requires(From from, To to)
      {
         to = from;
      };
```
The reason I changed it to this is because when you use it, you check the concept, and then immediately do the equivalent of `to = from`:
```c++
            if constexpr (std::is_assignable_v<decltype(val),
                                               decltype(value)> &&
                          detail::non_narrowing_convertable<
                             std::decay_t<decltype(value)>,
                             std::decay_t<decltype(val)>>) {
               result = true;
               val = value;
            }
```
There are many compiler warnings produced at this point, but it does at least compile now.

**Comment by stephenberry** [comment]
That change checks if it is assignable, which should compile fine, but isn't as safe as blocking narrowing conversions. But, I'd rather get gcc compiling, so I'm changing the code to:
```c++
      template <class From, class To>
      concept non_narrowing_convertable = requires(From from, To to)
      {
#if __GNUC__
         // TODO: guard gcc against narrowing conversions when fixed
         to = from;
#else
         To{from};
#endif
      };
```

Yeah, I'm slowly working through warnings. A bunch come from the fmt library. But, I'm really glad gcc is building now! Thanks!

**Comment by Ahajha** [comment]
Agreed, at least it's building now!

**Comment by stephenberry** [comment]
Closing this issue. Will kick off another issue to add automatic build/unit testing on pushes.
