### ISSUE TITLE
cmake doesn't look for eigen

### ISSUE THREAD

**Issue by yurivict** [stephenberry/glaze#707]
I had no eigen installed, yet the configure, build and install all succeeded, and only tests broke.

cmake should look for eigen.

**Comment by stephenberry** [comment]
This is intended behavior. CMake will look for Eigen (find_package) or clone it (FetchContent_Declare) when using developer mode (glaze_DEVELOPER_MODE) or running CMake at the top level (triggering the developer mode).

We wouldn't want everyone who included Glaze to need to download Eigen. You'll find that only the `eigen_test` looks for Eigen.

In short, if you want to run tests, just configure the CMake for Glaze as the top level.

Thanks for your concern.

**Comment by justend29** [comment]
@stephenberry a standard for this is to add a cmake component to the project that includes the eigen ext files and publically depends upon eigen. 

```
find_package(glaze CONFIG REQUIRED COMPONENTS eigen3)
target_link_libraries(my_target PRIVATE glaze::eigen3)
```

**Comment by stephenberry** [comment]
@justend29 that's a great approach. However, Eigen doesn't play very nice with CMake and I don't really want to maintain a public CMake configuration for Eigen. I'd prefer to let users install the dependency as they choose.
