### ISSUE TITLE
Escaped Unicode surrogate pair handling

### ISSUE THREAD

**Issue by Clyraz** [stephenberry/glaze#716]
Parsing strings with escaped surrogate pairs fails with error "unicode_escape_conversion_failure".
I don't see any way to fix this using the current design:
```cpp
const char* c;
if (length < size_t(end - it)) [[likely]] {
    c = parse_string<Bytes>(&*start, value.data(), ctx);
}
else [[unlikely]] {
    c = parse_string<1>(&*start, value.data(), ctx);
}
```
Are there any plans to support this feature or should I stick to a user provided converter/wrapper?

**Comment by stephenberry** [comment]
Can you explain a bit more what you mean by `escaped surrogate`? Could you provide a simple example? Thanks.

**Comment by Clyraz** [comment]
Consider the following example:
```cpp
const char* json = R"("\uD83C\uDF40")"; //🍀
std::string val;
auto ec = glz::read_json(val, json); 
```
This fails to parse, could we add a wrapper enabling proper conversion?

**Comment by stephenberry** [comment]
Ah, I hadn't considered how pairs could be used for larger unicode code points. It would be nice to support this. Do you know of a C++ library that supports this or do you have example code for handling pairs of unicode? I do want to generally improve unicode handling in glaze as well.

**Comment by Clyraz** [comment]
Here is some pseudo code:
```cpp
	constexpr std::uint32_t generic_surrogate_mask = 0xF800;
	constexpr std::uint32_t generic_surrogate_value = 0xD800;

	constexpr std::uint32_t surrogate_mask = 0xFC00;
	constexpr std::uint32_t high_surrogate_value = 0xD800;
	constexpr std::uint32_t low_surrogate_value = 0xDC00;

	constexpr std::uint32_t surrogate_codepoint_offset = 0x10000;
	constexpr std::uint32_t surrogate_codepoint_mask = 0x03FF;
	constexpr std::uint32_t surrogate_codepoint_bits = 10;

	//encountered unicode escape sequence
	std::uint32_t codepoint;

	std::uint32_t high;
	std::from_chars(in, in + 4, high, 0x10);
	in += 4;

	if ((high & generic_surrogate_mask) == generic_surrogate_value) {

		if ((high & surrogate_mask) != high_surrogate_value) return conversion_error;

		//verify that second unicode escape sequence is present
		in += 2;

		std::uint32_t low;
		std::from_chars(in, in + 4, low, 0x10);
		in += 4;

		if ((low & surrogate_mask) != low_surrogate_value) return conversion_error;

		codepoint = (high & surrogate_codepoint_mask) << surrogate_codepoint_bits;
		codepoint |= (low & surrogate_codepoint_mask);
		codepoint += surrogate_codepoint_offset; 
	}
	else {

		codepoint = high;
	}

	//encode unicode codepoint as utf8 and write to output
```

**Comment by arturbac** [comment]
@stephenberry You may want to use even by copy paste using parts of my code for constexpr [utf handling](https://github.com/arturbac/stralgo/blob/master/include/stralgo/utf/utf.h)

**Comment by stephenberry** [comment]
Thanks to both of you for sharing code. Very helpful. I'm also open to pull requests to add this support, otherwise I'll try to get to this added sooner than later.

**Comment by Adam-Vandervorst** [comment]
Upon trying to parse WikiData (https://dumps.wikimedia.org/wikidatawiki/entities/) I ran into this.
Specifically, on the following JSON https://www.wikidata.org/wiki/Special:EntityData/Q125125689.json

**Comment by Adam-Vandervorst** [comment]
In my case, it fails here: https://github.com/stephenberry/glaze/blame/3e98d8c2c5e4c784e3fee18b9643c11d12c09573/include/glaze/util/parse.hpp#L986

**Comment by stephenberry** [comment]
Thanks for pushing this issue. One of my priorities is to add surrogate pair handling and faster unicode support. Will be working on this and will hopefully have support soon.

**Comment by stephenberry** [comment]
All, thanks for bringing unicode surrogate pair support to my attention. I just merged in support. This also significantly improves the prior escaped unicode handling and performance.

Let me know if you run into any issues. Thanks @Clyraz for the pseudo-code, it was very helpful.

**Comment by Adam-Vandervorst** [comment]
Congrats! Glaze can now correctly parse the 1.6TB WikiData JSON dump in 1493 seconds on a single core.

**Comment by stephenberry** [comment]
Excellent! But wow, how do you have enough memory to support a file this big?

**Comment by Adam-Vandervorst** [comment]
I'm streaming the file line by line (the top level is an array). One could also use mmap or pre-processing it by substituting strings with integers.

**Comment by stephenberry** [comment]
Cool, I was just curious. Thanks!
