### ISSUE TITLE
Can't serialzie std::vector<std::pair<...>>

### ISSUE THREAD

**Issue by Haatschii** [stephenberry/glaze#720]
Maybe I missed something and this is not a bug after all, but for some reason glaze won't handle vectors of pairs, although vectors and pairs are supported without explicit metadata?

**MRE:**
```C++
int main ([[maybe_unused]] int argC, [[maybe_unused]] char* argV[] ) {
	const auto x = glz::read_json<std::vector<std::pair<int, int>>>("[{\"1\":2},{\"3\":4}]");
	return 0;
}
```
Fails with:
> glaze/json/read.hpp:77:33: error: static assertion failed: Glaze metadata is probably needed for your type

**Comment by stephenberry** [comment]
In #724 I have added support for reading `std::vector<std::pair...` as you desired. However, I also needed to add an option to handle roundtrip writing.

`std::pair` has special handling in glaze. Not only is `std::pair` used for key/value pairs, but it also works with ranges for writing out concatenated objects from ranges of key/value pairs. So, in your example, the output when writing the same vector will be `{"1":2,"3":4}` (a concatenated object of the key/value pairs). This does not roundtrip and therefore may not be desired.

I have added a compile time option to allow you to avoid concatenating ranges of pairs.

The following unit tests show the behavior and how to use the option to get roundtrip support working:
```c++
"vector pair"_test = [] {
    std::vector<std::pair<int, int>> v;
    expect(!glz::read_json(v, R"([{"1":2},{"3":4}])"));
    static_assert(glz::detail::writable_map_t<decltype(v)>);
    const auto s = glz::write_json(v);
    expect(s == R"({"1":2,"3":4})") << s;
 };
 "vector pair roundtrip"_test = [] {
    std::vector<std::pair<int, int>> v;
    expect(!glz::read_json(v, R"([{"1":2},{"3":4}])"));
    const auto s = glz::write<glz::opts{.concatenate = false}>(v);
    expect(s == R"([{"1":2},{"3":4}])") << s;
 };
```

> For future reference: It may be that we want to make the default roundtrip in the future, but currently the ranges concatenate handling has been more used, and so we'll keep this the default behavior for the foreseeable future to not break existing code.

**Comment by stephenberry** [comment]
I will let you know when I merge this active pull request.

**Comment by stephenberry** [comment]
#724 with support for handling `std::vector<std::pair...` has been merged.
