### ISSUE TITLE
Error parsing flags field if it contains spaces

### ISSUE THREAD

**Issue by omarmed** [stephenberry/glaze#722]
A syntax error occurs when parsing a field of type "Boolean Flags" that contains spaces after "[". 
Ej:

```
struct Sinks {
   bool file = true;
   bool console = false;

   struct glaze {
      using T = Sinks;
      static constexpr auto value = glz::flags("file", &T::file, "console", &T::console);
   };
};  

glaze::read_json<Sinks>(R"([  "file"])"))
```

 fail with syntax_error(10)

**Comment by stephenberry** [comment]
Your simple example here worked, but I just pushed a commit that fixes whitespace handling for more complex, nested cases. So, the error you were seeing should now be gone on the `main` branch. This fix will be in the next release.

Let me know if you run into any more problems. Thanks for pointing this out!

**Comment by omarmed** [comment]
Yes, I'm sorry for oversimplifying the example, that Sinks field actually belongs to another structure and that is where it failed.
Now it works perfectly.
Thank you very much for the library, I find it incredibly useful

**Comment by stephenberry** [comment]
No problem, and I'm glad it's working for you. Thanks for helping make the library better!
