### ISSUE TITLE
File an issue with MSVC for broken static thread_local constinit support

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#728]
MSVC is broken when it comes to `static thread_local constinit`. This is required for reflection to work in some multi-threaded contexts.

**Comment by stephenberry** [comment]
Found a similar issue here and added another comment: https://developercommunity.visualstudio.com/t/thread_local-with-constinit-of-a-constex/10071867?q=thread_local+constexpr

**Comment by Tomcat-42** [comment]
@stephenberry Sorry for necrobumping this, but there's actually a workaround for this? It seems that `nvc++` suffers from the same problem.

**Comment by stephenberry** [comment]
Currently the solution is to not use constinit with MSVC and lose some performance. I'll have to check on the status of the associated issue with MSVC. Are you trying to build glaze with nvc++? I've never tried.
