### ISSUE TITLE
Problem with enum classes in BVE (JSON -> BVE) 

### ISSUE THREAD

**Issue by cian-dev10** [stephenberry/glaze#740]
Hi,

this sample code works with read/write json

```cpp
			enum class sub : uint8_t
			{
				START,
				END,
				UPDATE_ITEM,
				UPDATE_PRICE,
                                ....
                        }; 

                        struct A {
                            sub b;
                            struct glaze {
					using T = A;
					static constexpr auto value = glz::object(
						"b", &T::b
					);
				};
                        };
```

After changing to BVE this behaviour dont work. I could switch to an uint8_t for a easily workaround. Can you have look for that?

Result: 'Glaze metadata is probably needed for your type'

Best regards

**Comment by stephenberry** [comment]
Thanks for pointing out this bug. Will try to fix this sooner than later.
