### ISSUE TITLE
Add Address Sanitizer to GitHub Actions

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#774]
I would like to suggest adding profile with asan build
```
                "CMAKE_C_COMPILER": "clang-17",
                "CMAKE_CXX_COMPILER": "clang++-17",
                "CMAKE_CXX_FLAGS" : "-ggdb -fvisibility=default -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=undefined",
                "CMAKE_EXE_LINKER_FLAGS" : "-fsanitize=address -fsanitize=undefined"
```
And running it always before creating release.

_Originally posted by @arturbac in https://github.com/stephenberry/glaze/issues/773#issuecomment-1955290393_

**Comment by stephenberry** [comment]
@arturbac, do you know how to get the address sanitizer running on a macOS GitHub action? I tried to add address sanitizer flags to the CMake in [this merge request](https://github.com/stephenberry/glaze/pull/777) (#777), but it isn't linking to the address sanitizer. I'm not sure how to link against the address sanitizer library in Clang in my CMake.

**Comment by arturbac** [comment]
I am working on linux, so I just added to Your profile( temporary didn't have time to define CMakeUserProfile from scratch) and used that profile
```
        {
            "name": "dev-release-arturbac",
            "displayName": "Developer Mode",
            "description": "Builds Glaze w/ tests and downloaded test dependencies",
            "generator": "Ninja",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release",
                "glaze_DEVELOPER_MODE": true,
                "BUILD_TESTING": true,
                "CMAKE_EXPORT_COMPILE_COMMANDS": true,
                "CMAKE_C_COMPILER": "clang-17",
                "CMAKE_CXX_COMPILER": "clang++-17",
                "CMAKE_CXX_FLAGS" : "-ggdb -fvisibility=default -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=undefined",
                "CMAKE_EXE_LINKER_FLAGS" : "-fsanitize=address -fsanitize=undefined"
            }
        },
```

**Comment by arturbac** [comment]
You can test directly adding -lasan and -lubsan to linker flags

**Comment by arturbac** [comment]
And one thing to note for using ubsan at github action You probably want it to stop exection and fail, so set ENV
UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1

**Comment by stephenberry** [comment]
Thanks for these tips.

**Comment by arturbac** [comment]
And if asan fail that was not first initialized
ASAN_OPTIONS=check_initialization_order=0
IMO just ignore unless You have plenty of globals that can fail before asan library constructor init or use LD_PRELOAD or add -lasan -lubsan to LINK_FLAGS or something
But they are writting that 
[Note that this option is not supported on macOS.](https://clang.llvm.org/docs/AddressSanitizer.html#initialization-order-checking)

**Comment by stephenberry** [comment]
I think I got it added in #779
