### ISSUE TITLE
Improve error handling for writing

### ISSUE THREAD

**Issue by anaelorlinski** [stephenberry/glaze#847]
I try to use glz::manage to avoid writing some keys on the output. 
My initial goal would be to avoid writing a an array key when the content it empty. (any idea is welcome for this).

However while experimenting I found that the bool return value is not documented on its behavior, and moreover it generates invalid output when set to false.

Here is a small way to reproduce the issue.

```
struct manage_test_struct {
  std::string a;
  std::string b;

  bool read_a() { return true; }
  bool write_a() { return false; } // <-- false here
};

template <>
struct glz::meta<manage_test_struct>
{
   using T = manage_test_struct;
   static constexpr auto value = object(
      "a", manage<&T::a, &T::read_a, &T::write_a>,
      "b", &T::b
   );
   
};

int test2()
{
    manage_test_struct s{.a="aaa", .b="bbb"};
    std::string out{};
    glz::write<glz::opts{.prettify = false}>(s, out);
    std::cout << out << std::endl;
    return 0;
}
```

Returned invalid output : 
```
{"a":,"b":"bbb"}
```

**Comment by stephenberry** [comment]
Thanks for reporting this. I'll look into it.

**Comment by stephenberry** [comment]
This bug you found brings up an issue in Glaze when it comes to handling write errors. Write errors have only existed for files, except for this corner case of `glz::manage`, which are not being returned at the top level. The boolean return was intended to denote whether an error occurred, but this produces a very unhelpful error. I think that it should instead expect a glz::error_code.

Returning write errors is an API breaking change, but one that I think must be done. In the meantime, be aware that returning `false` from a write function using `glz::manage` will not be handled.

Thanks so much for bringing this up. It is motivation to add write error handling sooner than later.

**Comment by stephenberry** [comment]
A note about handling write errors:
There are many cases where calling write cannot produce an error, and so it doesn't make sense to require the write API to always return an `expected`. Instead, I think that the write API should take an optional additional `glz::write_error` by reference, which will be populated if an error occurs. This will keep the API cleaner for many use cases, but allow error handling when it is needed. This is similar to how the asio library handles error codes.

```c++
glz::write_error err{};
auto buffer = glz::write_json<Type>(err);
// or
glz::write_json(value, buffer, err);

if (err) {
   // check for write errors
}
```

**Comment by scalpel4k** [comment]
I think this looks a lot like what I was originally asking for in discussion #674. So sooner rather than later sounds great to me ;-)

**Comment by stephenberry** [comment]
I've decided that it's best to make the write API match the read API. Write errors will be supported soon with the merge of #1053

**Comment by scalpel4k** [comment]
thanks a lot
