### ISSUE TITLE
invalid documentation

### ISSUE THREAD

**Issue by arturbac** [stephenberry/glaze#860]
https://github.com/stephenberry/glaze/blob/main/docs/custom-serialization.md
Is:
```
template <>
   struct to_json<uuid_t>
   {
      template <auto Opts>
      static void op(uuid_t& uuid, auto&&... args) noexcept
```
should be:
```
template <>
   struct to_json<uuid_t>
   {
      template <auto Opts>
      static void op(uuid_t const & uuid, auto&&... args) noexcept
```
or

```
template <>
   struct to_json<uuid_t>
   {
      template <auto Opts>
      static void op(auto && uuid, auto&&... args) noexcept
```
as uuid_t& uuid will fail with concept write_json_invocable when used as const for example std::span<uuid_t const>

I didnt check this uuid_t but my own non trivial class.

**Comment by stephenberry** [comment]
This should not fail if `uuid` is not const, which is necessary in this example because it is modified.

It seems like your use case is different, in that you have a const type, which will need to have a const input.

Let me know if you still think the documentation is wrong, I added a unit test that mimics this behavior and it passes (#863).

**Comment by arturbac** [comment]
I was just struggling to find in documentation example how to support my custom type for any case of it const and non cost, fully.
The error is pointing to some json internals because of sfinae and there is no easy single 
typename<typename T>
concept `my_type_is_json_supported` = ..
to check if my class specialization is valid for json.
So maybe not invalid but not precise/misleading , The most common case for serializing value when using const correctness is T const &, not T &
so using && const & would be IMO better for novice facing library and looking for answers.

**Comment by stephenberry** [comment]
I can add a concept to check if your type is supported. Great idea.

For the writing bit you're right, I'll change it to use `const` in the example.

**Comment by arturbac** [comment]
I was trying to use the concept You have in internals but it is a bit unusable as it requires ctx, iterators and so on

**Comment by stephenberry** [comment]
Yeah, I just created `glz::read_json_supported` and `glz::write_json_supported` concepts that allow you to check much more easily in #864. I'll merge this soon.

**Comment by arturbac** [comment]
All that report is because I am novice to glaze internals and that was my first attempt to specialize, so I unique 'first time' experience of reading documentation and trying it to do. SO I taught it will be valuable to report what caused a bit of delay into getting to point after reading doc and trying it to do.

If You want to make it better I mean doc, example with using base functionality of  embedded types like string view or int and with ctx as argument to report error inside custom specialization like below my use case would be beneficial to new comers.

For example I think I know what I should but can get this to pass concept write_json_invocable/actually use to_json to serialize enums by name
No idea why it fails ..

```
#include <glaze/glaze.hpp>
#include <simple_enum/simple_enum.hpp>
#include <simple_enum/enum_cast.hpp>

namespace glz::detail
  {
template<simple_enum::enum_concept enumeration_type>
struct from_json<enumeration_type>
  {

  template<auto Opts>
  static void op(enumeration_type && rc, is_context auto && ctx, auto &&... args)
    {
    std::string_view value;
    read<json>::op<Opts>(value, ctx, args...);

    if (bool(ctx.error)) [[unlikely]] 
      return;
      
    cxx23::expected<enumeration_type, simple_enum::enum_cast_error> 
    res{ simple_enum::enum_cast<enumeration_type>(value)};
    if(!res.has_value()) [[unlikely]]
      {
      ctx.error = error_code::syntax_error;
      return;
      }
    rc = res.value();
    }
  };
  
template<simple_enum::enum_concept enumeration_type>
struct to_json<enumeration_type>
  {
  template<auto Opts>
  static void op(auto && rc, auto &&... args) noexcept
    {
    std::string_view value {simple_enum::enum_name( rc )};
    write<json>::op<Opts>(value, args...);
    }
  };
enum struct test_enum{};
// template <auto Opts, class T, class Ctx, class B, class IX>
static_assert(write_json_invocable<glz::opts{},test_enum, glz::context, std::string, int>);

```

**Comment by arturbac** [comment]
Ok i know now

Podpowiedź: Because 'to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx), std::forward<B>(b), std::forward<IX>(ix))' would be invalid: ambiguous partial specializations of 'to_json<glz::detail::test_enum>'

**Comment by arturbac** [comment]
> Yeah, I just created `glz::read_json_supported` and `glz::write_json_supported` concepts that allow you to check much more easily in #864. Just merged.

BTw2:
Shouldn't top level functions use those concepts ? Just idea for future ...
```
template <read_json_supported T, class Buffer>
[[nodiscard]] inline expected<T, parse_error> read_json(Buffer&& buffer) noexcept

```

**Comment by stephenberry** [comment]
I do think the top level functions should probably use these concepts, but I'm considering the consequences. It assumes a default `glz::opts`, and specific options could cause your type to be incompatible in different ways. However, I think it is a good idea to require all types to be able to read or write with the default options.

I'll make a branch adding them and try it out. I may also use them in static_asserts so that I can customize the message.

**Comment by stephenberry** [comment]
> All that report is because I am novice to glaze internals and that was my first attempt to specialize, so unique 'first time' experience of reading documentation and trying it to do. SO I taught it will be valuable to report what caused a bit of delay into getting to point after reading doc and trying it to do.
> 
> If You want to make it better I mean doc, example with using base functionality of embedded types like string view or int and with ctx as argument to report error inside custom specialization like below my use case would be beneficial to new comers.
> 
> For example I think I know what I should but can not get this to pass concept write_json_invocable/actually use to_json to serialize enums by name No idea why it fails ..
> 
> ```
> #include <glaze/glaze.hpp>
> #include <simple_enum/simple_enum.hpp>
> #include <simple_enum/enum_cast.hpp>
> 
> namespace glz::detail
>   {
> template<simple_enum::enum_concept enumeration_type>
> struct from_json<enumeration_type>
>   {
> 
>   template<auto Opts>
>   static void op(enumeration_type && rc, is_context auto && ctx, auto &&... args)
>     {
>     std::string_view value;
>     read<json>::op<Opts>(value, ctx, args...);
> 
>     if (bool(ctx.error)) [[unlikely]] 
>       return;
>       
>     cxx23::expected<enumeration_type, simple_enum::enum_cast_error> 
>     res{ simple_enum::enum_cast<enumeration_type>(value)};
>     if(!res.has_value()) [[unlikely]]
>       {
>       ctx.error = error_code::syntax_error;
>       return;
>       }
>     rc = res.value();
>     }
>   };
>   
> template<simple_enum::enum_concept enumeration_type>
> struct to_json<enumeration_type>
>   {
>   template<auto Opts>
>   static void op(auto && rc, auto &&... args) noexcept
>     {
>     std::string_view value {simple_enum::enum_name( rc )};
>     write<json>::op<Opts>(value, args...);
>     }
>   };
> enum struct test_enum{};
> // template <auto Opts, class T, class Ctx, class B, class IX>
> static_assert(write_json_invocable<glz::opts{},test_enum, glz::context, std::string, int>);
> ```

Thanks for your feedback and I can't immediately see an issue with this code. It might have partial template specialization ambiguity with glaze's enum concepts. I'll have to look at it more later.

**Comment by arturbac** [comment]
I have always approach to templates to narrow down error as fast as possible, prevent calling template as soon as possible. As top constraints give nice error message and point to user code, while deep very often even don't point to user code error line .. **and this is as case of static_assert(false_v<T> in glaze**.
Absolutely hard to find place in my code where I made mistake as error refers to only glaze code and the only clue is a type on template after many <false,false.... opts ..

**Comment by arturbac** [comment]
> It might have partial template specialization ambiguity with glaze's enum concepts
Yes it is that case, and I have no idea how to solve even by trick or hack it ..

**Comment by stephenberry** [comment]
> I have always approach to templates to narrow down error as fast as possible, prevent calling template as soon as possible. As top constraints give nice error message and point to user code, while deep very often even don't point to user code error line .. **and this is as case of static_assert(false_v in glaze**. Absolutely hard to find place in my code where I made mistake as error refers to only glaze code and the only clue is a type on template after many <false,false.... opts ..

If we static_assert higher up in the template chain then it isn't so deep, but I agree that concept errors at the top level are the cleanest, just not always clear to the user.

**Comment by stephenberry** [comment]
> > It might have partial template specialization ambiguity with glaze's enum concepts
> 
> Yes it is that case, and I have no idea how to solve even by trick or hack it ..

@arturbac, note this code:
```c++
// Allows developers to add `static constexpr auto custom_read = true;` to their glz::meta to prevent ambiguous
// partial specialization for custom parsers
template <class T>
concept custom_read = requires { meta<T>::custom_read == true; };

template <class T>
concept custom_write = requires { meta<T>::custom_write == true; };
```

If you create a glz::meta with `custom_read = true;` then this will allow you to avoid the partial specialization ambiguity.

**Comment by arturbac** [comment]
Thx, tried it fast
And it solves ambiguity, passes below concepts checks and fails with both with static_assertswhen i try to use enum on struct , will try to understand later.
```
template<typename T>
concept read_json_supported = glz::detail::
  read_json_invocable<glz::opts{}, std::add_lvalue_reference<T>, glz::context &, char const * &, char const * &>;

template<typename T>
concept write_json_supported = detail::
  write_json_invocable<glz::opts{}, std::add_const_t<std::add_lvalue_reference<T>>, glz::context &, std::string &, size_t &>;
```

**Comment by arturbac** [comment]
I have small repro case and don't undestand why it passes first write_json_invocable and fails at second

[include/simple_enum/glaze_json_enum_name.hpp](https://github.com/arturbac/simple_enum/blob/glaze_support/include/simple_enum/glaze_json_enum_name.hpp)
[tests/glaze_enum_name_ut.cc](https://github.com/arturbac/simple_enum/blob/glaze_support/tests/glaze_enum_name_ut.cc)

order as from normal compilation reversed 
```
if constexpr (write_json_invocable<Opts, T, Ctx, B, IX>) {
               to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                                  std::forward<B>(b), std::forward<IX>(ix));
error: static assertion failed due to requirement 'false_v<const test_enum_e &>': Glaze metadata is probably needed for your type
te T type is from get_member(value, member) and it is  test_enum_e const &

// OK no test
write<json>::op<Opts>(get_member(value, member), ctx, b, ix);
glz::detail::write<10>::op<opts{}, const test_enum_e &, glz::context &, std::string &, unsigned long &>

// Goes thru op_base<write_unknown_on<Options>()>(std::forward<V>(value), ctx, b, ix);
glz::detail::to_json<test_data_t>::op_base<opts{}, const test_data_t &, glz::context &, std::string &, unsigned long &>

//OK test if constexpr (write_json_invocable<Opts, T, Ctx, B, IX>) {
glz::detail::to_json<test_data_t>::op<opts{}, const test_data_t &, glz::context &, std::string &, unsigned long &>
```
