### ISSUE TITLE
Map of quoted numbers

### ISSUE THREAD

**Issue by RozeFound** [stephenberry/glaze#869]
Quick question, is it possible to parse object into a map with quoted numbers?
Basically, I have a schema like this:
```jsonc
"combos": {
	 "type": "object",
	"properties": {
		"MODE": {
			"type": "integer"
		},
		"DIRECTION": {
			"type": "integer"
	} // and 20 more entries like this
}
```
And in code I need these integers as strings. It's not a big deal to convert it in place, but would be nice to have the ability to do such while parsing.

**Comment by stephenberry** [comment]
Yes, here is code for a strongly typed solution: https://gcc.godbolt.org/z/sxoKn654x

```c++
#include <iostream>

#include "glaze/glaze.hpp"

struct entry_t
{
    int type{};
};

template <>
struct glz::meta<entry_t> {
    using T = entry_t;
    static constexpr auto value = object("type", quoted_num<&T::type>);
};

struct properties_t
{
    entry_t MODE{};
    entry_t DIRECTION{};
};

struct combos_t
{
    std::string type = "object";
    properties_t properties{};
};

int main() {
    combos_t combos{};
    std::cout << glz::write_json(combos) << '\n';
    return 0;
}
```

I'm showing writing here, but reading works the same way.

**Comment by stephenberry** [comment]
You can also use `glz::quoted_num` around containers like `std::vector` and `std::map` for more dynamic solutions.

**Comment by RozeFound** [comment]
My bad for not giving clear information. The schema in question is quite _literally_ [schema](http://json-schema.org/schema).

The actual json looks more like this
```json
"pass": {
	"id": 1,
	"combos": {
		"MODE": 2,
		"DIRECTION": 3
	}
}
```
And structure in code like

```cpp
struct Pass {
	int id;
	std::unordered_map<std::string, std::string> combos;
}
```

I tried to to use `glz::quoted_num` in meta
```cpp
template <> struct glz::meta<Pass> {
	using T = objects::Pass;
	static constexpr auto value = object(
		"id", &T::id,
		"combos", glz::quoted_num<&T::combos>
	);
};
```
But all it gave me is an error
```
142:22: syntax_error
                                                                "VERTICAL" : 1
                        ^
```

**Comment by RozeFound** [comment]
Oh, so I misunderstood how `glz::quoted_num` works...
I thought it can parse normal integers into string, but it parses strings into normal integers

**Comment by RozeFound** [comment]
Yeah I found now that you can use `glz::number` to get the desired result, but it wasn't documented basically nowhere (except for compile time options, which doesn't make it obvious that you can use it outside of said options), which led to this issue.

**Comment by stephenberry** [comment]
Yeah, `glz::quoted_num` treats an underlying integer as a string in JSON.

Instead of handing your combos object as `std::unordered_map<std::string, std::string>`, use `std::unordered_map<std::string, int>`.

Your goal was to not have to convert the strings to integers in place, right? Using `int` in your map and `glz::quoted_num` should solve your problem.

**Comment by RozeFound** [comment]
Sorry to confuse you so much. My original goal was to treat json INTEGERS as STRINGS, not the other way around

**Comment by stephenberry** [comment]
> Sorry to confuse you so much. My original goal was to treat json INTEGERS as STRINGS, not the other way around

No problem at all. It helps reveal where the documentation is lacking/needing improvement.

**Comment by RozeFound** [comment]
> The wrappers are documented in brief here: [main/docs/wrappers.md#available-wrappers](https://github.com/stephenberry/glaze/blob/main/docs/wrappers.md?rgh-link-date=2024-03-25T14%3A55%3A12Z#available-wrappers)

I did read this file, but I wasn't sure if I can use these on containers, and at the moment I tried to, I already forgot about the listed options and stick to the one highlighted in readme which was the quoted one.

**Comment by stephenberry** [comment]
Understandable, I think adding easy to read examples will be the most helpful. I'll make a documentation issue to add examples for the wrappers.

**Comment by stephenberry** [comment]
@RozeFound, yes this weird error format should be an issue. Can you share a small piece of code that generates this weird formatting? The C++ structs, glaze stuff, and the input string.

**Comment by RozeFound** [comment]
I created a little extremely stripped down test chamber, [link](https://pastes.io/dqddtiumrr)

**Comment by RozeFound** [comment]
I assume the problem is tabs in json string

**Comment by stephenberry** [comment]
Ah, you're right. I never tested formatting errors with tabs in the JSON. Thanks for your example. Because tabs don't always have consistent output width, I think I'll probably update the code to take the error snippet and convert tabs to spaces for printing the error. This should allow consistent error output that is formatted properly.

**Comment by stephenberry** [comment]
Formatting of errors with tabs is handled in #877 

> In the formatter error output, we now convert tabs to single spaces. This allows consistent output and properly formatted errors when tabs occur. We only convert to single spaces to keep the context code cleaner and avoid more allocations.

**Comment by stephenberry** [comment]
Yeah, I agree with you that the new line shouldn't be there at the end, per how things are usually done. I'll remove it.

**Comment by RozeFound** [comment]
Anyway, this issue is getting rather long, and offtopic, I'll close it
Have a nice day!
