### ISSUE TITLE
Unexpected and inconsistent behaviour with std::filesystem::path

### ISSUE THREAD

**Issue by dbraeckelmann** [stephenberry/glaze#888]
I observed some really confusing and inconsistent behaviour when trying to deserialize a `std::filesystem::path` struct member

CXX compiler is MSVC 19.39.33523.0 (Visual Studio 2022 v17.9.5)
C++ Standard Library 14.39.33519 / Windows SDK 10.0.22621.0 on Windows 10.0.19045.

The following does not compile with this compiler error:
`glaze-src\include\glaze\reflection\to_tuple.hpp(70,25): error C3448: the number of identifiers must match the number of array elements or members in a structured binding declaration`

```CPP
struct test_struct {
    uint32_t i {0};
    std::filesystem::path p {"."};
};
constexpr static auto json = R"({"i": 1, "p": "C:/123"})";

auto test = glz::read_json<test_struct>(json);
```

The next code variation does compile but does not work:

```CPP
struct test_struct {
    std::filesystem::path p {"."};
};
constexpr static auto json = R"({"p": "C:/123"})";

auto test = glz::read_json<test_struct>(json);
```

```
JSON parse error (22): 1:2: unknown_key
   {"p": "C:\123"}
    ^
```

If I introduce a custom deserializer for `std::filesystem::path` as follows the code compiles but still does not deserialize the path correctly
```CPP
namespace glz::detail {
template<> struct from_json<std::filesystem::path> {
    template <auto Opts>
    static void op(std::filesystem::path& path, auto&&... args) {
        std::string str;
        read<json>::op<Opts>(str, args...);
        path = std::filesystem::path {str};
    }
};
}
```

Only after I introduce an explicit `glz::meta` struct combined with the custom deserializer, it works as intended:
```CPP
struct test_struct
{
    std::filesystem::path p {"."};
    struct glaze {
        static constexpr auto value = glz::object(&test_struct::p);
    };
};
```

Having the explicit `glz::meta` but without providing the custom deserializer, I get this compiler error: 
`glaze-src\include\glaze\json\read.hpp(974,34): error C2039: 'size': is not a member of 'std::filesystem::path'`

Finally, wrapping the `std::filesystem::path` in a container like `std::vector` or `std::optional` it all compiles and works as intended while providing the custom deserializer but having no explicit `glz::meta`:

```CPP
struct test_struct
{
    std::optional<std::filesystem::path> p {"."};
}
```

**Comment by stephenberry** [comment]
Thanks for bringing this up. I've never tested/used `std::filesystem::path` with Glaze, but it should definitely be supported. Thanks for providing a detailed analysis. I'll look into this more soon.

**Comment by stephenberry** [comment]
@dbraeckelmann, support has been added for `std::filesystem::path`. However, this support requires its use in glaze metadata (e.g. glz::meta) on GCC and MSVC. I could not get pure reflection to work in GCC and MSVC, which seem like bugs with aggregate initialization of structs with `std::filesystem::path`.
