### ISSUE TITLE
JSON pointer (get_as_json) failing on array of objects

### ISSUE THREAD

**Issue by dbraeckelmann** [stephenberry/glaze#922]
Glaze v2.5.1
CXX compiler is MSVC 19.39.33523.0 (Visual Studio 2022 v17.9.5)
C++ Standard Library 14.39.33519 / Windows SDK 10.0.22621.0 on Windows 10.0.19045.

Using following test code:

```
std::string_view data = R"({ "data": [ {"a": true} ] })";

int main() {
  auto a = glz::get_as_json<bool, "/data/0/a">(data);
  if(a.has_value()) {
    std::println("a: {}", a.value());
  } else {
    std::println("Parse Error: {}", glz::format_error(a.error(), data));
  }
}
```

Expected output: `a: true`
Actual output:
```
Parse Error: 1:24: syntax_error
   { "data": [ {"a": true} ] }
                          ^
```

I also noticed, that get_as_json accepts malformed JSON:
```
std::string_view data_b = R"({ "data": { "b": [ true} ] })";

int main() {
  auto b = glz::get_as_json<bool, "/data/b/0">(data_b);

  if(b.has_value()) {
    std::println("b: {}", b.value());
  } else {
    std::println("Parse Error: {}", glz::format_error(b.error(), data_b));
  }
}
```

It should yield a syntax error (or be documented that the JSON pointer implementation does not check for a well-formed input), instead it prints the value: `b: true`

**Comment by stephenberry** [comment]
Thanks for pointing out these issues, will look into ASAP.

**Comment by stephenberry** [comment]
I've fixed the issue with using a JSON pointer that has an intermediate array access in #923. I've also majorly improved the error handling.

Concerning accepting ill-formed JSON:
Glaze will error on any ill formed JSON prior to the value you are reading. Anything beyond the value you are reading is not validated. Consider that you might want to read the first field of a 1 GB file, it wouldn't make any sense to validate the entire file after we parsed a few bytes to get the field we wanted. I will add documentation to describe this behavior.

Let me know if you have further thoughts about this partial parsing.

**Comment by dbraeckelmann** [comment]
Hey Steven, thanks for addressing this so extremely quickly, appreciated!

I think it's totally reasonable to only partially parse the JSON up until to the location pointed to; just found it quite interesting when I spotted my typo in the test and thought to myself: hmm that doesn't look quite right. The way you documented it now looks perfectly fine to me!

**Comment by dbraeckelmann** [comment]
Just a quick question as I encountered this the other day: Would it be possible to have the same functionality as get_as_json but with a runtime string_view as json_ptr instead of a template parameter? 
Maybe I just missed it already being present, but it looked to me as this was not implemented yet. Our codebase has quite a few runtime-dependant JSON root-keys like:

```JSON
{
    "root_key_1": {},
    "root_key_2": {}
}
``` 

What I currently do is extract these by parsing it as `json_t` and then re-parse just the root-key into the fixed structure it represents, not really a deal-breaker but also no incredibly elegant. As it is just configuration files (the runtime-dependant keys are config for dynamically loaded plugins) that are loaded during startup the performance aspect for this case is completely irrelevant, but maybe there already is a better way to do this?

**Comment by stephenberry** [comment]
Interesting, thanks for sharing your use case. Are you aware of `glz::raw_json`? If you know the names of your root keys you can have a struct with `glz::raw_json`, which will parse the JSON into an underlying string that you can then parse into your fixed structure that it represents.

**Comment by dbraeckelmann** [comment]
Oh, I see - thanks for pointing that out, must have looked over it previously. Maybe you could reference raw_json on the generic-json docs page? Currently it's quite well hidden when you don't know where to look at.

Unfortunately I only know the root keys once the program has started up (the plugins are part of the core configuration in the same file); I'm arguing with myself back and forth if it maybe makes sense to split the file into one for the core configuration and on for the plugins to avoid this kind of problem all together.

**Comment by stephenberry** [comment]
Good idea, I'll document glz::raw_json in the generic-json docs. Thanks!
