### ISSUE TITLE
Default Constructors breaking write_json Method

### ISSUE THREAD

**Issue by maldag** [stephenberry/glaze#936]
I was in the need of a custom constructor for a dataclass, so I was constructing the default constructors based on the rule of six. But with all defaulted constructors it does not compile anymore. Am I missing something here? https://gcc.godbolt.org/z/feesG1v65

The original example I was working on was the following using template inheritance which required a custom constructor for the templated message: https://gcc.godbolt.org/z/5ev3W7njz

**Comment by stephenberry** [comment]
Adding constructors makes the class not aggregate initializable, and therefore you need to supply a `glz::meta` to enable serialization/deserialization. See the documentation about [pure reflection here](https://github.com/stephenberry/glaze/blob/main/docs/pure-reflection.md)

The [README](https://github.com/stephenberry/glaze/blob/main/README.md) has more about `glz::meta` or local metadata.

When we get compile time reflection in the C++ language we'll then be able to handle constructors with pure reflection.

**Comment by maldag** [comment]
Thanks for the support.
