### ISSUE TITLE
The executable glaze_ide is built but not installed

### ISSUE THREAD

**Issue by yurivict** [stephenberry/glaze#959]
The development mode should probable be disabled in releases.
Or it should be based on an environment variable instead so that regular users wouldn't be affected.

Version: 2.5.5

**Comment by stephenberry** [comment]
The developer mode is only enabled if the library is the top level (or the only thing built). If you include Glaze in your project then it won't be in developer mode.

If you're having an issue with it in developer mode when used in your project, let me know.

**Comment by yurivict** [comment]
It's not a not a big problem.
Thanks for your clarification.
