### ISSUE TITLE
ASIO REPE example bad file descriptor error

### ISSUE THREAD

**Issue by SiebrenW** [stephenberry/glaze#985]
In the repe_client test application I couldn't get the client to work without reporting the bad file descriptor error.
I figured that this is because the connect is called after set_option in asio_client::init().
Putting the set_option to the end did fix it, but I would like to know what the idea was with this, since I'm not sure whether or how this worked before.

This is regarding this line: https://github.com/stephenberry/glaze/blob/main/include/glaze/ext/glaze_asio.hpp#L109

I rewrote it to something like this to fix it on my end:

```cpp
      [[nodiscard]] std::error_code init()
      {
         ctx = std::make_shared<asio::io_context>(concurrency);
         socket = std::make_shared<asio::ip::tcp::socket>(*ctx);
         asio::ip::tcp::resolver resolver{*ctx};
         const auto endpoint = resolver.resolve(host, service);
         std::error_code ec{};
         asio::connect(*socket, endpoint, ec);
         if (ec) {
            return ec;
         }
         return socket->set_option(asio::ip::tcp::no_delay(true), ec);
      }
```

**Comment by stephenberry** [comment]
Thanks so much for bringing this up and explaining a fix. I'll look into it.

**Comment by stephenberry** [comment]
Your solution seems great, so I made the change and merged it in. FYI, I will be working more on the REPE/asio networking in the future, but it is not my highest priority currently.
