### ISSUE TITLE
minify_json compiler errors when including header directly

### ISSUE THREAD

**Issue by scalpel4k** [stephenberry/glaze#987]
I've noticed that when I use glz::minify_json via code completion, the <glaze/json/minify.hpp> header gets included. Compiling the code then will give a couple of output_buffer errors.

Removing the header mitigates the problem.

**Comment by stephenberry** [comment]
Strange, could you supply a simple example that causes this compilation issue? You can use compiler explorer with Glaze if you don't want to set up a project.

**Comment by scalpel4k** [comment]
`
#include <glaze/json/minify.hpp> // the include order is the problem
#include <glaze/json/write.hpp>
#include <iostream>

struct Test {
  int val1{0};
  bool val2{false};
};

int main(int argc, const char **argv) {
  Test i;
  std::string serialized = glz::write_json(i);
  std::cout << serialized << '\n' << glz::minify_json(serialized) << std::endl;
  return 0;
}`

clangd is sorting the includes in the above order which happens to be the source of error. output_buffer is unknown when including the minify header before the write header. Reversing the include order fixes the problem.

**Comment by stephenberry** [comment]
I moved the `output_buffer` concept to the lower level `container_concepts.hpp`, so this bug should be fixed. Let me know if it pops up still.

**Comment by stephenberry** [comment]
Excellent! Thanks for pointing this out.
