### ISSUE TITLE
Function signatures inconsistency between write_file_json and read_file_json

### ISSUE THREAD

**Issue by melg8** [stephenberry/glaze#989]
1. read_file_json takes string view as file name argument, while write_file_json only takes std::string which is less useful. write_file_json should also take string_view as argument for file name, so more types can be used with function without need of conversion to std::string.
2. write_file_json is marked as [[nodiscard]] inline write_error, while read_file_json has only inline parse_error. read_file_json should also be marked [[nodiscard]], so they both report error if user forgot to handle returning value.

**Comment by stephenberry** [comment]
Thanks for this. You could make a pull request, or I'll get to this next week.

**Comment by stephenberry** [comment]
@melg8, I've merged your requested changes. Thanks for the feedback.

> Note that the `file_name` buffer must be null terminated. I was using `std::string` before for more safety, but I think the flexibility of `std::string_view` is more important. However, it is now up to the user to ensure that the `file_name` is null terminated.
